---
sidebar: sidebar 
permalink: cli-upgrade-esxi.html 
keywords: administer, administering, cli, esxi, upgrade, esxi 8.0 
summary: Wenn Sie ONTAP Select auf VMware ESXi ausführen, können Sie die ESXi-Software von einer früheren unterstützten Version auf ESXi 8.0 oder höher aktualisieren. Vor dem Upgrade sollten Sie den Prozess verstehen und das entsprechende Upgrade-Verfahren auswählen. 
---
= Führen Sie ein Upgrade auf VMware ESXi 8.0 oder höher durch, um ONTAP Select zu nutzen.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie ONTAP Select auf VMware ESXi ausführen, können Sie die ESXi-Software von einer früheren unterstützten Version auf ESXi 8.0 oder höher aktualisieren. Vor dem Upgrade sollten Sie den Prozess verstehen und das entsprechende Upgrade-Verfahren auswählen.



== Bereiten Sie das Upgrade von VMware ESXi vor.

Bereiten Sie das für Ihre Umgebung geeignete Upgrade-Verfahren vor und wählen Sie es aus, bevor Sie die ESXi-Software auf den Hypervisoren aktualisieren, die einen ONTAP Select -Cluster hosten.

.Schritte
. *Machen Sie sich mit dem Upgrade von VMware ESXi vertraut*
+
Das Upgrade der ESXi-Software ist ein von VMware geschriebenes und unterstütztes Verfahren. Das Hypervisor-Upgrade ist Teil des umfassenderen Upgrade-Verfahrens bei der Verwendung von ONTAP Select. Weitere Informationen finden Sie in der VMware-Dokumentation.

. *Wählen Sie ein Upgrade-Verfahren aus*
+
Es stehen mehrere Upgrade-Verfahren zur Verfügung. Sie sollten das zutreffende Verfahren anhand der folgenden Kriterien auswählen:

+
** ONTAP Select
+
Es werden sowohl Einzelknoten- als auch Mehrknotencluster unterstützt.

** Verwendung von ONTAP Select Deploy
+
Ein Upgrade ist sowohl mit als auch ohne das Deploy-Dienstprogramm möglich.

+

TIP: Sie sollten ein Upgrade-Verfahren auswählen, das das Dienstprogramm Administration bereitstellen verwendet.

+
Die Durchführung eines ESXi-Upgrades mit dem Deploy-Verwaltungsprogramm ist die allgemeinere und zuverlässigere Option. Es kann jedoch Fälle geben, in denen Deploy nicht verfügbar oder nicht nutzbar ist. Beispielsweise wird ein Upgrade auf ESXi 8.0 mit früheren Versionen von ONTAP Select und dem Deploy-Verwaltungsprogramm nicht unterstützt.

+
Wenn Sie diese früheren Versionen verwenden und ein Upgrade versuchen, kann die virtuelle ONTAP Select-Maschine in einem Zustand belassen werden, in dem sie nicht gestartet werden kann. In diesem Fall müssen Sie ein Upgrade-Verfahren auswählen, das nicht Bereitstellung verwendet. Siehe link:https://mysupport.netapp.com/site/bugs-online/product/ONTAPSELECT/BURT/1172198["1172198"^] Finden Sie weitere Informationen.



. *Aktualisieren Sie das Deploy-Verwaltungsprogramm*
+
Bevor Sie ein Upgrade mit dem Deploy-Dienstprogramm durchführen, müssen Sie möglicherweise Ihre Deploy-Instanz aktualisieren. Im Allgemeinen sollten Sie auf die neueste Version von Deploy aktualisieren. Das Deploy-Dienstprogramm muss die von Ihnen verwendete Version von ONTAP Select unterstützen.  Siehe dielink:reference_release_notes.html["ONTAP Select – Versionshinweise"] für weitere Informationen.

. *Nach Abschluss des Aktualisierungsvorgangs*
+
Wenn Sie ein Upgrade-Verfahren auswählen, bei dem das Deploy-Utility verwendet wird, sollten Sie eine Cluster-Aktualisierung mit Deploy durchführen, nachdem alle Nodes aktualisiert wurden. Weitere Informationen finden Sie unter Aktualisieren der Implementierungscluster-Konfiguration.





== Upgrade eines Single-Node-Clusters mit Implementierung

Sie können das Deploy Administration Utility im Rahmen des Verfahrens zum Upgrade des VMware ESXi-Hypervisors verwenden, der ein ONTAP Select Single-Node-Cluster hostet.

.Schritte
. Melden Sie sich in der CLI des Bereitstellungsdienstprogramms mithilfe von SSH mit dem Administratorkonto an.
. Versetzen Sie den Knoten in den Offline-Status:
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. Aktualisieren Sie den Hypervisor-Host, auf dem ONTAP Select ausgeführt wird, mithilfe des von VMware bereitgestellten Verfahrens auf ESXi 8.0 oder höher.
. Versetzen Sie den Knoten in den Online-Status:
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. Vergewissern Sie sich, dass sich nach dem Einrichten des Node ein ordnungsgemäßen Zustand des Clusters befindet.
+
Beispiel:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.Nachdem Sie fertig sind
Sie sollten einen Cluster-Aktualisierungsvorgang mit dem Deploy Administration Utility durchführen.



== Upgrade eines Multi-Node-Clusters mit Implementierung

Sie können das Deploy Administration Utility im Rahmen des Verfahrens zum Upgrade der VMware ESXi Hypervisoren verwenden, die ein ONTAP Select Multi-Node-Cluster hosten.

.Über diese Aufgabe
Sie müssen dieses Upgrade-Verfahren für jeden der Nodes im Cluster, jeweils einen Node, durchführen. Wenn das Cluster vier oder mehr Nodes enthält, sollten Sie die Nodes in jedem HA-Paar nacheinander aktualisieren, bevor Sie zum nächsten HA-Paar wechseln.

.Schritte
. Melden Sie sich in der CLI des Bereitstellungsdienstprogramms mithilfe von SSH mit dem Administratorkonto an.
. Versetzen Sie den Knoten in den Offline-Status:
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. Aktualisieren Sie den Hypervisor-Host, auf dem ONTAP Select ausgeführt wird, mithilfe des von VMware bereitgestellten Verfahrens auf ESXi 8.0 oder höher.
+
Weitere Informationen finden Sie unter Vorbereiten des Upgrades von VMware ESXi.

. Versetzen Sie den Knoten in den Online-Status:
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. Vergewissern Sie sich, dass nach dem Einrichten des Node ein Storage-Failover aktiviert ist und sich das Cluster in einem ordnungsgemäßen Zustand befindet.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.Nachdem Sie fertig sind
Sie müssen für jeden im ONTAP Select Cluster verwendeten Host das Upgrade durchführen. Nachdem alle ESXi-Hosts aktualisiert wurden, sollten Sie mithilfe des Deploy-Administration-Dienstprogramms eine Cluster-Aktualisierung durchführen.



== Upgrade für ein Single-Node-Cluster ohne Implementierung

Sie können einen VMware ESXi Hypervisor, der ein ONTAP Select Single-Node Cluster hostet, ohne mithilfe des Deploy-Administration Utility aktualisieren.

.Schritte
. Melden Sie sich bei der ONTAP Befehlszeilenschnittstelle an und beenden Sie den Knoten.
. Vergewissern Sie sich mithilfe von VMware vSphere, dass die ONTAP Select Virtual Machine ausgeschaltet ist.
. Aktualisieren Sie den Hypervisor-Host, auf dem ONTAP Select ausgeführt wird, mithilfe des von VMware bereitgestellten Verfahrens auf ESXi 8.0 oder höher.
+
Weitere Informationen finden Sie unter Vorbereiten des Upgrades von VMware ESXi.

. Greifen Sie mit VMware vSphere auf vCenter zu und führen Sie folgende Schritte aus:
+
.. Fügen Sie der virtuellen ONTAP Select-Maschine ein Diskettenlaufwerk hinzu.
.. Schalten Sie die virtuelle ONTAP Select-Maschine ein.
.. Melden Sie sich über SSH mit dem Administratorkonto bei der ONTAP-CLI an.


. Vergewissern Sie sich, dass sich nach dem Einrichten des Node ein ordnungsgemäßen Zustand des Clusters befindet.
+
Beispiel:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.Nachdem Sie fertig sind
Sie sollten einen Cluster-Aktualisierungsvorgang mit dem Deploy Administration Utility durchführen.



== Upgrade eines Multi-Node-Clusters ohne Implementierung

Die VMware ESXi Hypervisoren, die ein ONTAP Select Multi-Node Cluster hosten, können ohne mithilfe des Deploy Administration Utility aktualisiert werden.

.Über diese Aufgabe
Sie müssen dieses Upgrade-Verfahren für jeden der Nodes im Cluster, jeweils einen Node, durchführen. Wenn das Cluster vier oder mehr Nodes enthält, sollten Sie die Nodes in jedem HA-Paar nacheinander aktualisieren, bevor Sie zum nächsten HA-Paar wechseln.

.Schritte
. Melden Sie sich bei der ONTAP Befehlszeilenschnittstelle an und beenden Sie den Knoten.
. Vergewissern Sie sich mithilfe von VMware vSphere, dass die ONTAP Select Virtual Machine ausgeschaltet ist.
. Aktualisieren Sie den Hypervisor-Host, auf dem ONTAP Select ausgeführt wird, mithilfe des von VMware bereitgestellten Verfahrens auf ESXi 8.0 oder höher.
. Greifen Sie mit VMware vSphere auf vCenter zu und führen Sie folgende Schritte aus:
+
.. Fügen Sie der virtuellen ONTAP Select-Maschine ein Diskettenlaufwerk hinzu.
.. Schalten Sie die virtuelle ONTAP Select-Maschine ein.
.. Melden Sie sich über SSH mit dem Administratorkonto bei der ONTAP-CLI an.


. Vergewissern Sie sich, dass nach dem Einrichten des Node ein Storage-Failover aktiviert ist und sich das Cluster in einem ordnungsgemäßen Zustand befindet.
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.Nachdem Sie fertig sind
Sie müssen für jeden im ONTAP Select Cluster verwendeten Host das Upgrade durchführen.
