---
sidebar: sidebar 
permalink: concept_lic_production.html 
keywords: license, licensing, production, purchased, standard, premium, premium xl 
summary: Nachdem Sie festgestellt haben, dass ONTAP Select für Ihr Unternehmen geeignet ist, können Sie die für eine Implementierung in einer Produktionsumgebung erforderlichen Lizenzen erwerben. Sie müssen entweder das Lizenzmodell für die Kapazitäts-Tiers oder den Kapazitäts-Pool und die Storage-Kapazität für jede Bereitstellung auswählen. 
---
= Von ONTAP Select erworbene Lizenzen für die Implementierung in der Produktion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie festgestellt haben, dass ONTAP Select für Ihr Unternehmen geeignet ist, können Sie die für eine Implementierung in einer Produktionsumgebung erforderlichen Lizenzen erwerben. Sie müssen entweder das Lizenzmodell für die Kapazitäts-Tiers oder den Kapazitäts-Pool und die Storage-Kapazität für jede Bereitstellung auswählen.



== Gemeinsame Lizenzierungsmerkmale

Die Lizenzierungsmodelle _Capacity Tiers_ und _Capacity Pools_ unterscheiden sich in mehrfacher Hinsicht sehr. Die beiden Lizenzmodelle haben jedoch verschiedene gemeinsame Merkmale:

* Bei der Implementierung von ONTAP Select in einer Produktionsumgebung müssen Sie mindestens eine Lizenz erwerben.
* Die Speicherkapazität einer Lizenz wird in Schritten von 1 TB zugewiesen.
* Die Speicherkapazität identifiziert die Rohkapazität und entspricht der zulässigen Gesamtgröße der für die ONTAP Select Virtual Machine verfügbaren Datenfestplatten.
* Es werden alle Angebote für Plattformlizenzen unterstützt (Standard, Premium, Premium XL).
* Wenden Sie sich bei dem Erwerb der erforderlichen Lizenzen an Ihr NetApp Account Team oder Ihren Partner.
* Sie müssen die Lizenzdateien in das Deploy Administration Utility hochladen, das dann die Lizenzen basierend auf dem Lizenzmodell anwendet.
* Nach der Installation und anwenden einer Lizenz können Sie weitere Kapazitäten hinzufügen, indem Sie sich an Ihr NetApp Account Team oder Ihren Partner wenden, um eine aktualisierte Lizenz zu beschaffen.
* Beide Nodes in einem HA-Paar müssen den gleichen Storage und die gleiche Lizenzkapazität aufweisen.
* Ein ONTAP Select-Node, der ursprünglich mit einer erworbenen Lizenz implementiert wird, kann nicht in eine Evaluierungslizenz umgewandelt werden.




== Lizenzmodell für Kapazitäts-Tiers

Das Lizenzmodell für Kapazitäts-Tiers zeichnet sich durch verschiedene Merkmale aus, darunter:

* Für jeden ONTAP Select Node müssen Sie eine Lizenz erwerben.
* Sie können mindestens 1 TB kaufen.
* Jede Capacity-Tier-Lizenz verfügt über eine Speicherkapazität und ist an einen bestimmten Node gebunden.
* Für jeden ONTAP Select Node wird von NetApp eine neunstellige Lizenzseriennummer generiert.
* Der einem Node zugewiesene Storage ist unbefristet (keine Verlängerung erforderlich).
* Die Node-Seriennummer ist neun Ziffern und entspricht der Lizenz-Seriennummer.
* Sie können die Lizenzdatei während der Cluster-Bereitstellung oder innerhalb von 30 Tagen nach dem Erstellen eines Clusters anwenden.




== Lizenzmodell für Kapazitäts-Pools

Das Kapazitäts-Pools-Lizenzmodell bietet verschiedene Merkmale, darunter:

* Sie müssen für jeden Pool mit gemeinsam genutzter Kapazität eine Lizenz erwerben.
* Sie können mindestens 2 TB kaufen.
* Jede Capacity Pool-Lizenz verfügt über eine Speicherkapazität und ist an eine bestimmte License Manager-Instanz gebunden.
* Für jeden Kapazitäts-Pool wird von NetApp eine neunstellige Lizenzseriennummer generiert.
* Der einem Kapazitäts-Pool zugewiesene Storage ist nur für einen bestimmten Zeitraum gültig, der auf dem Kauf basiert (Verlängerung erforderlich).
* Die Seriennummer des Node ist zwanzig Ziffern und wird vom License Manager auf Basis der Lizenznummer des Kapazitäts-Pools generiert.
* Jeder Node vermietet automatisch Storage-Kapazität für seine lokalen Datenaggregate aus einem Pool gemeinsam genutzter Kapazität.


Weitere Informationen zum Lizenzierungsmodell für Kapazitätspools finden Sie im „_Capacity Pools“-Lizenzmodell_.
