---
sidebar: sidebar 
permalink: concept_lic_cp_serial_number.html 
keywords: license, licensing, Capacity Pools, node serial numbers 
summary: Beim Lizenzmodell für die Kapazitäts-Tiers stimmt die neunstellige Node-Seriennummer mit der dem Node zugewiesenen Lizenzseriennummer überein. Die Seriennummern, die Nodes mit dem Kapazitätenpool-Lizenzmodell zugewiesen werden, haben jedoch ein anderes Format. 
---
= Seriennummern der Nodes für das ONTAP Select Kapazitäts-Pools Lizenzmodell
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Beim Lizenzmodell für die Kapazitäts-Tiers stimmt die neunstellige Node-Seriennummer mit der dem Node zugewiesenen Lizenzseriennummer überein. Die Seriennummern, die Nodes mit dem Kapazitätenpool-Lizenzmodell zugewiesen werden, haben jedoch ein anderes Format.

Die Seriennummer eines Node, der die Lizenzierung von Kapazitätspools verwendet, hat das folgende Format:

`999 ppppppppp nnnnnnnn`


NOTE: Leerzeichen wurden aus Gründen der Klarheit hinzugefügt, sind aber nicht Teil der tatsächlichen Seriennummer.

Die folgende Tabelle beschreibt jeden Abschnitt der Knotenseriennummer von links nach rechts.

[cols="15,85"]
|===
| Abschnitt | Beschreibung 


| '999' | Konstanter dreistelliger Wert reserviert von NetApp. 


| Pppppppppppppppppppppppp | Variable neunstellige Lizenzseriennummer, die dem Kapazitäts-Pool von NetApp zugewiesen wurde 


| Nnnnnnnnnnnnnn | Variabler achtstelliger Wert, der vom License Manager für jeden Knoten generiert wird, der den Kapazitäts-Pool verwendet 
|===

CAUTION: Wenn Sie einen Fall beim NetApp Support eröffnen, der einen Knoten mit einer Capacity Pool-Lizenz betrifft, müssen Sie die neunstellige Capacity Pool-Lizenz-Seriennummer angeben. Sie können nicht die vollständige zwanzigstellige Knoten-Seriennummer angeben. Sie können die Lizenz-Seriennummer aus der Knoten-Seriennummer ableiten, indem Sie die ersten drei Ziffern der Knoten-Seriennummer („999“) überspringen und die nächsten neun Ziffern (ppppppppp) extrahieren.
