---
sidebar: sidebar 
permalink: concept_lic_cp_benefits.html 
keywords: license, licensing, Capacity Pools, benefits 
summary: Wenn Sie das Lizenzmodell für Kapazitäts-Pools anstelle des Lizenzmodells für Kapazitäts-Tiers verwenden, gibt es verschiedene Vorteile. 
---
= Zusammenfassung der Vorteile der ONTAP Select Capacity Pools-Lizenzierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie das Lizenzmodell für Kapazitäts-Pools anstelle des Lizenzmodells für Kapazitäts-Tiers verwenden, gibt es verschiedene Vorteile.



== Effizientere Nutzung der Storage-Kapazität

Bei der Nutzung der Capacity-Tiers-Lizenzierung weisen Sie jedem Node eine feste Storage-Kapazität zu. Ungenutzter Speicherplatz kann nicht mit den anderen Nodes gemeinsam genutzt werden und wird effektiv verschwendet. Bei der Lizenzierung der Kapazitäts-Pools verbraucht jeder Node basierend auf der Größe der Datenaggregate nur die Kapazität, die er benötigt.

Die Kapazität ist in einem zentralen Pool verankert, wo sie von vielen Knoten in Ihrer Organisation gemeinsam genutzt werden kann.



== Erheblich geringerer administrativer Aufwand und damit niedrigere Kosten

Wenn Sie Capacity Tier-Lizenzen verwenden, müssen Sie für jeden Node eine Lizenz beziehen und installieren. Bei der Nutzung von Kapazitäts-Pools gibt es eine Lizenz für jeden gemeinsam genutzten Pool. Dies reduziert den administrativen Overhead erheblich und senkt die Kosten.



== Verbesserte Nutzungsmetriken

Die Web-Benutzeroberfläche „Bereitstellen“ bietet erweiterte Nutzungsinformationen für die Kapazitätspools. Es lässt sich schnell bestimmen, wie viel Storage verwendet und in einem Kapazitäts-Pool verfügbar ist, welche Nodes Storage aus einem Pool verwenden und von welchen Pools ein Cluster Kapazität zuweist.
