---
sidebar: sidebar 
permalink: concept_lic_cp_serial_number.html 
keywords: license, licensing, Capacity Pools, node serial numbers 
summary: Beim Lizenzmodell für die Kapazitäts-Tiers stimmt die neunstellige Node-Seriennummer mit der dem Node zugewiesenen Lizenzseriennummer überein. Die Seriennummern, die Nodes mit dem Kapazitätenpool-Lizenzmodell zugewiesen werden, haben jedoch ein anderes Format. 
---
= Seriennummern der Nodes für das ONTAP Select Kapazitäts-Pools Lizenzmodell
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Beim Lizenzmodell für die Kapazitäts-Tiers stimmt die neunstellige Node-Seriennummer mit der dem Node zugewiesenen Lizenzseriennummer überein. Die Seriennummern, die Nodes mit dem Kapazitätenpool-Lizenzmodell zugewiesen werden, haben jedoch ein anderes Format.

Die Seriennummer eines Node, der die Lizenzierung von Kapazitätspools verwendet, hat das folgende Format:

`999 ppppppppp nnnnnnnn`


NOTE: Leerzeichen wurden aus Gründen der Klarheit hinzugefügt, sind aber nicht Teil der tatsächlichen Seriennummer.

Jeder Abschnitt der Seriennummer des Node wird in der folgenden Tabelle von links nach rechts beschrieben.

[cols="15,85"]
|===
| Abschnitt | Beschreibung 


| '999' | Konstanter dreistelliger Wert reserviert von NetApp. 


| Pppppppppppppppppppppppp | Variable neunstellige Lizenzseriennummer, die dem Kapazitäts-Pool von NetApp zugewiesen wurde 


| Nnnnnnnnnnnnnn | Variabler achtstelliger Wert, der vom License Manager für jeden Knoten generiert wird, der den Kapazitäts-Pool verwendet 
|===

NOTE: Achtung: Beim Eröffnen eines Falls mit NetApp Support, der einen Node umfasst, der eine Kapazitäts-Pool-Lizenz verwendet, können Sie nicht die vollständige zwanzig-stellige Node-Seriennummer angeben. Stattdessen müssen Sie die neunstellige Lizenznummer für den Kapazitäts-Pool angeben. Sie können die Lizenzseriennummer von der Node-Seriennummer wie oben dargestellt ableiten. Überspringen Sie die ersten drei Ziffern der Knotenseriennummer ('999') und extrahieren Sie die nächsten neun Ziffern (ppppppppppppppppppppp).
