---
sidebar: sidebar 
permalink: concept_automate_ansible.html 
keywords: ansible, automation, configuration management, ontap, ontap select, na_ots_deploy, na_ots_cluster, ansible roles, ansible playbook 
summary: Ansible-Rollen ermöglichen automatisierte ONTAP Select-Implementierungen. 
---
= Automatisieren Sie ONTAP Select-Implementierungen mit Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Automatisieren Sie ONTAP Select Implementierungen mit Ansible-Rollen und Playbooks.

Eine Ansible-Rolle ist eine logische Sammlung von Aufgaben, Vorlagen, Handlern und Variablen in einer standardisierten Dateistruktur. Verwenden Sie diese Rollen, um Funktionen zu erleichtern, wiederzuverwenden und zu modulisieren, die unabhängig verwendet werden können. Nehmen Sie Rollen und die Liste der Hosts mit auf, an denen sie ausgeführt werden sollen, in einem Playbook zur Ausführung auf. Nach der Installation von Ansible und der Aktualisierung der erforderlichen Module sowie Playbooks können Sie ONTAP Select-Rollen (OTS) von NetApp GitHub herunterladen und so Ihr eigenes Playbook zur Implementierung von ONTAP Select Clustern erstellen und ausführen.



== Rollen

Für ONTAP Select sind zwei Rollen verfügbar:



=== na_ots_Deploy

Diese Rolle lädt die Installationsdatei für ONTAP Select Deploy auf einen vCenter- oder ESXi-Host herunter. Anschließend wird die Implementierungs-VM erstellt und ausgeführt.

Diese Rolle verwendet die folgenden Eingabewerte:

* Anmeldedaten für vCenter oder ESXi Host
* Implementieren der VM-Erstellung, einschließlich Informationen wie:
+
** IP-Adresse
** Host-Name
** Anmelden
** Passwort
** Datenspeicher
** Netzwerk


* Lokaler Pfad zur OVA-Datei
+
Stellen Sie sicher, dass die Installationsdatei verfügbar ist, bevor Sie das Playbook mit der Rolle ausführen.)




NOTE: Die einfachste Möglichkeit, diese Eingabewerte bereitzustellen, ist eine globale Variablendatei im YML-Format. Geben Sie diese YML-Datei im Playbook weiter.

Die Rolle hat eine einzige Aufgabe, die die OVA-Datei „Bereitstellen“ auf den Host importiert, die VM erstellt und ausgeführt. Hier können Sie diese Rolle im NetApp Ansible GitHub aufrufen und herunterladen: link:https://github.com/netapp-automation/na_ots_deploy["na_ots_Deploy"^]



=== na_ots_Cluster

Diese Rolle verwendet die ONTAP Select Deploy-APIs zum Erstellen und Implementieren des ONTAP Select-Clusters. Es wird davon ausgegangen, dass die BereitstellungsVM erstellt wurde und entweder manuell ausgeführt wird oder die Rolle *na_ots_Deploy* verwendet wird. Die Rolle setzt außerdem voraus, dass die Select-Hosts mit den für den ONTAP Select-Cluster erforderlichen Netzwerk- und Storage-Ressourcen konfiguriert sind.

Die Rolle verwendet die Eingabewerte für die vCenter- oder ESXI-Anmeldedaten und implementiert VM-Zugangsdaten, um auf die APIs und alle zugehörigen Informationen zuzugreifen, die zum Erstellen des ONTAP Select-Clusters und der Node-VM erforderlich sind.

Die Rolle führt die folgenden Aufgaben aus:

* Hinzufügen von Hostanmeldeinformationen (vcenter oder esxi
* Abrufen und Registrieren der Host-IDs
* Überprüfung des internen Netzwerks (für Cluster mit mehreren Nodes)
* Erstellen des Clusters
* Konfigurieren der Nodes
* Konfiguration des Netzwerks und des Speicherpools
* Implementieren des Clusters


So ist die Rolle bei laufendem Cluster die Cluster-VM betriebsbereit und der ONTAP Select-Cluster vollständig implementiert. Hier können Sie diese Rolle im NetApp Ansible GitHub aufrufen und herunterladen: link:https://github.com/NetApp-Automation/na_ots_cluster["na_ots_Cluster"^]



== Beispiel Für Ein Playbook

Im Folgenden finden Sie ein Beispiel-Playbook, das diese beiden ONTAP Select-Rollen nennt. Beachten Sie, dass die Eingabevariablen in YML-Dateien definiert und über „Vars_files“ weitergegeben werden. Weitere Details finden Sie in den README-Dateien in jeder Rolle.

[listing]
----
—

– name: Create ONTAP Select deploy from OVA (ESXi)

vars_files:

– vars_deploy.yml                              # All Variables

– vars_deploy_pwd.yml                          # host_password & deploy_password

hosts: “{{ target_vcenter_or_esxi_host }}”     # Entry in Ansible ‘hosts’ file

gather_facts: false

connection: ‘local’

roles:

– na_ots_deploy

– name: Create ONTAP Select Cluster

vars_files:

– vars_cluster_test.yml

– vars_cluster_pwd.yml

hosts: “localhost”

gather_facts: false

roles:

– na_ots_cluster

----
Nachdem der ONTAP Select Cluster anhand der oben genannten Rollen erstellt und ausgeführt wurde, können Sie die umfassenden ONTAP Ansible Funktionen nutzen, die für eine weitere Automatisierung von ONTAP Funktionen verfügbar sind. Auf die verfügbaren ONTAP Rollen kann zugegriffen werden link:https://github.com/NetApp/ansible["Hier"]. Zusammenfassend lässt sich sagen, dass Sie mithilfe der ONTAP Select Ansible Rollen und ONTAP Rollen Ihren gesamten Workflow automatisieren und so Ihren Storage mit ONTAP Select managen können.
