---
sidebar: sidebar 
permalink: concept_adm_before.html 
keywords: administer, administering, web, before you begin 
summary: Nach dem Erstellen eines ONTAP Select-Clusters können Sie die Implementierung durch Ausführen verschiedener Administrationsaufgaben unterstützen. Beachten Sie dabei einige allgemeine Überlegungen. 
---
= Bevor Sie mit der Administration von ONTAP Select beginnen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nach dem Erstellen eines ONTAP Select-Clusters können Sie die Implementierung durch Ausführen verschiedener Administrationsaufgaben unterstützen. Beachten Sie dabei einige allgemeine Überlegungen.

Im Allgemeinen lassen sich die Verfahren, die Sie mit der Weboberfläche Bereitstellen durchführen können, in eine von drei Kategorien einteilen.

.Implementieren eines ONTAP Select-Clusters
Single Node und Multi-Node-Cluster können implementiert werden. Siehe link:task_deploy_cluster.html["Implementieren eines ONTAP Select-Clusters"] Finden Sie weitere Informationen.

.Führen Sie eine Prozedur mit einem vorhandenen ONTAP Select Cluster durch
Die Verwaltungsverfahren sind in verschiedenen Kategorien organisiert, wie _Security_ und _Clusters_.

.Führen Sie ein Verfahren für das Dienstprogramm „Bereitstellen“ durch
Für die Bereitstellung gibt es verschiedene Verfahren (z. B. Ändern des Administratorkennworts).



== Verwaltung von ONTAP Select

Zur Unterstützung der ONTAP Select stehen zahlreiche verschiedene administrative Verfahren zur Verfügung. Darüber hinaus gibt es Verfahren speziell für das Deploy Administration Utility. Die wichtigsten dieser Verfahren sind nachfolgend aufgeführt. Im Allgemeinen verwenden alle die Webbenutzeroberfläche Bereitstellen.


NOTE: Das können Sie auch link:https://docs.netapp.com/us-en/ontap-select/task_cli_signing_in.html["Verwenden Sie die Befehlszeilenschnittstelle"] Für die Verwaltung von ONTAP Select.



== Zusätzliche ONTAP-Konfiguration durchführen

Nachdem ein ONTAP Select Cluster implementiert wurde, können Sie den Cluster wie ein hardwarebasiertes ONTAP System konfigurieren und managen. Sie können beispielsweise ONTAP System Manager oder die ONTAP CLI verwenden, um den ONTAP Select Cluster zu konfigurieren.

.NetApp Client-Software
Mit der folgenden unterstützten NetApp Client Software können Sie eine Verbindung zu ONTAP Select herstellen:

* ONTAP System Manager
* Active IQ Unified Manager
* OnCommand Insight
* OnCommand Workflow-Automatisierung
* SnapCenter
* Virtual Storage Console für VMware vSphere


Um die unterstützten Versionen der Client-Software zu identifizieren, lesen Sie die link:https://mysupport.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool"^]. Wenn die Client-Software ONTAP 9 unterstützt, wird dieselbe Version auch mit ONTAP Select unterstützt.


NOTE: Für die Nutzung von SnapCenter und den entsprechenden Plug-ins sind serverbasierte Lizenzen erforderlich. Storage-Systemlizenzen für SnapCenter Plug-ins werden derzeit nicht bei ONTAP Select unterstützt.

Alle anderen NetApp Client-Software, die nicht in der Liste enthalten ist, wird von ONTAP Select nicht unterstützt.

.Mögliche Konfigurationsoptionen
Beim Konfigurieren des Clusters stehen verschiedene Optionen zur Verfügung. Dazu zählen:

* Erstellen der Netzwerkkonfiguration
* Aggregate auslegen
* Erstellung der Storage-VMs (SVMs)


.Erworbene Lizenzen mit Storage-Kapazität
Wenn Sie sich gegen die Installation der Lizenzdateien im Rahmen der Bereitstellung des ONTAP Select-Clusters entschieden haben, müssen Sie die Lizenzdateien erwerben und installieren, bevor der Gnadenzeitraum für Cluster abläuft, die mit einer erworbenen Lizenz ausgeführt werden.

.Gespiegelte Aggregate
Auf jedem ONTAP Select Node sind durch das Deploy Administration Utility Daten-Spare-Festplatten aus dem nutzbaren Datenspeicherplatz (z. B. Pool0 und Pool1) erstellt. Um Hochverfügbarkeit für Ihre Daten in einem Cluster mit mehreren Knoten zu implementieren, müssen Sie ein gespiegeltes Aggregat unter Verwendung dieser Ersatzteile erstellen.
