---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: Nachdem Sie ein ONTAP Select Cluster implementiert haben, können Sie mithilfe des standardmäßigen ONTAP Software-Upgrades das ONTAP Image jedes Nodes nach Bedarf aktualisieren. 
---
= Aktualisieren Sie die ONTAP Select-Nodes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nach der Bereitstellung eines ONTAP Select Clusters können Sie das ONTAP-Image bei jedem Node im Cluster nach Bedarf aktualisieren.


CAUTION: Das Deploy Administration Utility ist nicht zum Durchführen von Upgrades vorhandener ONTAP Select-Nodes möglich. Das Deploy-Tool kann nur verwendet werden, um neue ONTAP Select-Cluster zu erstellen.



== Allgemeines Verfahren

Auf hoher Ebene sollten Sie die folgenden Schritte verwenden, um einen vorhandenen ONTAP Select Node zu aktualisieren.

.Schritte
. Rufen Sie die link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site Downloads"^] Seite auf.
. Scrollen Sie nach unten und wählen Sie *ONTAP Select Image* aus.
. Wählen Sie die gewünschte Version des Installationsabbilds aus.
. Lesen Sie die Endbenutzer-Lizenzvereinbarung (EULA), und wählen Sie *Accept & Continue* aus.
. Wählen Sie das passende *ONTAP Select Image Upgrade*-Paket aus und laden Sie es herunter. Beantworten Sie alle erforderlichen Eingabeaufforderungen.
+
Überprüfen Sie die link:reference_release_notes.html["Versionshinweise"] auf zusätzliche Informationen und alle erforderlichen Verfahren, bevor Sie einen ONTAP Select-Knoten aktualisieren.

. Aktualisieren Sie den ONTAP Select-Knoten mithilfe der standardmäßigen ONTAP-Upgrade-Verfahren für die ONTAP Select-Upgrade-Datei. Informationen zu unterstützten Upgrade-Pfaden finden Sie im link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["Unterstützte ONTAP Upgrade-Pfade"^].




== Zurücksetzen eines ONTAP Select-Knotens

Sie können einen ONTAP Select Node nicht auf eine Version vor der Version zurücksetzen, auf der er ursprünglich installiert wurde. Beispiel:

ONTAP Select 9.16.1 ist standardmäßig installiert.:: Sie können den Knoten auf Version 9.17.1 aktualisieren und bei Bedarf wieder auf Version 9.16.1 zurücksetzen.
ONTAP Select 9.17.1 ist standardmäßig installiert.:: Eine Wiederherstellung ist nicht möglich, da zuvor keine ältere Version installiert war.




== Verwenden Sie den VMXNET3-Netzwerktreiber

VMXNET3 ist der Standard-Netzwerktreiber bei neuen Cluster-Implementierungen auf VMware ESXi. Wenn Sie einen vorhandenen ONTAP Select-Knoten aktualisieren, auf dem ONTAP Select 9.4 oder eine frühere Version ausgeführt wird, wird der Netzwerktreiber nicht automatisch aktualisiert. Sie müssen manuell ein Upgrade auf VMXNET3 durchführen. Wenden Sie sich an den NetApp Support, um Hilfe beim Upgrade zu erhalten.

.Verwandte Informationen
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP Upgrade-Übersicht"^]
