---
sidebar: sidebar 
permalink: concept_lic_cp_restrictions.html 
keywords: license, licensing, Capacity Pools, restrictions 
summary: Im Folgenden werden die Einschränkungen dargestellt, die bei der Nutzung des Kapazitäts-Pool-Lizenzmodells gelten. 
---
= Implementierungsbeschränkungen für die Lizenzierung von ONTAP Select Kapazitäts-Pools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Im Folgenden werden die Einschränkungen dargestellt, die bei der Nutzung des Kapazitäts-Pool-Lizenzmodells gelten.

.Konsistentes Lizenzmodell pro Cluster
Alle Nodes in einem einzelnen ONTAP Select Cluster müssen dasselbe Lizenzmodell nutzen, entweder die Kapazitäts-Tiers oder die Kapazitäts-Pools. Sie können die Lizenztypen für die Nodes nicht in einem einzelnen Cluster kombinieren.

.Alle Nodes in einem Cluster verwenden dieselbe Lizenz-Manager-Instanz
Alle Knoten mit einer Capacity Pool-Lizenz in einem ONTAP Select Cluster müssen dieselbe License Manager-Instanz verwenden. Da es in jeder Deploy-Instanz eine License Manager-Instanz gibt, ist diese Einschränkung eine Wiederholung der bestehenden Anforderung, dass dieselbe Deploy-Instanz alle Knoten in einem Cluster verwalten muss.

.Ein Kapazitäts-Pool pro Node
Jeder Node kann Storage aus genau einem Kapazitäts-Pool leasen. Ein Node kann mindestens zwei Pools nicht verwenden.

.Derselbe Pool für Nodes in einem HA-Paar
Beide Nodes in einem einzelnen HA-Paar müssen Storage aus demselben Kapazitäts-Pool leasen. Verschiedene HA-Paare innerhalb desselben Clusters können jedoch Storage aus verschiedenen Pools leasen, die von demselben License Manager gemanagt werden.

.Dauer der Storage-Lizenz
Sie müssen beim Erwerb der Storage-Lizenz von NetApp eine Lizenzdauer auswählen. Beispielsweise könnte eine Lizenz für ein Jahr gültig sein.

.Leasing-Dauer für das Datenaggregat
Wenn ein ONTAP Select-Node eine Storage-Leasing-Anforderung für ein Datenaggregat anfordert, stellt der License Manager basierend auf der Konfiguration des Kapazitätspools eine Leasing-Option für eine bestimmte Dauer bereit. Sie können die Leasing-Dauer für jeden Pool zwischen einer Stunde und sieben Tagen konfigurieren. Die Standard-Leasing-Dauer beträgt 24 Stunden.

.Der Bereitstellung zugewiesene statische IP-Adresse
Sie müssen dem Dienstprogramm „Deployment Administration“ eine statische IP-Adresse zuweisen, wenn die Lizenzierung von Kapazitätspools verwendet wird.
