---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: Merkmale interner und externer ONTAP Select-Netzwerke. 
---
= Interne und externe ONTAP Select-Netzwerke
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Merkmale interner und externer ONTAP Select Netzwerke



== Internes ONTAP Select Netzwerk

Das interne ONTAP Select Netzwerk, das nur in der Multi-Node-Variante des Produkts vorhanden ist, ist für die Bereitstellung des ONTAP Select Clusters mit Clusterkommunikation, HA-Interconnect und synchronen Replizierungsdiensten verantwortlich. Dieses Netzwerk umfasst die folgenden Ports und Schnittstellen:

* *e0c, e0d.* Hosting von Clusternetzwerk-LIFs
* *e0e.* Hosting der RSM LIF
* *e0f.* Hosting der HA Interconnect LIF


Der Durchsatz und die Latenz dieses Netzwerks sind beim ermitteln der Performance und Ausfallsicherheit des ONTAP Select Clusters entscheidend. Netzwerkisolierung ist für die Cluster-Sicherheit erforderlich und stellt sicher, dass die Systemschnittstellen nicht durch andere Netzwerkdatenströme getrennt bleiben. Deshalb muss dieses Netzwerk ausschließlich vom ONTAP Select Cluster verwendet werden.


NOTE: Die Verwendung des internen Netzwerks auswählen für Datenverkehr außer Cluster-Datenverkehr auswählen, wie z. B. Anwendungs- oder Verwaltungsdatenverkehr, wird nicht unterstützt. Es können keine anderen VMs oder Hosts auf dem internen ONTAP VLAN vorhanden sein.

Netzwerkpakete, die das interne Netzwerk durchlaufen, müssen sich in einem dedizierten VLAN-getaggten Layer-2-Netzwerk befinden. Führen Sie hierzu eine der folgenden Aufgaben aus:

* Zuweisen einer VLAN-getaggten Portgruppe zu den internen virtuellen NICs (e0c über e0f) (VST-Modus)
* Verwenden des nativen VLAN, das vom Upstream Switch bereitgestellt wird, wobei das native VLAN nicht für anderen Datenverkehr verwendet wird (weisen Sie eine Portgruppe ohne VLAN-ID zu, also EST-Modus)


In jedem Fall wird das VLAN-Tagging für den internen Netzwerk-Datenverkehr außerhalb der ONTAP Select VM durchgeführt.


NOTE: Es werden ausschließlich ESXi Standard und Distributed vSwitches unterstützt. Andere virtuelle Switches oder direkte Verbindungen zwischen ESXi Hosts werden nicht unterstützt. Das interne Netzwerk muss vollständig geöffnet sein; NAT oder Firewalls werden nicht unterstützt.

Innerhalb eines ONTAP Select Clusters werden interner und externer Datenverkehr mithilfe virtueller Layer-2-Netzwerkobjekte, sogenannter Portgruppen, getrennt. Die korrekte Zuordnung dieser Portgruppen zu den vSwitches ist von größter Wichtigkeit, insbesondere für das interne Netzwerk, das für die Bereitstellung von Cluster-, HA-Interconnect- und Mirror-Replikationsdiensten zuständig ist. Unzureichende Netzwerkbandbreite für diese Netzwerkports kann zu Leistungseinbußen führen und sogar die Stabilität des Clusterknotens beeinträchtigen.  Daher ist für Cluster mit vier, sechs, acht, zehn und zwölf Knoten erforderlich, dass das interne ONTAP Select Netzwerk eine 10-Gb-Konnektivität nutzt; 1-Gb-NICs werden nicht unterstützt.  Allerdings können Kompromisse mit dem externen Netzwerk eingegangen werden, da die Begrenzung des Datenflusses an einen ONTAP Select Cluster dessen zuverlässige Funktionsfähigkeit nicht beeinträchtigt.

In einem Cluster mit zwei Nodes können entweder vier 1-Gbit-Ports für den internen Datenverkehr oder einen einzelnen 10-Gbit-Port verwendet werden. Dabei kommen nicht die zwei vom Cluster mit vier Nodes erforderlichen 10-Gbit-Ports zum Einsatz. In einer Umgebung, in der der Server nicht mit vier 10-Gbit-NIC-Karten passt, können für das interne Netzwerk zwei 10-Gbit-NIC-Karten verwendet werden und zwei 1-Gbit-NICs für das externe ONTAP-Netzwerk verwendet werden.



=== Interne Netzwerkvalidierung und Fehlerbehebung

Das interne Netzwerk in einem Multi-Node-Cluster kann mithilfe der Netzwerkverbindungsprüfungsfunktion validiert werden. Diese Funktion kann von der Deploy-CLI aus durch Ausführen des  `network connectivity-check start` Befehls aufgerufen werden.

Führen Sie den folgenden Befehl aus, um die Ausgabe des Tests anzuzeigen:

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
Dieses Tool ist ausschließlich zur Fehlerbehebung im internen Netzwerk in einem Multi-Node-Select-Cluster geeignet. Das Tool sollte nicht zur Fehlerbehebung bei Single-Node-Clustern (einschließlich vNAS-Konfigurationen), der ONTAP Deploy zu ONTAP Select-Konnektivität oder Client-seitigen Konnektivitätsproblemen verwendet werden.

Der Cluster-Erstellungsassistent (Bestandteil der ONTAP Deploy UI) beinhaltet die Überprüfung des internen Netzwerks als optionalen Schritt während der Erstellung von Multi-Node-Clustern. Angesichts der wichtigen Rolle, die das interne Netzwerk in Multi-Node-Clustern spielt, verbessert die Aufnahme dieses Schritts in den Cluster-Erstellungs-Workflow die Erfolgsrate von Cluster-Erstellungsvorgängen.

Ab ONTAP Deploy 2.10 kann die vom internen Netzwerk verwendete MTU-Größe zwischen 7,500 und 9,000 festgelegt werden. Mit dem Network Connectivity Checker kann auch die MTU-Größe zwischen 7,500 und 9,000 getestet werden. Der MTU-Standardwert ist auf den Wert des virtuellen Netzwerk-Switches eingestellt. Dieser Standardwert müsste durch einen kleineren Wert ersetzt werden, wenn ein Netzwerküberlagerung wie VXLAN in der Umgebung vorhanden ist.



== Externes ONTAP Select-Netzwerk

Das ONTAP Select externe Netzwerk ist für die gesamte ausgehende Kommunikation des Clusters zuständig und ist daher sowohl in Einzelknoten- als auch in Mehrknotenkonfigurationen vorhanden. Obwohl dieses Netzwerk nicht die streng definierten Anforderungen an den Durchsatz des internen Netzwerks hat, sollte der Administrator darauf achten, keine Netzwerkengpässe zwischen dem Client und der ONTAP VM zu verursachen, da Leistungsprobleme fälschlicherweise als ONTAP Select Probleme interpretiert werden könnten.


NOTE: Ähnlich wie der interne Traffic kann externer Datenverkehr auf der vSwitch-Ebene (VST) und auf der externen Switch-Ebene (EST) markiert werden. Darüber hinaus kann der externe Datenverkehr von der ONTAP Select-VM selbst in einem Prozess namens VGT markiert werden. Siehe Abschnitt link:concept_nw_data_mgmt_separation.html["Trennung des Daten- und Management-Datenverkehrs"] Entnehmen.

Die folgende Tabelle zeigt die wesentlichen Unterschiede zwischen internen und externen ONTAP Select-Netzwerken.

* Kurzreferenz des internen und externen Netzwerks*

[cols="3*"]
|===
| Beschreibung | Internes Netzwerk | Externes Netzwerk 


| Netzwerkservices | Cluster HA/IC RAID SyncMirror (RSM) | Datenmanagement Intercluster (SnapMirror und SnapVault) 


| Netzwerkisolierung | Erforderlich | Optional 


| Frame-Größe (MTU) | 7,500 bis 9,000 | 1,500 (Standard) 9,000 (unterstützt) 


| Zuweisung der IP-Adresse | Automatisch Generiert | Benutzerdefiniert 


| DHCP-Support | Nein | Nein 
|===


=== NIC-Teaming

Um sicherzustellen, dass sowohl interne als auch externe Netzwerke über die erforderliche Bandbreite als auch die Resiliency-Merkmale verfügen, die für eine hohe Performance und Fehlertoleranz erforderlich sind, wird die Gruppenbildung von physischen Netzwerkadaptern empfohlen. Es werden zwei-Node-Cluster-Konfigurationen mit einem einzelnen 10-GB-Link unterstützt. Die von NetApp empfohlene Best Practice besteht jedoch darin, NIC-Teaming sowohl auf den internen als auch auf den externen Netzwerken des ONTAP Select Clusters zu nutzen.



=== MAC-Adressgenerierung

Die MAC-Adressen, die allen ONTAP Select-Netzwerk-Ports zugewiesen sind, werden automatisch vom enthaltenen Bereitstellungs-Dienstprogramm generiert. Die Utility verwendet eine plattformspezifische, organisatorisch einzigartige Kennung (OUI) speziell für NetApp, um sicherzustellen, dass keine Konflikte mit FAS Systemen bestehen. Eine Kopie dieser Adresse wird dann in einer internen Datenbank in der ONTAP Select Installations-VM (ONTAP Deploy) gespeichert, um eine versehentliche Neuzuweisung bei zukünftigen Node-Implementierungen zu verhindern. In keinem Fall sollte der Administrator die zugewiesene MAC-Adresse eines Netzwerkports ändern.
