---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: Nachdem Sie ein ONTAP Select Cluster implementiert haben, können Sie mithilfe des standardmäßigen ONTAP Software-Upgrades das ONTAP Image jedes Nodes nach Bedarf aktualisieren. 
---
= Aktualisieren Sie die ONTAP Select-Nodes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nach der Bereitstellung eines ONTAP Select Clusters können Sie das ONTAP-Image bei jedem Node im Cluster nach Bedarf aktualisieren.


CAUTION: Das Deploy Administration Utility ist nicht zum Durchführen von Upgrades vorhandener ONTAP Select-Nodes möglich. Das Deploy-Tool kann nur verwendet werden, um neue ONTAP Select-Cluster zu erstellen.



== Allgemeines Verfahren

Auf hoher Ebene sollten Sie die folgenden Schritte verwenden, um einen vorhandenen ONTAP Select Node zu aktualisieren.

. Navigieren Sie zu der Download-Seite auf der NetApp Support Site.
+
https://mysupport.netapp.com/site/downloads["NetApp Support-Downloads"^]

. Klicken Sie auf *ONTAP Select Knoten-Upgrade*.
. Wählen Sie das entsprechende Upgrade-Image aus, und laden Sie es herunter, um alle Aufforderungen bei Bedarf zu beantworten.
+
Weitere Informationen und erforderliche Verfahren vor dem Upgrade eines ONTAP Select-Knotens sind in den Versionshinweisen zu finden.

. Aktualisieren Sie den ONTAP Select-Knoten mithilfe der standardmäßigen ONTAP-Upgrade-Verfahren für die ONTAP Select-Upgrade-Datei. Informationen zu unterstützten Upgrade-Pfaden finden Sie im link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["Unterstützte ONTAP Upgrade-Pfade"^].




== Zurücksetzen eines ONTAP Select-Knotens

Sie können einen ONTAP Select Node nicht auf eine Version vor der Version zurücksetzen, auf der er ursprünglich installiert wurde. Beispiel:

ONTAP Select 9.7 ist zunächst installiert:: Sie können den Node auf Version 9.8 aktualisieren und bei Bedarf zurück auf Version 9.7 wechseln.
ONTAP Select 9.8 ist zunächst installiert:: Sie können nicht auf Version 9.7 zurücksetzen, da diese Version vor der ursprünglich installierten Version liegt.




== Verwenden Sie den VMXNET3-Netzwerktreiber

VMXNET3 ist der Standard-Netzwerktreiber bei neuen Cluster-Implementierungen auf VMware ESXi. Wenn Sie einen vorhandenen ONTAP Select-Knoten aktualisieren, auf dem ONTAP Select 9.4 oder eine frühere Version ausgeführt wird, wird der Netzwerktreiber nicht automatisch aktualisiert. Sie müssen manuell ein Upgrade auf VMXNET3 durchführen. Wenden Sie sich an den NetApp Support, um Hilfe beim Upgrade zu erhalten.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP Upgrade-Übersicht"^]

