---
sidebar: sidebar 
permalink: concept_vpi_vcenter_integration.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter integration 
summary: Das Deploy-Plug-in ist eng mit vCenter Server integriert. Aufgrund dieser Integration finden Sie problemlos zwischen den Ressourcen, die von Deploy Utility und vCenter Server gemanagt werden. Einige Beispiele für diese Integration finden Sie im Folgenden. 
---
= Implementieren Sie Plug-in- und vCenter-Integration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Deploy-Plug-in ist eng mit vCenter Server integriert. Aufgrund dieser Integration finden Sie problemlos zwischen den Ressourcen, die von Deploy Utility und vCenter Server gemanagt werden. Einige Beispiele für diese Integration finden Sie im Folgenden.



== Einem ONTAP Select-Cluster zugewiesene VMware-Ressourcen

Ein ONTAP Select Cluster läuft auf VMware als Satz von einem oder mehreren Nodes. Jeder Node ist eine dedizierte Virtual Machine auf einem anderen ESXi Host. Ein ONTAP Select Cluster ist den folgenden VMware-Ressourcen zugeordnet:

* Hosts
* ONTAP-VMs
* Datenspeicher
* Netzwerke


Es gibt verschiedene Möglichkeiten, die VMware Ressourcen anzuzeigen, die von einem bestimmten ONTAP Select Cluster verwendet werden.



== Zeigen Sie die VMware-Ressourcen für einen Cluster über das Plug-in an

Sie können über das Deploy-Plug-in die VMware Ressourcen anzeigen, die einem ONTAP Select Cluster zugewiesen sind.

.Schritte
. Melden Sie sich über vSphere HTML5 mit einem Browser beim vCenter-Server an.
. Klicken Sie im Fenster *Globale Inventarlisten* auf *ONTAP Select Cluster*.
. Klicken Sie rechts in der Liste auf den gewünschten Cluster.
. Klicken Sie auf die Registerkarte *Mehr Objekte* und wählen Sie oben auf der Seite die gewünschte Ressourcenkategorie aus.
. Wählen Sie eine bestimmte VMware-Ressource aus, um zusätzliche Informationen anzuzeigen.




== Zeigen Sie die ONTAP Select-Cluster über eine virtuelle ESXi-Maschine an

Sie können das ONTAP Select-Cluster und die zugehörigen Clusterressourcen anzeigen, indem Sie auf eine VMware Virtual Machine zugreifen.

.Schritte
. Melden Sie sich über vSphere HTML5 mit einem Browser beim vCenter-Server an.
. Klicken Sie oben auf *Menü* und dann auf *VMs und Vorlagen*.
. Wählen Sie die gewünschte virtuelle Maschine in der Liste links aus.
. Klicken Sie auf die Registerkarte *Mehr Objekte*, um den ONTAP Select Cluster anzuzeigen, der in der VM ausgeführt wird.
. Um die gesamte Sammlung von VMware-Ressourcen anzuzeigen, die dem Cluster zugeordnet sind, klicken Sie auf den ONTAP Select-Cluster und dann auf die Registerkarte *Mehr Objekte*.




== Erstellen Sie ein Single-Node-Cluster auf einem ESXI-Host

Sie können einen ESXI Hypervisor Host über die vSphere Schnittstelle auswählen und ein ONTAP Select Single-Node-Cluster implementieren.

.Schritte
. Melden Sie sich über vSphere HTML5 mit einem Browser beim vCenter-Server an.
. Klicken Sie oben auf *Menü* und dann auf *Hosts und Cluster*.
. Klicken Sie mit der rechten Maustaste auf den gewünschten Hypervisor-Host auf der linken Seite, wählen Sie *ONTAP Select* und klicken Sie dann auf *Neuer ONTAP Select*.
. Führen Sie den Bereitstellungsprozess durch, indem Sie die Schritte unter ausführen link:task_deploy_cluster.html["Implementieren eines ONTAP Select-Clusters"].

