---
sidebar: sidebar 
permalink: concept_vpi_overview.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, overview, functionality 
summary: Das VMware vCenter Plug-in für ONTAP Select Deploy wurde für ONTAP Select Administratoren konzipiert, die in der VMware Umgebung arbeiten. Es stellt eine Alternative zur nativen Bereitstellungsbenutzeroberfläche dar. 
---
= Überblick über das Deploy vCenter Plug-in
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das VMware vCenter Plug-in für ONTAP Select Deploy wurde für ONTAP Select Administratoren konzipiert, die in der VMware Umgebung arbeiten. Es stellt eine Alternative zur nativen Bereitstellungsbenutzeroberfläche dar.



== Paketpaket mit Implementierung

Das Plug-in Deploy vCenter ist im Lieferumfang des Deploy Administration Utility enthalten. Nachdem Sie das Plug-in über die Benutzeroberfläche Deploy auf dem vCenter Server installiert haben, können Sie über die vSphere Webschnittstelle auf das Plug-in zugreifen.



== Integration mit VMware

VMware vCenter ist für viele Unternehmen eine zentrale Plattform zur Administration virtualisierter Datacenter- und Cloud-Ressourcen. Da das Plug-in für die Implementierung eng in vCenter integriert ist, können Administratoren schnell zwischen den ONTAP Select- und vCenter-Domänen verschieben, um die Beziehungen zwischen den verschiedenen Ressourcen zu nutzen.



== Funktionen des Deploy vCenter Plug-ins

Nach der Installation des Plug-ins Deploy vCenter stehen über vSphere im Fenster *Global Inventory Lists* zwei primäre Optionen zur Verfügung.



=== ONTAP Select Cluster

Die Option ONTAP Select Cluster entspricht in etwa der Registerkarte *Cluster* in der systemeigenen Webbenutzeroberfläche bereitstellen. Er bietet die in der folgenden Tabelle beschriebenen Funktionen.

[cols="30,70"]
|===
| Sie führen diese Operation durch ... | Indem Sie dies tun ... 


| Implementieren eines ONTAP Select-Clusters | Klicken Sie auf Neue ONTAP Select. 


| Zeigen Sie Cluster-Details an | Wählen Sie einen Cluster aus, klicken Sie auf Zusammenfassung und klicken Sie dann auf Details. 


| Zeigen Sie Cluster-Ereignismeldungen an | Wählen Sie einen Cluster aus, klicken Sie auf Zusammenfassung und dann auf Ereignisse. 


| Ein Cluster kann online oder offline verschoben oder ein Cluster gelöscht werden | Wählen Sie einen Cluster aus, klicken Sie auf Actions und klicken Sie dann auf die gewünschte Aktion. 


| Starten Sie System Manager | Wählen Sie einen Cluster aus, klicken Sie auf Zusammenfassung, klicken Sie auf Details und klicken Sie dann auf System Manager starten. 


| Zeigen Sie die von einem Cluster verwendeten ESXi-Hosts an | Wählen Sie einen Cluster aus, klicken Sie auf Weitere Objekte, und klicken Sie dann auf Hosts. Wählen Sie einen Host aus, um weitere Details und weitere Aktionen zu erhalten. 


| Zeigen Sie die von einem Cluster verwendeten ONTAP VMs an | Wählen Sie einen Cluster aus, klicken Sie auf Weitere Objekte und klicken Sie dann auf ONTAP VMs. Wählen Sie eine VM aus, um weitere Details und weitere Aktionen anzuzeigen. 


| Anzeigen der von einem Cluster verwendeten Datenspeicher | Wählen Sie einen Cluster aus, klicken Sie auf mehrere Objekte und klicken Sie dann auf Datastores. Wählen Sie einen Datastore aus, um weitere Details und weitere Aktionen zu erhalten. 


| Zeigen Sie die Netzwerke an, die von einem Cluster verwendet werden | Wählen Sie einen Cluster aus, klicken Sie auf Weitere Objekte, und klicken Sie dann auf Netzwerke. Wählen Sie ein Netzwerk aus, um weitere Details und weitere Aktionen zu erhalten. 
|===


=== ONTAP Select Deploy

Die ONTAP Select-Deploy-Option entspricht ungefähr den Registerkarten *Hypervisor-Hosts* und *Administration* in der nativen Deploy-Webbenutzeroberfläche. Sie bietet Funktionen über drei Registerkarten oben auf der Seite, wie in der folgenden Tabelle beschrieben.

[cols="15,85"]
|===
| Registerkarte | Beschreibung 


| Zusammenfassung | Beschreibt die Merkmale der Deploy-Instanz, einschließlich des Host-Namens und der IP-Adresse. 


| Host | Zeigt Informationen zu den ESXi-Hosts an, die bei ONTAP Select Deploy registriert sind. Sie können Hosts hinzufügen oder entfernen. 


| Administration | Ermöglicht die Ausführung von Verwaltungsaufgaben über das Dienstprogramm „Bereitstellen“. Diese Funktionalität entspricht der nativen Benutzeroberfläche von ONTAP Select Deploy, mit der Ausnahme, dass die Optionen *Credentials* und *Plugins* nicht mit dem Plug-in verfügbar sind. 
|===


== Vergleichen Sie das vCenter Plug-in mit der nativen Deploy-Benutzeroberfläche

Die Funktionen, die das vCenter Plug-in über vSphere bietet, entsprechen der nativen Implementierungsschnittstelle. Es gibt jedoch einige Funktionen, die nicht mit dem Plug-in geliefert werden und nur mit der Benutzeroberfläche Deploy verfügbar sind.



=== VCenter Plug-in managen und

Sie können das vCenter Plug-in nicht mit dem vCenter Plug-in installieren, aktualisieren, entfernen oder überprüfen. Sie müssen diese Managementaufgaben über die native Benutzeroberfläche für die Bereitstellung ausführen.



=== Management der vCenter-Anmeldedaten

Bevor Sie das vCenter Plug-in installieren, müssen Sie die erforderlichen vCenter-Anmeldeinformationen hinzufügen, um die Bereitstellung über die native Deploy-Benutzeroberfläche zu verwenden.



=== ONTAP Select Cluster müssen vom gleichen vCenter Server gesteuert werden

Sie können nur die ONTAP Select Cluster implementieren und unterstützen, die von einem einzelnen vCenter Server gemanagt werden, auf dem das Plug-in installiert ist. Sie können das Plug-in nicht verwenden, um auf ONTAP Select Cluster zuzugreifen, die von anderen vCenter Servern oder Clustern verwaltet werden, die auf eigenständigen ESXi- oder KVM-Hosts ausgeführt werden.
