---
sidebar: sidebar 
permalink: concept_stor_eff_support.html 
keywords: ontap select, storage efficiency support 
summary: ONTAP Select bietet Storage-Effizienz-Optionen, die den auf FAS und AFF Arrays vorhandenen Optionen für Storage-Effizienz ähnlich sind. 
---
= Support für Storage-Effizienz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select bietet Storage-Effizienz-Optionen, die den auf FAS und AFF Arrays vorhandenen Optionen für Storage-Effizienz ähnlich sind.

Virtuelle ONTAP Select NAS-Implementierungen mit rein Flash-basiertem VSAN oder generischen Flash-Arrays sollten den Best Practices für ONTAP Select mit Direct-Attached Storage (das) anderer SSDs folgen.

Bei neuen Installationen wird automatisch eine All Flash FAS Persönlichkeit aktiviert, sofern Sie das-Storage mit SSD-Laufwerken und eine Premiumlizenz haben.

Dank All Flash FAS Persönlichkeit werden die folgenden Inline-SE-Funktionen während der Installation automatisch aktiviert:

* Inline-Erkennung von Null-Mustern
* Inline-Deduplizierung von Volume
* Hintergrund-Deduplizierung des Volume
* Anpassungsfähige Inline-Komprimierung
* Inline-Data-Compaction
* Inline-Deduplizierung von Aggregaten
* Deduplizierung im Hintergrund eines Aggregats


Führen Sie den folgenden Befehl für ein neu erstelltes Volume aus, um zu überprüfen, ob ONTAP Select alle standardmäßigen Storage-Effizienzrichtlinien aktiviert hat:

[listing]
----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

NOTE: Für ONTAP Select Upgrades von 9.6 und höher müssen Sie ONTAP Select auf das SSD Storage mit einer Premiumlizenz installieren. Außerdem müssen Sie während der ersten Cluster-Installation mit ONTAP Deploy das Kontrollkästchen *Storage-Effizienz* aktivieren* aktivieren. Wenn die Bedingungen noch nicht erfüllt sind, muss nach dem ONTAP Upgrade eine AFF-ähnliche Persönlichkeit erstellt werden, um ein Boot-Argument und einen Node-Neustart zu ermöglichen. Weitere Informationen erhalten Sie vom technischen Support.

Die folgende Tabelle fasst die verschiedenen verfügbaren, standardmäßig aktivierten und nicht standardmäßig aktivierten Storage-Effizienztechnologien zusammen, jedoch empfohlen, je nach Medientyp und Softwarelizenz. Die Informationen in der folgenden Tabelle gelten für ONTAP Select 9.6 und neuere Versionen. Informationen zu vorherigen Versionen finden Sie im Abschnitt „_ONTAP Select Storage Efficiency Support_“ in https://www.netapp.com/media/10662-tr4517.pdf["TR-4517"^].

[cols="4"]
|===
| Funktionen der ONTAP Select | DAS SSD (Premium oder Premium XL^1^) | DAS HDD (alle Lizenzen) | VNAS (alle Lizenzen) 


| Inline-Zero-Erkennung | Ja (Standard) | Ja, die Funktion ist für Benutzer auf Volume-Basis aktiviert | Ja, die Funktion ist für Benutzer auf Volume-Basis aktiviert 


| Inline-Deduplizierung von Volume | Ja (Standard) | Nicht verfügbar | Nicht unterstützt 


| 32.000 Inline-Komprimierung (sekundäre Komprimierung) | Ja, die Funktion ist für Benutzer pro Volume aktiviert. | Ja, die Funktion ist für Benutzer auf Volume-Basis aktiviert | Nicht unterstützt 


| 8 KB Inline-Komprimierung (anpassungsfähige Komprimierung) | Ja (Standard) | Ja, die Funktion ist für Benutzer pro Volume aktiviert | Nicht unterstützt 


| Hintergrund-Komprimierung | Nicht unterstützt | Ja, die Funktion ist für Benutzer pro Volume aktiviert | Ja, die Funktion ist für Benutzer auf Volume-Basis aktiviert 


| Komprimierungsscanner | Ja. | Ja. | Ja, die Funktion ist für Benutzer auf Volume-Basis aktiviert 


| Inline-Data-Compaction | Ja (Standard) | Ja, die Funktion ist für Benutzer pro Volume aktiviert | Nicht unterstützt 


| Verdichtescanner | Ja. | Ja. | Nicht unterstützt 


| Inline-Deduplizierung von Aggregaten | Ja (Standard) | K. A. | Nicht unterstützt 


| Hintergrund-Deduplizierung des Volume | Ja (Standard) | Ja, die Funktion ist für Benutzer pro Volume aktiviert | Ja, die Funktion ist für Benutzer auf Volume-Basis aktiviert 


| Deduplizierung im Hintergrund eines Aggregats | Ja (Standard) | K. A. | Nicht unterstützt 
|===
[Small]#^1^ONTAP Select 9.6 unterstützt eine neue Lizenz (Premium XL) und eine neue VM-Größe (groß). Die große VM wird jedoch nur bei das-Konfigurationen unter Verwendung von Software-RAID unterstützt. Hardware-RAID und vNAS Konfigurationen werden von der großen ONTAP Select VM in Version 9.6 nicht unterstützt.#

Warten Sie nach dem Upgrade auf ONTAP Select 9.6 oder höher auf den `system node upgrade-revert show` Befehl zeigt an, dass das Upgrade abgeschlossen wurde, bevor die Storage-Effizienzwerte für vorhandene Volumes überprüft wurden.

Auf einem System, das auf ONTAP Select 9.6 oder höher aktualisiert wird, verhält sich ein neues Volume, das auf einem vorhandenen Aggregat oder einem neu erstellten Aggregat erstellt wurde, mit dem Verhalten eines Volumes, das auf einer neuen Implementierung erstellt wurde. Für vorhandene Volumes, die dem ONTAP Select Code Upgrade unterzogen werden, liegen die meisten Storage-Effizienzrichtlinien wie für ein neu erstelltes Volume vor, wobei einige Variationen bestehen:

Szenario 1:: Wenn vor dem Upgrade keine Storage-Effizienzrichtlinien für ein Volume aktiviert wurden, gilt Folgendes:
+
--
* Volumes mit `space guarantee = volume` Es ist keine Inline-Data-Compaction, Inline-Deduplizierung für Aggregate und keine Deduplizierung im Hintergrund für Aggregate aktiviert. Diese Optionen können nach dem Upgrade aktiviert werden.
* Volumes mit `space guarantee = none` Die Hintergrund-Komprimierung ist nicht aktiviert. Diese Option kann nach dem Upgrade aktiviert werden.
* Die Storage-Effizienzrichtlinie für die vorhandenen Volumes ist nach einem Upgrade auf automatisch festgelegt.


--
Szenario 2:: Wenn bereits vor dem Upgrade einige Storage-Effizienzen auf einem Volume aktiviert sind, dann:
+
--
* Volumes mit `space guarantee = volume` Sehe keinen Unterschied nach einem Upgrade.
* Volumes mit `space guarantee = none` Deduplizierung im Hintergrund für Aggregate ist aktiviert.
* Volumes mit `storage policy inline-only` Lassen Sie ihre Richtlinie auf automatisch setzen.
* Volumes mit benutzerdefinierten Storage-Effizienzrichtlinien ändern die Richtlinie nicht, mit Ausnahme von Volumes `space guarantee = none`. Diese Volumes sind durch Deduplizierung im Hintergrund für die Aggregate aktiviert.


--


Storage-Effizienzfunktionen, die vor dem Upgrade aktiviert wurden, werden nach dem Upgrade auf ONTAP Select 9.6 oder höher beibehalten. Wenn vor dem Upgrade keine Storage-Effizienz aktiviert wurde, ist nach einem Upgrade keine Storage-Effizienz aktiviert.
