---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: Das Lizenzmodell für Kapazitäts-Pools unterscheidet sich vom Modell für Kapazitäts-Tiers. Die Storage-Kapazität wird jedem einzelnen Node nicht mehr bereitgestellt, sondern einem Pool zugewiesen, der von vielen Nodes gemeinsam genutzt wird. Zur Unterstützung des Kapazitäts-Pools-Modells wurden zusätzliche Komponenten und Prozesse erstellt. 
---
= Operative Details des ONTAP Select Kapazitäts-Pools-Lizenzmodells
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Lizenzmodell für Kapazitäts-Pools unterscheidet sich vom Modell für Kapazitäts-Tiers. Die Storage-Kapazität wird jedem einzelnen Node nicht mehr bereitgestellt, sondern einem Pool zugewiesen, der von vielen Nodes gemeinsam genutzt wird. Zur Unterstützung des Kapazitäts-Pools-Modells wurden zusätzliche Komponenten und Prozesse erstellt.



== Lizenzmanager

Der License Manager wird in jeder Instanz des Dienstprogramms Deploy Administration als separater Prozess ausgeführt. Einige der von LM bereitgestellten Funktionen umfassen:

* Basierend auf der Lizenznummer des Kapazitäts-Pools wird für jeden Node eine eindeutige, zwanzig-stellige Seriennummer generiert
* Erstellung von Leasingverträgen für Kapazität aus den Pools mit gemeinsam genutzter Kapazität basierend auf Anforderungen der ONTAP Select Nodes
* Erstellen Sie Informationen zur Pool-Nutzung über die Benutzeroberfläche „Bereitstellen“




== Leasing-Merkmale

Dem für jedes Datenaggregat auf einem Node mit einer Lizenz im Kapazitäts-Pool zugewiesenen Storage muss ein Leasing zugewiesen sein. Der Node fordert ein Storage-Leasing an, und wenn die Kapazität verfügbar ist, reagiert der License Manager mit einem Leasing. Jeder Leasingvertrag hat die folgenden expliziten oder impliziten Attribute:

* Lizenzmanager jeder ONTAP Select-Knoten ist einer Lizenz-Manager-Instanz zugeordnet
* Kapazitäts-Pool jeder ONTAP Select-Node ist einem Kapazitäts-Pool zugeordnet
* Storage-Zuweisung Ein bestimmter Kapazitätswert wird im Leasing zugewiesen
* Verfallsdatum und -Uhrzeit die Dauer zwischen einer Stunde und sieben Tagen ist abhängig von der Benutzerkonfiguration.




== Lizenzsperre ID

Jede Instanz des License Manager und damit jede entsprechende Deploy Utility-Instanz wird mit einer eindeutigen 128-Bit-Nummer identifiziert. Diese Nummer wird mit der neunstelligen Lizenz-Seriennummer für den Kapazitätspool kombiniert, um den Pool für eine bestimmte License Manager-Instanz zu sperren (die im Prinzip eine Bereitstellungsinstanz ist). Sie müssen beide Werte auf der NetApp Support-Website beim Generieren der NetApp License File (NLF) angeben.

Sie können die Lizenzsperre-ID für Ihre Deploy-Instanz mithilfe der Web-Benutzeroberfläche auf folgende Weise bestimmen:

* Seite „erste Schritte“ Diese Seite wird angezeigt, wenn Sie sich zum ersten Mal bei der Bereitstellung anmelden. Sie können die Seite auch anzeigen, indem Sie auf das Dropdown-Feld oben rechts auf der Seite klicken und „erste Schritte“ auswählen. Die LLID wird im Abschnitt Lizenzen hinzufügen angezeigt.
* Verwaltung Klicken Sie oben auf der Seite auf die Registerkarte *Administration* und dann auf *Systeme* und *Einstellungen*.




== Basis-Leasing-Operationen

Ein ONTAP Select Node muss bei jedem Erstellen, erweitern oder Ändern eines Datenaggregats einen gültigen Kapazitätsleast anfordern oder anfordern. Es kann ein Leasing aus einer vorherigen Anfrage verwendet werden, das noch gültig ist, oder bei Bedarf ein neuer Leasing angefordert werden. Der ONTAP Select Node unternimmt folgende Schritte, um einen Kapazitäts-Pool-Leasing ausfindig zu machen:

. Wenn sich ein vorhandener Leasing auf dem Node befindet, wird er verwendet, solange alle folgenden Fällen zutrifft:
+
** Leasing ist noch nicht abgelaufen
** Die Storage-Anforderung für das Aggregat überschreitet nicht die Leasing-Kapazität


. Wenn ein vorhandener Leasing nicht gefunden werden kann, fordert der Node vom License Manager ein neues Leasing an.




== Rückgabe der Speicherkapazität an einen Kapazitäts-Pool

Die Speicherkapazität wird je nach Bedarf aus einem Kapazitäts-Pool zugewiesen, und jede neue Anforderung kann den verfügbaren Speicher im Pool verringern. Die Storage-Kapazität wird in verschiedenen Situationen an den Pool zurückgegeben. Dies umfasst:

* Eine Leasing-Option für ein Datenaggregat läuft ab und wird nicht durch den Node verlängert
* Das Datenaggregat wird gelöscht



NOTE: Wenn eine ONTAP Select Virtual Machine gelöscht wird, bleiben aktive Leasing-Verträge bis zum Ablaufdatum verfügbar. In diesem Fall wird die Kapazität wieder in den Pool zurückgeführt.
