---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: Das Lizenzmodell für Kapazitäts-Pools unterscheidet sich vom Modell für Kapazitäts-Tiers. Die Storage-Kapazität wird jedem einzelnen Node nicht mehr bereitgestellt, sondern einem Pool zugewiesen, der von vielen Nodes gemeinsam genutzt wird. Zur Unterstützung des Kapazitäts-Pools-Modells wurden zusätzliche Komponenten und Prozesse erstellt. 
---
= Operative Details des ONTAP Select Kapazitäts-Pools-Lizenzmodells
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Lizenzmodell für Kapazitäts-Pools unterscheidet sich vom Modell für Kapazitäts-Tiers. Die Storage-Kapazität wird jedem einzelnen Node nicht mehr bereitgestellt, sondern einem Pool zugewiesen, der von vielen Nodes gemeinsam genutzt wird. Zur Unterstützung des Kapazitäts-Pools-Modells wurden zusätzliche Komponenten und Prozesse erstellt.



== Lizenzmanager

Der License Manager wird in jeder Instanz des Dienstprogramms Deploy Administration als separater Prozess ausgeführt. Einige der von LM bereitgestellten Funktionen umfassen:

* Basierend auf der Lizenznummer des Kapazitäts-Pools wird für jeden Node eine eindeutige, zwanzig-stellige Seriennummer generiert
* Erstellung von Leasingverträgen für Kapazität aus den Pools mit gemeinsam genutzter Kapazität basierend auf Anforderungen der ONTAP Select Nodes
* Erstellen Sie Informationen zur Pool-Nutzung über die Benutzeroberfläche „Bereitstellen“




== Leasing-Merkmale

Dem für jedes Datenaggregat auf einem Node mit einer Lizenz im Kapazitäts-Pool zugewiesenen Storage muss ein Leasing zugewiesen sein. Der Node fordert ein Storage-Leasing an, und wenn die Kapazität verfügbar ist, reagiert der License Manager mit einem Leasing. Jeder Leasingvertrag hat die folgenden expliziten oder impliziten Attribute:

* Lizenzmanager
+
Jeder ONTAP Select Node ist einer License Manager Instanz zugeordnet

* Kapazitätspool
+
Jeder ONTAP Select Node ist einem Capacity Pool zugeordnet

* Speicherzuweisung
+
Ein bestimmter Kapazitätswert wird im Leasingvertrag zugewiesen

* Ablaufdatum und Uhrzeit
+
Die Laufzeit der Leases liegt je nach Benutzerkonfiguration zwischen einer Stunde und sieben Tagen.





== Lizenzsperre ID

Jede Instanz des License Manager und damit jede entsprechende Deploy Utility-Instanz wird mit einer eindeutigen 128-Bit-Nummer identifiziert. Diese Nummer wird mit der neunstelligen Lizenz-Seriennummer für den Kapazitätspool kombiniert, um den Pool für eine bestimmte License Manager-Instanz zu sperren (die im Prinzip eine Bereitstellungsinstanz ist). Sie müssen beide Werte auf der NetApp Support-Website beim Generieren der NetApp License File (NLF) angeben.

Sie können die Lizenzsperre-ID für Ihre Deploy-Instanz mithilfe der Web-Benutzeroberfläche auf folgende Weise bestimmen:

* Erste Schritte-Seite
+
Deploy zeigt diese Seite an, wenn Sie sich zum ersten Mal anmelden. Sie können auch das Dropdown-Menü oben rechts auf der Seite öffnen und *Getting Started* auswählen, um diese Seite anzuzeigen. Die LLID wird im Abschnitt Add Licenses angezeigt.

* Wählen Sie oben auf der Seite die Registerkarte *Administration* und dann *Systeme & AutoSupport* aus.




== Basis-Leasing-Operationen

Ein ONTAP Select-Knoten muss jedes Mal, wenn ein Datenaggregat erstellt, erweitert oder geändert wird, eine gültige Kapazitätslizenz finden oder anfordern. Sie können eine aus einer vorherigen Anfrage erhaltene, noch gültige Lizenz verwenden oder bei Bedarf eine neue anfordern. Der ONTAP Select-Knoten führt die folgenden Schritte aus, um eine Capacity Pool-Lizenz zu finden:

. Wenn sich ein vorhandener Leasing auf dem Node befindet, wird er verwendet, solange alle folgenden Fällen zutrifft:
+
** Leasing ist noch nicht abgelaufen
** Die Storage-Anforderung für das Aggregat überschreitet nicht die Leasing-Kapazität


. Wenn ein vorhandener Leasing nicht gefunden werden kann, fordert der Node vom License Manager ein neues Leasing an.




== Rückgabe der Speicherkapazität an einen Kapazitäts-Pool

Die Speicherkapazität wird je nach Bedarf aus einem Kapazitäts-Pool zugewiesen, und jede neue Anforderung kann den verfügbaren Speicher im Pool verringern. Die Storage-Kapazität wird in verschiedenen Situationen an den Pool zurückgegeben. Dies umfasst:

* Eine Leasing-Option für ein Datenaggregat läuft ab und wird nicht durch den Node verlängert
* Das Datenaggregat wird gelöscht



NOTE: Wenn eine ONTAP Select Virtual Machine gelöscht wird, bleiben aktive Leasing-Verträge bis zum Ablaufdatum verfügbar. In diesem Fall wird die Kapazität wieder in den Pool zurückgeführt.
