---
sidebar: sidebar 
permalink: reference_api_workflow.html 
keywords: rest api, deploy rest api, rest, workflow, create cluster, curl, json 
summary: Sie können einen ONTAP Select Cluster mit einem einzelnen Knoten auf einem von VMware ESXi verwalteten Host, der von vCenter gemanagt wird, bereitstellen. 
---
= Erstellung eines ONTAP Select Einzelknoten Evaluierungsclusters auf ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können ein Single-Node ONTAP Select Cluster auf einem von vCenter verwalteten VMware ESXi Host implementieren. Der Cluster wird mit einer Evaluierungslizenz erstellt.

Der Workflow für die Cluster-Erstellung unterscheidet sich in folgenden Situationen:

* Der ESXi-Host wird nicht von vCenter verwaltet (eigenständiger Host).
* Innerhalb des Clusters werden mehrere Nodes oder Hosts verwendet.
* Der Cluster ist in einer Produktionsumgebung mit einer erworbenen Lizenz implementiert.
* Anstelle von VMware ESXi wird der KVM Hypervisor verwendet.




[[step-1-register-vcenter-server-credential]]
== Schritt 1: vCenter Server-Anmeldeinformationen registrieren

Bei der Bereitstellung auf einem von einem vCenter Server verwalteten ESXi-Host ist es erforderlich, vor der Registrierung des Hosts Anmeldeinformationen hinzuzufügen. Das Dienstprogramm Deploy kann dann die Anmeldeinformationen zur Authentifizierung bei vCenter verwenden.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Implementieren | POST | /Sicherheit/Anmeldedaten 
|===
Curl::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step01 'https://10.21.191.150/api/security/credentials'
----
JSON-Eingabe (Schritt 01)::


[source, json]
----
{
  "hostname": "vcenter.company-demo.com",
  "type": "vcenter",
  "username": "misteradmin@vsphere.local",
  "password": "mypassword"
}
----
Verarbeitungsart:: Asynchron
Ausgabe::
+
--
* Anmeldeinformations-ID in der Kopfzeile für Standortantwort
* Jobobjekt


--




[[step-2-register-a-hypervisor-host]]
== Schritt 2: Registrierung eines Hypervisor-Hosts

Einen Hypervisor-Host hinzufügen, auf dem die virtuelle Maschine mit dem ONTAP Select Node ausgeführt wird.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Cluster | POST | /Hosts 
|===
Curl::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step02 'https://10.21.191.150/api/hosts'
----
JSON-Eingabe (Schritt 02)::


[source, json]
----
{
  "hosts": [
    {
      "hypervisor_type": "ESX",
      "management_server": "vcenter.company-demo.com",
      "name": "esx1.company-demo.com"
    }
  ]
}
----
Verarbeitungsart:: Asynchron
Ausgabe::
+
--
* Host-ID in der Kopfzeile der Standortantwort
* Jobobjekt


--




[[step-3-create-a-cluster]]
== Schritt 3: Einen Cluster erstellen

Wenn ein ONTAP Select Cluster erstellt wird, wird die grundlegende Clusterkonfiguration registriert und Deploy generiert die Node-Namen automatisch.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Cluster | POST | /Cluster 
|===
Curl:: Der Abfrageparameter node_count ist für einen Einzelknotencluster auf 1 zu setzen.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step03 'https://10.21.191.150/api/clusters? node_count=1'
----
JSON-Eingang (Schritt 03)::


[source, json]
----
{
  "name": "my_cluster"
}
----
Verarbeitungsart:: Synchron
Ausgabe::
+
--
* Cluster-ID in der Kopfzeile für Speicherantwort


--




[[step-4-configure-the-cluster]]
== Schritt 4: Das Cluster konfigurieren

Im Rahmen der Clusterkonfiguration müssen Sie die folgenden Attribute angeben.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Cluster | PATCH | /Clusters/{Cluster_id} 
|===
Curl:: Die Cluster-ID angeben.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step04 'https://10.21.191.150/api/clusters/CLUSTERID'
----
JSON-Eingang (Schritt 04)::


[source, json]
----
{
  "dns_info": {
    "domains": ["lab1.company-demo.com"],
    "dns_ips": ["10.206.80.135", "10.206.80.136"]
    },
    "ontap_image_version": "9.5",
    "gateway": "10.206.80.1",
    "ip": "10.206.80.115",
    "netmask": "255.255.255.192",
    "ntp_servers": {"10.206.80.183"}
}
----
Verarbeitungsart:: Synchron
Ausgabe:: Keine




[[step-5-retrieve-the-node-name]]
== Schritt 5: Node-Name abrufen

Das Deploy Verwaltungsprogramm generiert beim Erstellen eines Clusters automatisch die Node-IDs und Node-Namen. Vor der Konfiguration eines Node muss die zugewiesene ID abgerufen werden.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Cluster | GET | /Clusters/{Cluster_id}/Nodes 
|===
Curl:: Die Cluster-ID angeben.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/clusters/CLUSTERID/nodes?fields=id,name'
----
Verarbeitungsart:: Synchron
Ausgabe::
+
--
* Array zeichnet alle, die einen einzelnen Knoten mit der eindeutigen ID und dem Namen beschreiben


--




[[step-6-configure-the-nodes]]
== Schritt 6: Die Nodes konfigurieren

Die Basiskonfiguration für den Node bereitstellen, dies ist der erste von drei API-Aufrufen, die zur Konfiguration eines Node verwendet werden.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Cluster | PFAD | /Clusters/{Cluster_id}/Nodes/{Node_id} 
|===
Curl:: Die Cluster-ID und die Node-ID angeben.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step06 'https://10.21.191.150/api/clusters/CLUSTERID/nodes/NODEID'
----
JSON-Eingabe (Schritt 06):: Die Host-ID angeben, auf der der ONTAP Select Node ausgeführt wird.


[source, json]
----
{
  "host": {
    "id": "HOSTID"
    },
  "instance_type": "small",
  "ip": "10.206.80.101",
  "passthrough_disks": false
}
----
Verarbeitungsart:: Synchron
Ausgabe:: Keine




[[step-7-retrieve-the-node-networks]]
== Schritt 7: Knotennetzwerke abrufen

Die Daten- und Managementnetzwerke, die vom Node im Single-Node-Cluster verwendet werden, sind zu identifizieren. Das interne Netzwerk wird bei einem Single-Node-Cluster nicht verwendet.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Cluster | GET | /Clusters/{Cluster_id}/Nodes/{Node_id}/Netzwerke 
|===
Curl:: Die Cluster-ID und die Node-ID angeben.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/ clusters/CLUSTERID/nodes/NODEID/networks?fields=id,purpose'
----
Verarbeitungsart:: Synchron
Ausgabe::
+
--
* Array mit zwei Datensätzen, die jeweils ein einziges Netzwerk für den Knoten beschreiben, einschließlich der eindeutigen ID und des Zwecks


--




[[step-8-configure-the-node-networking]]
== Schritt 8: Node-Netzwerk konfigurieren

Die Daten- und Managementnetzwerke werden konfiguriert. Das interne Netzwerk wird bei einem Single-Node-Cluster nicht verwendet.


NOTE: Geben Sie den folgenden API-Aufruf zweimal ein, einmal für jedes Netzwerk.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Cluster | PATCH | /Clusters/{Cluster_id}/Nodes/{Node_id}/Networks/{Network_id} 
|===
Curl:: Geben Sie die Cluster-ID, die Node-ID und die Netzwerk-ID an.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step08 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID/networks/NETWORKID'
----
JSON-Eingang (Schritt 08):: Den Namen des Netzwerks angeben.


[source, json]
----
{
  "name": "sDOT_Network"
}
----
Verarbeitungsart:: Synchron
Ausgabe:: Keine




[[step-9-configure-the-node-storage-pool]]
== Schritt 9: Konfiguration des Node Storage Pools

Der letzte Schritt beim Konfigurieren eines Node ist das Verbinden eines Speicherpools. Sie können die verfügbaren Speicherpools über den vSphere Web-Client oder optional über die Rest-API implementieren bestimmen.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Cluster | PATCH | /Clusters/{Cluster_id}/Nodes/{Node_id}/Networks/{Network_id} 
|===
Curl:: Geben Sie die Cluster-ID, die Node-ID und die Netzwerk-ID an.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step09 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID'
----
JSON-Eingabe (Schritt 09):: Die Poolkapazität beträgt 2 TB.


[source, json]
----
{
  "pool_array": [
    {
      "name": "sDOT-01",
      "capacity": 2147483648000
    }
  ]
}
----
Verarbeitungsart:: Synchron
Ausgabe:: Keine




[[step-10-deploy-the-cluster]]
== Schritt 10: Cluster bereitstellen

Nachdem das Cluster und der Node konfiguriert wurden, können Sie das Cluster implementieren.

[cols="15,15,70"]
|===
| Kategorie | HTTP-Verb | Pfad 


| Cluster | POST | /Clusters/{Cluster_id}/Deploy 
|===
Curl:: Die Cluster-ID angeben.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step10 'https://10.21.191.150/api/clusters/CLUSTERID/deploy'
----
JSON-Eingang (Schritt 10):: Das Passwort für das ONTAP Administrator-Konto angeben.


[source, json]
----
{
  "ontap_credentials": {
    "password": "mypassword"
  }
}
----
Verarbeitungsart:: Asynchron
Ausgabe::
+
--
* Jobobjekt


--


.Verwandte Informationen
link:deploy-evaluation-ontap-select-ovf-template.html["Implementierung einer 90-Tage-Testinstanz für einen ONTAP Select Cluster"]
