---
sidebar: sidebar 
permalink: reference_initial_state.html 
keywords: install, installing, initial state, cluster initial state 
summary: Sie sollten den anfänglichen Status eines Clusters beachten, nachdem es implementiert wurde, und den Cluster nach Bedarf für die eigene Umgebung konfigurieren. 
---
= Anfangsstatus des ONTAP Select-Clusters nach der Implementierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie sollten den anfänglichen Status eines Clusters beachten, nachdem es implementiert wurde, und den Cluster nach Bedarf für die eigene Umgebung konfigurieren.

Ein ONTAP Select Cluster weist nach dem Erstellen verschiedene Merkmale auf.


NOTE: Durch das Einschränken von Rollen und Berechtigungen für das ONTAP-Administratorkonto kann die Fähigkeit von ONTAP Select Deploy zum Verwalten des Clusters eingeschränkt werden. Weitere Informationen finden Sie im Knowledge Base-Artikel link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/OTS_Deploy_cluster_refresh_fails_with_error%3A_ONTAPSelectSysCLIVersionFailed_zapi_returned_bad_status_0%3A_None["DIE AKTUALISIERUNG DES OTS-Bereitstellungs-Clusters schlägt mit einem Fehler fehl"^].

.LIFs
Es sind zwei Arten von vom Kunden angegebenen LIFs zugewiesen:

* Cluster-Management (eine pro Cluster)
* Node-Management (einer pro Node)



NOTE: Ein Multi-Node-Cluster verfügt über ein internes Netzwerk mit automatisch erstellten LIFs.

.SVMs
Drei SVMs sind aktiv:

* Admin-SVM
* Node-SVM
* System-SVM (Cluster)



NOTE: Data SVMs werden nicht als Teil der ONTAP Select Cluster-Implementierung erstellt. Sie müssen nach der Bereitstellung vom Clusteradministrator erstellt werden. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap/nfs-config/create-svms-data-access-task.html["Erstellen Sie ein SVM"^].

.Aggregate
Das Root-Aggregat wird erstellt.

.Funktionen
Alle Funktionen sind lizenziert und verfügbar. Sowohl SnapLock als auch FabricPool erfordern separate Lizenzen.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap/system-admin/types-svms-concept.html["In einem Cluster enthaltene SVMs-Typen"^]
* link:reference_lic_ontap_features.html["Standardmäßig sind ONTAP-Funktionen aktiviert"]

