---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: Die aktuelle Version enthält mehrere neue Funktionen oder Verbesserungen speziell für ONTAP Select. 
---
= Neuerungen bei ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie mehr über die neuen Funktionen und Verbesserungen der unterstützten Versionen von ONTAP Select.



== ONTAP Select 9.18.1

Verbesserte Unterstützung für die Erweiterung und Verkleinerung von Clustern:: Ab ONTAP Select 9.18.1 wird die Erweiterung und Verkleinerung von Clustern zwischen vier- und zwölf-Knoten ONTAP Select Clustern auf ESXi- und KVM-Hypervisor-Hosts unterstützt.
+
--
--
Sie können die Clustergröße eines bestehenden Clusters auf einem ESXi- oder KVM-Host in folgenden Schritten erhöhen:

* Von vier Knoten auf sechs, acht, zehn oder zwölf Knoten
* Von sechs Knoten auf acht, zehn oder zwölf Knoten
* Von acht Knoten auf zehn oder zwölf Knoten
* Von zehn auf zwölf Knoten


Sie können die Clustergröße eines bestehenden Clusters auf einem ESXi- oder KVM-Host in folgenden Schritten verringern:

* Von zwölf Knoten auf zehn, acht, sechs oder vier Knoten
* Von zehn Knoten auf acht, sechs oder vier Knoten
* Von acht auf sechs oder vier Knoten
* Von sechs auf vier Knoten


--
link:task_cluster_expansion_contraction.html["Erfahren Sie mehr über Cluster-Erweiterung und -Kontraktion sowie die unterstützten KVM- und ESXi-Hypervisor-Versionen"] .

--




== ONTAP Select 9.17.1

Software-RAID-Unterstützung für lokal angeschlossene NVMe-Festplatten auf KVM-Hosts:: ONTAP Select 9.17.1 führt Software-RAID-Unterstützung für lokal angeschlossene ONTAP Select NVMe-Festplatten auf einem Kernel-Based Virtual Machine (KVM)-Hypervisor-Host ein.
+
--
Um Software-RAID für lokal angeschlossene NVMe-Festplatten zu verwenden, müssen Sie link:kvm-host-configuration-and-preparation-checklist.html["PCI-Passthrough konfigurieren (DirectPath IO)"] bei der Vorbereitung des KVM-Hosts. Dadurch erhält der KVM-Host direkten Zugriff auf die lokal angeschlossenen NVMe-Festplatten, was für die folgenden Aufgaben erforderlich ist:

* Konfigurieren des KVM-Hosts zur Verwendung von NVMe-Laufwerken
* Verwenden von Software-RAID nach der Bereitstellung des Clusters


link:concept_stor_swraid_local.html["Erfahren Sie mehr über die Software-RAID-Konfigurationsdienste für lokal angeschlossenen Speicher"] .

--
Unterstützung für Cluster-Erweiterung und -Kontraktion auf KVM-Hosts:: Ab ONTAP Select 9.17.1 wird die Cluster-Erweiterung und -Kontraktion sowohl für Kernel-Based Virtual Machine (KVM) als auch für ESXi-Hypervisor-Hosts unterstützt. Für ONTAP Select 9.16.1 und 9.15.1 wird die Cluster-Erweiterung und -Kontraktion nur für ESXi-Hypervisor-Hosts unterstützt.
+
--
Sie können die Funktion zur Cluster-Erweiterung und -Kontraktion auf einem vorhandenen ONTAP Select Cluster verwenden, um die Größe von einem Cluster mit sechs Knoten auf einen Cluster mit acht Knoten zu erhöhen oder die Größe von einem Cluster mit acht Knoten auf einen Cluster mit sechs Knoten zu verringern.

link:task_cluster_expansion_contraction.html["Erfahren Sie mehr über Cluster-Erweiterung und -Kontraktion sowie die unterstützten KVM- und ESXi-Hypervisor-Versionen"] .

--
Verbesserte Unterstützung für Cluster-Erweiterung und -Kontraktion auf ESXi-Hosts:: Ab ONTAP Select 9.17.1 wird die Clustererweiterung und -verkleinerung zwischen Sechs-Knoten- und Zwölf-Knoten-Clustern auf ESXi-Hosts unterstützt:
+
--
--
Sie können die Clustergröße für einen vorhandenen ESXi-Cluster in den folgenden Schritten erhöhen:

* Von sechs Knoten auf acht, zehn oder zwölf Knoten
* Von acht Knoten auf zehn oder zwölf Knoten
* Von zehn auf zwölf Knoten


Sie können die Clustergröße für einen vorhandenen ESXi-Cluster in den folgenden Schritten verringern:

* Von zwölf Knoten auf zehn, acht oder sechs Knoten
* Von zehn Knoten auf acht oder sechs Knoten
* Von acht auf sechs Knoten


--
link:task_cluster_expansion_contraction.html["Erfahren Sie mehr über Cluster-Erweiterung und -Kontraktion sowie die unterstützten KVM- und ESXi-Hypervisor-Versionen"] .

--
Unterstützung für SnapMirror Cloud:: Ab ONTAP Select 9.17.1 wird SnapMirror Cloud mit ONTAP Select unterstützt. SnapMirror Cloud ist eine lizenzierte ONTAP Funktion, die standardmäßig aktiviert ist, wenn Sie einen ONTAP Select 9.17.1-Cluster bereitstellen oder einen vorhandenen ONTAP Select Cluster auf Version 9.17.1 aktualisieren.
+
--
https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["Erfahren Sie mehr über SnapMirror Cloud-Backups auf Objektspeicher"^] .

--
Support für SnapLock Select Enterprise:: Ab ONTAP Select 9.17.1 ist SnapLock Select Enterprise (einschließlich manipulationssicherer Snapshot-Sperre) für neue Bereitstellungen automatisch lizenziert.  Für Upgrades von ONTAP Select 9.16.1 und früher müssen Sie die SnapLock Select-Lizenz von derlink:https://mysupport.netapp.com/site/["NetApp Support Website"^] und wenden Sie es manuell an.
Unterstützung für vSAN ESA auf Clustern mit mehreren Knoten:: Ab ONTAP Select 9.17.1 wird die Unterstützung für vSAN Express Storage Architecture (ESA) erweitert, um Cluster mit mehreren Knoten bereitzustellen.  Diese Erweiterung ermöglicht Ihnen die Bereitstellung von vSAN ESA-Konfigurationen.
+
--
vSAN ESA ist eine ESX-spezifische Konfiguration und eine neue Architektur für VMware vSAN, die in vSphere 8 eingeführt wurde. vSAN ESA wurde entwickelt, um verbesserte Effizienz, Skalierbarkeit und Leistung zu bieten, insbesondere bei der Verwendung von NVMe-basierten TLC-Flash-Geräten.

ONTAP Select Deploy und ONTAP Select für ESX unterstützen die Konfiguration eines ONTAP Select Clusters mit einem oder mehreren Knoten, wobei entweder ein vSAN oder ein externer Array-Datenspeichertyp für den Speicherpool verwendet wird.

[NOTE]
====
Um Vorgänge in der Inhaltsbibliothek durchzuführen, benötigen Sie Zugriff auf zusätzliche Berechtigungsstufen.  Dies ist für vSAN ESA-Bereitstellungen erforderlich, wenn Sie mit eingeschränkten Rollen arbeiten.

link:https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html["Informationen zum Zugriff auf Berechtigungsstufen für Vorgänge in der Inhaltsbibliothek"^] .

====
--
Aktualisierte NDA-Treiberunterstützung:: Ab ONTAP Select 9.17.1 ersetzt der FreeBSD NDA-Gerätetreiber (NVMe Direct Access) den NVD-Treiber (NVMe Express Disk Driver). Der FreeBSD-Treiber unterstützt Direktzugriffsgeräte durch Implementierung des NVMe-Befehlsprotokolls. Wenn Sie einen ONTAP Select 9.17.1-Cluster bereitstellen oder einen vorhandenen ONTAP Select Cluster auf Version 9.17.1 aktualisieren, wird der FreeBSD-Treiber standardmäßig gestartet, wenn Sie die NVMe-Geräte konfigurieren.
+
--
Für ONTAP Select 9.16.1 und früher bietet NVD weiterhin Unterstützung für NVMe-Geräte in Ihrer ONTAP Select Bereitstellung.

--
Aktualisierte KVM-Hypervisor-Unterstützung:: Ab ONTAP Select 9.17.1 wird der KVM-Hypervisor auf Red Hat Enterprise Linux (RHEL) 9.6 und Rocky Linux 9.6 unterstützt.
Verbesserte Unterstützung von VMware ESXi:: ONTAP Select 9.17.1 beinhaltet Unterstützung für VMware ESXi 9.0.




== ONTAP Select 9.16.1

Unterstützung für NetApp-Lizenzdateien aktualisiert:: Ab ONTAP Select 9.16.1 wird die Unterstützung für die NetApp-Lizenzdatei (NLF) aktualisiert. Das neue NF-Format umfasst Lizenzen für die Funktionen ARP, ONTAP S3 und S3 SnapMirror. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Weitere Informationen ."].
+
--
Für ein neues ONTAP Select 9.16.1 Deploy wird das neue NF-Format automatisch angewendet. Wenn Sie eine vorhandene ONTAP Select-Bereitstellung auf 9.16.1 aktualisieren, wird das neue NF-Format nicht angewendet. Um die Lizenzen der ARP-, ONTAP S3- und S3-SnapMirror-Funktionen zu erhalten, müssen Sie nach dem Upgrade die aktualisierte Lizenzdatei herunterladen. Wenn Sie zu ONTAP Select 9.15.1 oder früher zurückkehren, müssen Sie die vor dem Upgrade vorhandenen Funktionslizenzen neu installieren.

--
Unterstützung für den autonomen Ransomware-Schutz:: In ONTAP Select 9.16.1 wird die Unterstützung für Autonomous Ransomware Protection (ARP) eingeführt. ONTAP Select 9.16.1 unterstützt nur manuelle Updates für ARP, automatische Updates werden nicht unterstützt. Die ARP-Funktionslizenz ist in der Lizenzdatei für ONTAP Select 9.16.1 enthalten. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Weitere Informationen ."].
Verbesserte Unterstützung von VMware ESXi:: ONTAP Select 9.16.1 unterstützt VMware ESXi 8.0 U3.
Aktualisierte KVM-Hypervisor-Unterstützung:: Ab ONTAP Select 9.16.1 wird der KVM-Hypervisor auf RHEL 9.5 und Rocky Linux 9.5 unterstützt.




== ONTAP Select 9.15.1

Aktualisierte KVM-Hypervisor-Unterstützung:: Ab ONTAP Select 9.15.1 wird der Kernel-basierte Virtual Machine (KVM)-Hypervisor unter RHEL 9.4 und Rocky Linux 9.4 unterstützt.
Unterstützung für Erweiterung und Verkleinerung von Clustern:: Ab ONTAP Select 9.15.1 wird die Erweiterung und Verkleinerung von Clustern unterstützt.
+
--
* Cluster-Erweiterung von Clustern mit sechs Nodes auf Cluster mit acht Nodes
+
Mit der Cluster-Erweiterungsfunktion können Sie die Cluster-Größe von einem Cluster mit sechs Nodes auf ein Cluster mit acht Nodes erhöhen. Cluster-Erweiterungen von Clustern mit einem, zwei oder vier Nodes auf Cluster mit sechs oder acht Nodes werden derzeit nicht unterstützt. link:task_cluster_expansion_contraction.html#expand-the-cluster["Weitere Informationen ."].

* Cluster-Kontraktion von Clustern mit acht Nodes auf sechs Nodes
+
Sie können die Cluster-Größe von einem Cluster mit acht Nodes auf ein Cluster mit sechs Nodes mit der Cluster-Kontraktionsfunktion verringern. Cluster-Kontraktionen von Clustern mit sechs oder acht Nodes zu Clustern mit einem, zwei oder vier Nodes werden derzeit nicht unterstützt. link:task_cluster_expansion_contraction.html#contract-the-cluster["Weitere Informationen ."].



--



NOTE: Die Unterstützung für Cluster-Erweiterung und -Verkleinerung ist auf ESX Cluster beschränkt.



== ONTAP Select 9.14.1

Unterstützung für KVM-Hypervisor:: Ab ONTAP Select 9.14.1 wurde die Unterstützung für KVM-Hypervisor wieder aufgenommen. Zuvor wurde in ONTAP Select 9.10.1 die Unterstützung für die Implementierung eines neuen Clusters auf einem KVM-Hypervisor entfernt, und in ONTAP Select 9.11.1 wurde die Unterstützung für das Management vorhandener KVM-Cluster und -Hosts entfernt, mit Ausnahme des Offline- bzw. Löschens.
Implementierung des VMware vCenter Plug-ins wird nicht mehr unterstützt:: Ab ONTAP Select 9.14.1 wird das Deploy VMware vCenter Plug-in nicht mehr unterstützt.
Aktualisierte Unterstützung für ONTAP Select Deploy:: Wenn Sie eine Version von ONTAP Select Deploy 9.14.1 verwenden, die niedriger als 9.14.1P2 ist, sollten Sie so bald wie möglich auf ONTAP Select Deploy 9.14.1P2 aktualisieren. Weitere Informationen finden Sie im link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Versionshinweise zu ONTAP Select 9.14.1"^].
Verbesserte Unterstützung von VMware ESXi:: ONTAP Select 9.14.1 umfasst Unterstützung für VMware ESXi 8.0 U2.




== ONTAP Select 9.13.1

Unterstützung für NVMe over TCP:: Wenn Sie ein Upgrade auf ONTAP Select 9.13.1 durchführen, benötigen Sie die neue Lizenz zur Unterstützung von NVMe over TCP. Diese Lizenz ist automatisch enthalten, wenn Sie ONTAP Select zum ersten Mal ab Version 9.13.1 bereitstellen.
Aktualisierte Unterstützung von VMware ESXi:: Ab ONTAP 9.13.1 wird VMware ESXi 8.0.1 GA (Build 20513097) mit Hardwareversion 4 und höher unterstützt.
Aktualisierte Unterstützung für ONTAP Select Deploy:: Seit April 2024 ist ONTAP Select Deploy 9.13.1 nicht mehr auf der NetApp Support-Website verfügbar. Falls Sie ONTAP Select Deploy 9.13.1 verwenden, sollten Sie so bald wie möglich auf ONTAP Select Deploy 9.14.1P2 aktualisieren. Weitere Informationen finden Sie im link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Versionshinweise zu ONTAP Select 9.14.1"^].




== ONTAP Select 9.12.1

ONTAP Select 9.12.1 profitiert von den meisten neuen Entwicklungen in der aktuellen Version des zentralen ONTAP Produkts. Es enthält keine neuen Funktionen oder Verbesserungen speziell für ONTAP Select.

Seit April 2024 ist ONTAP Select Deploy 9.12.1 nicht mehr auf der NetApp Support-Website verfügbar. Falls Sie ONTAP Select Deploy 9.12.1 verwenden, sollten Sie so bald wie möglich auf ONTAP Select Deploy 9.14.1P2 aktualisieren. Weitere Informationen finden Sie im link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Versionshinweise zu ONTAP Select 9.14.1"^].



== ONTAP Select 9.11.1

Verbesserte Unterstützung von VMware ESXi:: ONTAP Select 9.11.1 bietet Unterstützung für VMware ESXi 7.0 U3C.
Unterstützung für VMware NSX-T:: ONTAP Select 9.10.1 und neuere Versionen wurden für VMware NSX-T Version 3.1 qualifiziert. Bei Verwendung von NSX-T mit einem ONTAP Select Single-Node-Cluster, das mit einer OVA-Datei und dem ONTAP Select Deploy-Administrationsprogramm bereitgestellt wird, gibt es keine funktionalen Probleme oder Mängel. Wenn Sie jedoch NSX-T mit einem ONTAP Select Cluster mit mehreren Nodes verwenden, sollten Sie die folgende Einschränkung für ONTAP Select 9.11.1 beachten:
+
--
* Prüfung der Netzwerkkonnektivität
+
Der über die Bereitstellungs-CLI verfügbare Netzwerk-Konnektivitätsprüfer schlägt fehl, wenn er in einem NSX-T-basierten Netzwerk ausgeführt wird.



--
KVM-Hypervisor wird nicht mehr unterstützt::
+
--
* Ab ONTAP Select 9.10.1 können Sie kein neues Cluster mehr auf dem KVM-Hypervisor implementieren.
* Ab ONTAP Select 9.11.1 sind alle Managementfunktionen nicht mehr für vorhandene KVM-Cluster und -Hosts verfügbar, mit Ausnahme der Funktionen zum Offline- und Löschen.
+
NetApp empfiehlt seinen Kunden nachdrücklich, eine vollständige Datenmigration von ONTAP Select für KVM auf eine andere ONTAP Plattform, einschließlich ONTAP Select für ESXi, zu planen und durchzuführen. Weitere Informationen finden Sie im https://mysupport.netapp.com/info/communications/ECMLP2877451.html["EOA-Mitteilung"^]



--




== ONTAP Select 9.10.1

Unterstützung für VMware NSX-T:: ONTAP Select 9.10.1 ist für VMware NSX-T Version 3.1 qualifiziert. Bei Verwendung von NSX-T mit einem ONTAP Select Single-Node-Cluster, das mit einer OVA-Datei und dem ONTAP Select Deploy-Administrationsprogramm bereitgestellt wird, gibt es keine funktionalen Probleme oder Mängel. Wenn Sie jedoch NSX-T mit einem ONTAP Select Multi-Node-Cluster verwenden, sollten Sie die folgenden Anforderungen und Einschränkungen beachten:
+
--
* Cluster-MTU
+
Sie müssen die MTU-Größe des Clusters manuell auf 8800 anpassen, bevor Sie den Cluster bereitstellen, um den zusätzlichen Overhead zu berücksichtigen. Die Anleitung von VMware dient dazu, bei Verwendung von NSX-T. einen 200-Byte-Puffer zu ermöglichen

* 4x10-Gbit-Netzwerk-Konfiguration
+
Bei ONTAP Select-Bereitstellungen auf einem VMware ESXi Host, der mit vier NICs konfiguriert ist, werden Sie vom Deploy-Dienstprogramm aufgefordert, die Best Practice beim Aufteilen des internen Verkehrs auf zwei verschiedene Port-Gruppen und externen Datenverkehr über zwei verschiedene Port-Gruppen zu befolgen. Bei der Verwendung eines Overlay-Netzwerks funktioniert diese Konfiguration jedoch nicht und Sie sollten die Empfehlung ignorieren. In diesem Fall sollten Sie stattdessen nur eine interne Portgruppe und eine externe Portgruppe verwenden.

* Prüfung der Netzwerkkonnektivität
+
Der über die Bereitstellungs-CLI verfügbare Netzwerk-Konnektivitätsprüfer schlägt fehl, wenn er in einem NSX-T-basierten Netzwerk ausgeführt wird.



--
KVM-Hypervisor wird nicht mehr unterstützt:: Ab ONTAP Select 9.10.1 können Sie kein neues Cluster mehr auf dem KVM-Hypervisor implementieren. Wenn Sie jedoch ein Cluster von einer früheren Version auf 9.10.1 aktualisieren, können Sie das Dienstprogramm Deploy weiterhin zum Verwalten des Clusters verwenden.




== ONTAP Select 9.9.1

Unterstützung für Prozessorfamilien:: Ab ONTAP Select 9.9 werden nur CPU-Modelle von Intel Xeon Sandy Bridge oder höher für ONTAP Select unterstützt.
Aktualisierte Unterstützung von VMware ESXi:: Die Unterstützung für VMware ESXi wurde mit ONTAP Select 9.9 verbessert. Folgende Versionen werden jetzt unterstützt:
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

Hochgeschwindigkeits-Schnittstelle:: Die High-Speed-Schnittstelle bietet eine Option für 25 GbE und 40 Gbit (40 GbE), um die Netzwerkkonnektivität zu verbessern. Um die beste Performance beim Einsatz dieser höheren Geschwindigkeiten zu erreichen, sollten Sie die Best Practices für die Zuordnung von Ports befolgen, wie in der ONTAP Select-Dokumentation beschrieben.
Aktualisierte Unterstützung von VMware ESXi:: Es gibt zwei Änderungen an ONTAP Select 9.8 in Bezug auf die Unterstützung für VMware ESXi.
+
--
* Unterstützung von ESXi 7.0 (GA Build 15843807 und höher)
* ESXi 6.0 wird nicht mehr unterstützt


--

