---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select bietet vollständige Unterstützung für die meisten ONTAP Funktionen. Viele ONTAP Funktionen werden bei Implementierung eines Clusters automatisch für jeden Node lizenziert. Einige Funktionen erfordern jedoch eine separate Lizenz. 
---
= ONTAP Select-Unterstützung für ONTAP-Funktionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select unterstützt die meisten ONTAP Funktionen. Viele der ONTAP -Funktionen werden bei der Bereitstellung eines Clusters automatisch für jeden Knoten lizenziert. Für einige Funktionen ist jedoch eine separate Lizenz erforderlich.


NOTE: ONTAP Funktionen mit hardwarespezifischen Abhängigkeiten werden in der Regel nicht von ONTAP Select unterstützt.



== ONTAP Funktionen werden standardmäßig automatisch aktiviert

Die folgenden ONTAP Funktionen werden von ONTAP Select unterstützt und standardmäßig lizenziert:

* Autonomous Ransomware Protection (ARP) (manuelle Updates)
* CIFS
* Deduplizierung und Komprimierung
* FlexCache
* FlexClone
* ISCSI
* NDMP
* NetApp Volume Encryption (nur in Ländern ohne Beschränkungen)
* NFS
* NVMe über TCP –
* ONTAP Mandantenfähigkeit
* ONTAP S3
* S3 SnapMirror
* SnapMirror
* SnapMirror Cloud
* SnapRestore
* SnapVault
* Disaster Recovery für Storage VM (SVM DR)
+

NOTE: ONTAP Select unterstützt SVM DR als Quelle und Ziel mit maximal 16 Beziehungen. Die DR-Unterstützung der SVM ist auf die Verwendung der Quell-ONTAP-Version auf Version +2 beschränkt. Beispielsweise kann die ONTAP Select 9.12.1 Quelle eine Verbindung mit den Ziel-ONTAP-Versionen 9.12.1, 9.13.1 oder 9.14.1 herstellen.





== ONTAP-Funktionen, die separat lizenziert werden

Sie müssen für alle ONTAP -Funktionen, die nicht standardmäßig aktiviert sind, eine separate Lizenz erwerben, darunter:

* FabricPool
* MetroCluster SDS (ONTAP Select Premium-Lizenzangebot)


[NOTE]
====
* Für ONTAP Select 9.16.1 und früher ist SnapLock Select Enterprise (einschließlich manipulationssicherer Snapshot-Sperre) verfügbar über dielink:https://mysupport.netapp.com/site/["NetApp Support Website"^] .
* SnapLock Compliance wird für ONTAP Select nicht unterstützt.
* Sie brauchen keine FabricPool Lizenz, wenn Sie StorageGRID nutzen.


====
.Verwandte Informationen
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Vergleich von ONTAP Select und ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Master-Lizenzschlüssel für NetApp ONTAP"^]

