---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: Bei der Planung der Installation des ONTAP Select Deploy Administration Utility sollten Sie verschiedene allgemeine Anforderungen berücksichtigen. 
---
= ONTAP Select allgemeine Anforderungen bereitstellen und planen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bei der Planung der Installation des ONTAP Select Deploy Administration Utility sollten Sie verschiedene allgemeine Anforderungen berücksichtigen.



== Paarung des Dienstprogramms „Bereitstellen“ mit den ONTAP Select-Clustern

Beim Pairing einer Instanz des Dienstprogramms „Bereitstellen“ mit den ONTAP Select-Clustern stehen Ihnen verschiedene Optionen zur Verfügung.


NOTE: In allen Implementierungsszenarien können ein einzelnes ONTAP Select-Cluster und die Nodes im Cluster nur von einer Instanz des Deploy-Administration Utility gemanagt werden. Ein Cluster kann nicht von zwei oder mehr verschiedenen Instanzen des Deploy Utility gemanagt werden.

.Eine Instanz des Dienstprogramms für jedes ONTAP Select Cluster
Sie können jedes ONTAP Select Cluster mit einer dedizierten Instanz des Deploy Utility implementieren und managen. Mit dieser 1:1-Konfiguration besteht eine klare Trennung zwischen den einzelnen Kombinationen von Utility-to-Cluster. Diese Konfiguration bietet ein hohes Maß an Isolation bei kleineren Ausfall-Domains.

.Eine Instanz des Dienstprogramms für mehrere ONTAP Select Cluster
Sie können mehrere ONTAP Select Cluster in Ihrem Unternehmen mithilfe einer einzigen Instanz des Deploy Utility implementieren und managen. Bei dieser 1:n-Konfiguration werden alle Verarbeitungs- und Konfigurationsdaten über dieselbe Instanz des Deploy Utility gemanagt.


NOTE: Eine Instanz des Deploy Utility kann bis zu 400 ONTAP Select Nodes oder 100 Cluster verwalten.



== Anforderungen in Bezug auf die KVM-Umgebung

Bevor Sie das Dienstprogramm Deploy Administration in einer KVM-Hypervisor-Umgebung installieren, sollten Sie die grundlegenden Anforderungen überprüfen und die Bereitstellung vorbereiten.

.Anforderungen und Einschränkungen für eine Bereitstellung
Es gibt mehrere Anforderungen und Einschränkungen, die Sie bei der Installation des ONTAP Select Deploy-Dienstprogramms in einer KVM-Umgebung beachten sollten.

.Hardwareanforderungen für Linux KVM-Host-Server
Es gibt mehrere Mindestressourcenanforderungen, die Ihr Linux KVM-Hypervisor-Host erfüllen muss. Vergewissern Sie sich, dass die Hosts, auf denen ONTAP Select bereitgestellt ist, die folgenden grundlegenden Anforderungen erfüllen:

* Linux-Server:
+
** Die Hardware und Software muss 64-Bit sein
** Der Server muss die gleichen unterstützten Versionen einhalten, die für einen ONTAP Select-Knoten definiert sind


* Virtuelle CPUs (2)
* Virtueller Speicher (4 GB)
* Speicher (40 GB)
* „Dynamic Host Configuration Protocol (DHCP) ist aktiviert (Sie können auch eine statische IP-Adresse zuweisen).


.Netzwerk-Konnektivität
Stellen Sie sicher, dass die Netzwerkschnittstelle für die Bereitstellung der virtuellen Maschine konfiguriert ist und eine Verbindung zu den von ihr verwalteten ONTAP Select-Hosts herstellen kann.

.Unterstützung für IP Version 4
ONTAP Select Deploy unterstützt nur IP Version 4 (IPv4). Die IP-Version 6 (IPv6) wird nicht unterstützt. Diese Einschränkung wirkt sich auf ONTAP Select aus wie folgt aus:

* Sie müssen der Management-LIF der bereitzustellenden VM eine IPv4-Adresse zuweisen.
* Deploy kann keine ONTAP Select-Nodes erstellen, die für die Verwendung von IPv6 auf den ONTAP LIFs konfiguriert sind.




== Erforderliche Konfigurationsinformationen

Im Rahmen Ihrer Bereitstellungsplanung sollten Sie vor der Installation des ONTAP Select Deploy Administration Utility die erforderlichen Konfigurationsinformationen ermitteln.

.Name der bereitzustellenden VM
Der für die VM zu verwendende Name.

.Name des Linux KVM-Hosts
Der Linux KVM-Host, auf dem das Deploy-Dienstprogramm installiert ist.

.Name des Speicherpools
Der Speicherpool, der die VM-Dateien enthält (ca. 40 GB erforderlich).

.Netzwerk für die VM
Das Netzwerk, mit dem die bereitzustellende VM verbunden ist.



== Optionale Informationen zu Netzwerkkonfiguration

Die Bereitstellungs-VM wird standardmäßig mithilfe von DHCP konfiguriert. Bei Bedarf können Sie jedoch die Netzwerkschnittstelle für die VM manuell konfigurieren.

.Host-Name
Der Name des Hosts.

.Host-IP-Adresse
Die statische IPv4-Adresse.

.Subnetzmaske
Die Subnetzmaske, die auf dem Netzwerk basiert, in dem die VM ein Teil ist.

.Gateway
Das Standard-Gateway oder -Router.

.Primärer DNS-Server
Der primäre DNS-Server.

.Sekundärer DNS-Server
Der sekundäre DNS-Server.

.Domänen durchsuchen
Die zu verwendenden Suchdomänen.



== Authentifizierung mithilfe des Anmeldeinformationsspeichers

Der ONTAP Select Deploy-Anmeldeinformationsspeicher ist eine Datenbank mit Kontoinformationen. Bei der Clustererstellung und -Verwaltung erfolgt die Hostauthentifizierung mithilfe der Kontoanmeldeinformationen. Sie sollten wissen, wie der Anmeldeinformationsspeicher bei der Planung einer ONTAP Select-Bereitstellung verwendet wird.


NOTE: Die Kontoinformationen werden mithilfe des AES-Verschlüsselungsalgorithmus und des SHA-256-Hashing-Algorithmus sicher in der Datenbank gespeichert.

.Arten von Anmeldeinformationen
Folgende Typen von Anmeldeinformationen werden unterstützt:

* Host wird zur Authentifizierung eines Hypervisor-Hosts bei der Bereitstellung eines ONTAP Select-Knotens direkt in VMware ESXi verwendet
* VCenter wird zur Authentifizierung eines vCenter-Servers im Rahmen der Bereitstellung eines ONTAP Select-Knotens bei ESXi verwendet, wenn der Host von VMware vCenter gemanagt wird


.Datenzugriff
Der Anmeldeinformationsspeicher wird intern aufgerufen, wenn er normale administrative Aufgaben mithilfe von Deploy ausführt, z. B. Hinzufügen eines Hypervisor-Hosts. Sie können den Anmeldeinformationsspeicher auch direkt über die Webbenutzeroberfläche bereitstellen und über die CLI verwalten.
