---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: In Bezug auf die VMware Umgebung müssen Sie verschiedene Hardware-Anforderungen und Planungsprobleme in Betracht ziehen. 
---
= Überlegungen zu Hypervisoren und Hardware von VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Bezug auf die VMware Umgebung müssen Sie verschiedene Hardware-Anforderungen und Planungsprobleme in Betracht ziehen.



== Hypervisor-Anforderungen

Der Hypervisor, auf dem ONTAP Select ausgeführt wird, muss unter verschiedenen Anforderungen verbunden sein.


NOTE: Sie sollten in den aktuellen Versionshinweisen zu Ihrer Version von ONTAP Select alle weiteren bekannten Einschränkungen oder Einschränkungen lesen.



=== VMware Lizenzierung

Um ein ONTAP Select Cluster zu implementieren, muss Ihr Unternehmen über eine gültige VMware vSphere Lizenz für die Hypervisor-Hosts verfügen, auf denen ONTAP Select ausgeführt wird. Sie sollten die für Ihre Implementierung geeigneten Lizenzen verwenden.



=== Softwarekompatibilität

ONTAP Select kann auf folgenden Hypervisoren implementiert werden:

* KVM auf Red hat Enterprise Linux 8.6, 8.7, 8.8, 9.0, 9.1, 9.2 und 9.4
* KVM unter Rocky Linux 8.6, 8.7, 8.8, 8.9, 9.0 9.1, 9.2, 9.3 und 9.4
* VMware ESXi 7.0 GA (Build 15843807 oder höher), einschließlich 7.0 U1, U2 und U3C
* VMware ESXi 8.0 GA (Build 20513097)
* VMware ESXi 8.0 U1 (Build 21495797)



NOTE: NetApp unterstützt ONTAP Select auf den ermittelten Versionen von ESXi, solange VMware weiterhin dieselben Versionen unterstützt.


NOTE: ESXi 6.5 GA und ESXi 6.7 GA haben das Ende des Verfügbarkeitsstatus erreicht. Wenn Sie ONTAP Select-Cluster mit diesen Versionen haben, müssen Sie auf die unterstützten Versionen gemäß aktualisieren https://mysupport.netapp.com/matrix["Interoperabilitäts-Matrix-Tool (IMT)"^].



=== VMware vCenter und Standalone-ESXi-Hosts

Wenn ein ESXi-Hypervisor-Host von einem vCenter-Server gemanagt wird, müssen Sie den Host mithilfe der vCenter-Anmeldedaten im Deploy-Administration-Utility registrieren. Sie können den Host nicht als eigenständigen Host mit den ESXi-Anmeldeinformationen registrieren.



== Wichtige Hardwareanforderungen

Der physische Hypervisor-Host, auf dem ONTAP Select implementiert wird, muss mehrere Hardwareanforderungen erfüllen. Für den Hypervisor-Host kann eine beliebige Plattform gewählt werden, sofern sie die Mindestanforderungen an die Hardware erfüllt. Folgende Anbieter stellen unterstützte Hardware-Plattformen bereit: Cisco, Dell, HP, Fujitsu, Lenovo, Und Supermicro:


NOTE: Ab ONTAP Select 9.9.1 werden nur CPU-Modelle unterstützt, die auf Intel Xeon Sandy Bridge oder höher basieren.

Siehe https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool, Fenster=_blank"] Finden Sie weitere Informationen.



=== Grundlegende Hardwareanforderungen

Es gibt verschiedene allgemeine Hardwareanforderungen, die für alle Plattformen gelten, unabhängig vom Instanztyp oder Lizenzangebot des Nodes.

.Prozessor
Zu den unterstützten Mikroprozessoren gehören:

* Intel Xeon Prozessoren für Server (siehe link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Intel Xeon Prozessoren,window=_blank"] Weitere Informationen)


.Ethernet-Konfiguration
Es werden verschiedene unterstützte Ethernet-Konfigurationen basierend auf der Cluster-Größe unterstützt.

[cols="30,35,35"]
|===


| Clustergröße | Mindestanforderungen | Empfohlene Anforderungen 


| Single-Node-Cluster | 2 x 1 GbE | 2 x 10 GbE 


| MetroCluster-SDS für Cluster mit zwei Nodes | 4 x 1 GbE oder 1 x 10 GbE | 2 x 10 GbE 


| Cluster mit 4/6/8 Nodes | 2 x 10 GbE | 4 x 10 GbE oder 2x 25 GbE 
|===


=== Weitere Hardwareanforderungen basierend auf dem Instanztyp

Auf der Grundlage des Node-Instanztyps bestehen weitere Hardwareanforderungen.

Siehe link:concept_lic_platforms.html["Verstehen Sie die Angebote für Plattformlizenzen"] Finden Sie weitere Informationen.

.Klein
* CPU-Cores sechs physische Kerne oder größer, mit vier reserviert für ONTAP Select.
* Arbeitsspeicher 24 GB oder mehr mit 16 GB reserviert für ONTAP Select.
* Erforderliche Plattformlizenz für Standard, Premium oder Premium XL


.Mittel
* CPU-Cores, mindestens zehn physische Cores, wobei acht für ONTAP Select reserviert sind
* Arbeitsspeicher 72 GB oder mehr mit 64 GB reserviert für ONTAP Select
* Erforderliche Plattformlizenz für Premium oder Premium XL


.Groß
* CPU-Kerne achtzehn physische Kerne oder größer, mit sechzehn reservierten für ONTAP Select.
* Arbeitsspeicher 136 GB oder mehr mit 128 GB reserviert für ONTAP Select
* Erforderliche Plattformlizenz für Premium XL



NOTE: Die Plattformlizenz stellt zusätzliche Festplattenanforderungen bereit. Siehe link:reference_plan_ots_storage.html["Storage und RAID"] Finden Sie weitere Informationen.
