---
sidebar: sidebar 
permalink: reference_faq.html 
keywords: faq, frequently asked questions 
summary: Finden Sie Antworten auf häufig gestellte Fragen zu ONTAP Select. 
---
= FAQ zu ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hier finden Sie Antworten auf häufig gestellte Fragen zu ONTAP Select.

[NOTE]
====
Ab ONTAP Select 9.14.1 wurde die Unterstützung für KVM-Hypervisor wieder aufgenommen. Zuvor wurde in ONTAP Select 9.10.1 die Unterstützung für die Implementierung eines neuen Clusters auf einem KVM-Hypervisor entfernt, und in ONTAP Select 9.11.1 wurde die Unterstützung für das Management vorhandener KVM-Cluster und -Hosts entfernt, mit Ausnahme des Offline- bzw. Löschens.

====


== Allgemein

Es gibt einige allgemeine Fragen und Antworten.

.Was ist der Unterschied zwischen ONTAP Select Deploy und ONTAP Select?
ONTAP Select Deploy ist das Tool zum Erstellen von ONTAP Select Clustern. Derzeit ist ONTAP Select Deploy die einzige Methode, die zur Erstellung eines Produktions-Clusters verfügbar ist. ONTAP Select Deploy kann auch verwendet werden, um ein Evaluation Select Cluster zu erstellen, damit Kunden die tatsächlichen Schritte einer Produktionsimplementierung testen und dokumentieren können. Mit ONTAP Select Deploy kann ein Evaluation-Cluster auch mithilfe einer geeigneten Capacity-Tier-Lizenz in ein Produktions-Cluster umgewandelt werden, die ausreichend Kapazität bietet, um den während der Evaluierung belegten Speicherplatz zu decken.

ONTAP Select Deploy ist eine Virtual Machine, die ein Image von ONTAP Select enthält. Während der Cluster-Installation erzwingt ONTAP Select Deploy mehrere Prüfungen, um sicherzustellen, dass die Mindestanforderungen von ONTAP Select erfüllt werden. Die ONTAP Select-Cluster für die Implementierung von VMs und Select können separat aktualisiert werden.

.Wie kann ich mit ONTAP Select ein Performance-Problem beheben?
Genau wie ONTAP auf FAS, sollten Performance-Daten mit dem perfstat Dienstprogramm erfasst werden. Hier ist ein Beispielbefehl:

[listing]
----
perfstat8 –i N,m -t <sample time in minutes> --verbose --nodes=<filer IP> --diag-passwd=abcxyz --mode="cluster-mode" > <name of output file>
----
.Wie kann ich auf die Seite Swagger API for ONTAP Select Deploy zugreifen?
[listing]
----
http://<Deploy-IP-Address/api/ui
----

NOTE: Die API v3-Version ist nicht abwärtskompatibel mit der vorherigen Version der API. Ein neues API-Verfahren ist auf der verfügbar https://library.netapp.com/ecm/ecm_download_file/ECMLP2845694["Field Portal"^].

.Kann die ONTAP Select VM mit Snapshots von VMware oder anderen Drittanbietern gesichert werden?
Nein Die ONTAP Select VM verwendet unabhängige persistente Laufwerke, die von VMware-basierten Snapshots ausgeschlossen sind. Die einzige unterstützte Methode zum Backup von ONTAP Select ist SnapMirror oder SnapVault.

.Wo erhalte ich Klärung bei Fragen, die nicht in dieser FAQ behandelt werden?
Kontakt link:mailto:ng-ses-ontap-select@netapp.com["ng-ses-ontap-select@netapp.com"].



== Lizenzen, Installation, Upgrades und Rückkehr

Es gibt mehrere Fragen und Antworten zu Lizenzen, Installation, Upgrades und Rücksetzen.

.Können ONTAP Select und ONTAP Select separat aktualisiert werden?
Ja. Das ONTAP Select Deploy Tool kann separat vom ONTAP Select Cluster aktualisiert werden. Auf ähnliche Weise kann der Select-Cluster separat vom ONTAP Select Deploy Utility aktualisiert werden.

.Können ONTAP Select mit der gleichen Vorgehensweise wie ein FAS Cluster aktualisiert werden?
Ja, das Upgrade-Verfahren für einen Select-Cluster ist identisch mit dem Upgrade eines FAS-Clusters, obwohl die ONTAP Select-Upgrade-Binärdatei einen separaten Download von der ONTAP auf FAS Upgrade-Binärdatei darstellt.

.Können ONTAP Select mit derselben Prozedur wie ein FAS Cluster zurückgesetzt werden?
Ja, das Verfahren zur Zurücksetzen für ein ONTAP Select Cluster ist fast identisch mit dem Verfahren zur Zurücksetzen für ein FAS Cluster. Es gibt jedoch einige Unterschiede:

* Nur aktualisierte Instanzen von ONTAP Select können zurückgesetzt werden. Dies ist nur bis zur ursprünglichen Installationsversion möglich. Neue Installationen können nicht auf eine ältere Code-Version zurückgesetzt werden, auch wenn ONTAP Select im Allgemeinen diese ältere Version unterstützt.
* Für ONTAP Select (KVM) und ONTAP Select (ESX) mit Software-RAID ist es nicht möglich, auf eine frühere Version zurückzukehren, die Software-RAID nicht unterstützt. Außerdem verwendet eine Neuinstallation von ONTAP Select 9.5 oder höher auf ESXi VMXNET3-Netzwerktreiber und, wenn möglich, den vNMVE-Treiber. Diese neuen Installationen können nicht auf frühere Versionen von ONTAP Select zurückgesetzt werden.
* Wenn die ONTAP Select VM auch auf eine große Instanz aktualisiert wurde (mithilfe der Premium XL-Lizenz), wird die Rückkehr zu einer früheren Version vor 9.6 nicht unterstützt, da die Funktion „Große Instanz“ in früheren Versionen nicht verfügbar ist.


.Erfordert ONTAP MetroCluster SDS mindestens eine Premium-Lizenz?
Ja.

.Kann die ONTAP Select Cluster-Netzwerkkonfiguration nach der Installation geändert werden?
Änderungen an den folgenden ONTAP Select -Clustereigenschaften werden von ONTAP Select Deploy mithilfe des Cluster-Aktualisierungsvorgangs erkannt, der über die UI, CLI oder REST-API verfügbar ist:

* Netzwerkkonfiguration (IP-Adressen, DNS, NTP, Netmask und Gateway)
* ONTAP Select Cluster, Node-Name und Version


Zusätzlich werden folgende ONTAP Select VM Änderungen erkannt:

* Name und Status der ONTAP Select-VM werden geändert (z. B. online oder offline).
* Änderungen an Host-Netzwerkname und Storage-Pool-Namen


Ein Upgrade auf ONTAP Select Deploy 2.6 ermöglicht die Unterstützung dieser Änderungen bei allen bereits bereitgestellten ONTAP Select Clustern, die in der ursprünglichen Konfiguration jedoch nicht geändert wurden. Mit anderen Worten: Wenn die oben erwähnten ONTAP Select-Cluster-Eigenschaften mit System Manager oder vCenter geändert wurden, kann das Upgrade auf ONTAP Select Deploy 2.6 diese Inkonsistenzen nicht beheben. Die Änderungen an den ONTAP Select-Eigenschaften müssen zuerst für die Implementierung von ONTAP Select zurückgesetzt werden, um ihre eindeutigen Metadaten zu jeder ONTAP Select VM hinzuzufügen.

.Kann die ONTAP Select Deploy Netzwerkkonfiguration nach der Installation geändert werden?
Das Ändern der Netzwerkdetails der Deploy-Instanz nach der Ausführung in einer Umgebung wird nicht unterstützt. Weitere Informationen finden Sie im Knowledge Base-Artikel link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/Modifying_DNS_configuration_of_ONTAP_Deploy_instance["Ändern der DNS-Konfiguration der ONTAP Deploy-Instanz"^] .

.Wie erkennt Deploy, dass ONTAP Select Lizenzen verlängert werden?
Die Methode ist für alle Lizenzen gleich, obwohl die Einzelheiten davon abhängen, ob es sich um eine Capacity Tier oder eine Capacity Pool Lizenz handelt.

* ONTAP Select Deploy erkennt, ob Lizenzen und Supportverträge durch den Kauf einer aktualisierten Lizenzdatei von NetApp verlängert werden. Die Lizenzdatei (.NLF) enthält das Kapazitäts-, Start- und Enddatum und wird auf dem generiert link:https://mysupport.netapp.com/site/["NetApp Support Website"^], Und dann auf dem Deployment-Server aktualisiert.
+

NOTE: Sie können die NLF über die Funktionen *Hinzufügen* und *Update* in den Deploy-Server laden. *Add* fügt dem Server neue Lizenzen hinzu und *Update* aktualisiert vorhandene Dateien mit Informationen wie Kapazität, Knotenlizenz (Standard, Premium, Premium XL), Start- und Enddaten des Supports (Capacity Tier Lizenz) oder Start- und Enddaten des Abonnements (Capacity Pool Lizenz).

+

CAUTION: Versuchen Sie nicht, die Lizenzdatei zu ändern. Dadurch wird der Sicherheitsschlüssel ungültig und die Lizenz ungültig.

* Eine *Capacity Tier Lizenz* ist eine permanente Lizenz pro Node, die an die Seriennummer des ONTAP Select-Knotens gebunden ist. Es wird mit einem separaten Support-Vertrag verkauft. Die Lizenz ist unbefristet, aber der Supportvertrag muss verlängert werden, um auf ONTAP Select Upgrades zugreifen zu können und Unterstützung durch den technischen Support von NetApp zu erhalten. Außerdem ist ein aktueller Supportvertrag erforderlich, um Lizenzparameter wie z. B. Kapazität oder Node-Größe zu ändern.
+
Beim Erwerb eines Lizenzaktualisierungen, einer Parameteränderung oder einer Verlängerung von Support-Verträgen ist die Seriennummer des Node im Rahmen der Bestellung erforderlich. Die Seriennummern der Knoten der Kapazitätsebene sind neun Ziffern lang und beginnen mit der Nummer „32“.

+
Sobald der Kauf abgeschlossen ist und die Lizenzdatei generiert wurde, wird sie mit der Funktion *Update* auf den Deploy-Server hochgeladen.

* Eine *Capacity Pool-Lizenz* ist ein Abonnement, mit dem ein bestimmter Kapazitäts- und Node-Pool (Standard, Premium, Premium XL) für die Implementierung eines oder mehrerer Cluster genutzt werden kann. Das Abonnement umfasst das Recht zur Nutzung einer Lizenz und Support für eine bestimmte Laufzeit. Das Recht zur Nutzung einer Lizenz und des Supportvertrags haben Start- und Endtermine festgelegt.


.Wie erkennt Deploy, ob die Nodes über eine Verlängerung der Lizenzen oder einen Supportvertrag verfügen?
Durch den Kauf, die Generierung und das Hochladen einer aktualisierten Lizenzdatei erkennt Deploy erneuerte Lizenzen und Supportverträge.

Wenn das Enddatum eines Capacity Tier-Supportvertrags verstrichen ist, kann der Node zwar weiter ausgeführt werden, Sie können jedoch keine ONTAP Updates herunterladen und installieren oder sich an den technischen Support von NetApp wenden, ohne den Supportvertrag vorher auf den neuesten Stand zu bringen.

Wenn ein Kapazitäts-Pool-Abonnement ausfällt, warnt das System Sie zuerst, aber nach 30 Tagen, wenn das System heruntergefahren wird, wird es erst neu gestartet, wenn ein aktualisiertes Abonnement auf dem Bereitstellungs-Server installiert wird.



== Storage

Es gibt mehrere Fragen und Antworten im Zusammenhang mit Storage.

.Kann eine einzelne ONTAP Select Deploy Instanz Cluster sowohl auf ESXi als auch auf KVM erstellen?
Ja. ONTAP Select Deployment kann entweder auf KVM oder ESX installiert werden. Beide Installationen können ONTAP Select Cluster auf einem Hypervisor erstellen.

.Ist vCenter für ONTAP Select auf ESX erforderlich?
Sind die ESXi-Hosts ordnungsgemäß lizenziert, dann ist es nicht erforderlich, dass die ESXi-Hosts von einem vCenter Server verwaltet werden. Werden die Hosts jedoch von einem vCenter Server verwaltet, dann müssen Sie ONTAP Select Deploy so konfigurieren, dass dieser vCenter Server verwendet wird. Anders ausgedrückt: Sie können ESXi-Hosts in ONTAP Select Deploy nicht als eigenständige Systeme konfigurieren, wenn sie aktiv von einem vCenter Server verwaltet werden. Beachten Sie, dass die ONTAP Select Deploy VM auf vCenter angewiesen ist, um alle ONTAP Select VM-Migrationen zwischen ESXi-Hosts aufgrund eines vMotion oder VMware HA-Ereignisses nachzuverfolgen.

.Was ist Software RAID?
ONTAP Select kann Server ohne Hardware-RAID-Controller verwenden. In diesem Fall wird die RAID-Funktion in der Software implementiert. Bei Software-RAID werden sowohl SSD- als auch NVMe-Laufwerke unterstützt. ONTAP Select-Boot- und Kernfestplatten müssen sich weiterhin innerhalb einer virtualisierten Partition (Storage-Pool oder Datenspeicher) befinden. ONTAP Select verwendet RD2 (Root-Daten-Partitionierung) für die Partitionierung der SSDs. Daher befindet sich die ONTAP Select Root-Partition auf denselben physischen Spindeln, die für die Datenaggregate verwendet werden. Das Root-Aggregat und die Boot- und Core-virtualisierten Festplatten werden jedoch nicht mit der Kapazitätslizenz gezählt.

Alle auf All Flash FAS/FAS verfügbaren RAID-Methoden sind auch für ONTAP Select verfügbar. U. a. RAID 4, RAID DP und RAID-TEC. Die Mindestanzahl von SSDs variiert je nach Typ der ausgewählten RAID-Konfiguration. Best Practices erfordern das Vorhandensein von mindestens einem Ersatzteil. Die Spare- und Parity-Festplatten werden nicht auf die Kapazitätslizenz angerechnet.

.Wodurch unterscheidet sich Software-RAID von einer Hardware-RAID-Konfiguration?
Software-RAID ist eine Schicht im ONTAP Software Stack. Software RAID bietet mehr Administrationskontrolle, da die physischen Laufwerke partitioniert und als Rohfestplatten innerhalb der ONTAP Select VM verfügbar sind. Während bei Hardware-RAID normalerweise eine einzelne große LUN zur Verfügung steht, die dann zur Erstellung von VMDISKs in ONTAP Select sichtbar ist. Software-RAID ist optional und kann anstelle von Hardware-RAID verwendet werden.

Für Software-RAID gelten folgende Anforderungen:

* Unterstützt für ESXi und KVM
+
** Ab ONTAP Select 9.14.1 wurde die Unterstützung für KVM-Hypervisor wieder aufgenommen. Zuvor wurde die Unterstützung für KVM-Hypervisor in ONTAP Select 9.10.1 entfernt.


* Größe der unterstützten physischen Festplatten: 200 GB bis 32 TB
* Unterstützung nur auf das-Konfigurationen
* Unterstützung durch SSDs oder NVMe
* Erfordert eine Premium- oder Premium XL-ONTAP Select-Lizenz
* Der Hardware-RAID-Controller sollte abwesend oder deaktiviert sein, oder er sollte im SAS-HBA-Modus betrieben werden
* Ein LVM-Speicherpool oder Datastore, der auf einer dedizierten LUN basiert, muss für Systemfestplatten verwendet werden: Core Dump, Boot/NVRAM und Mediator.


.Unterstützt ONTAP Select für KVM mehrere NIC-Bonds?
Bei der Installation auf KVM müssen Sie eine einzige Verbindung und eine einzelne Bridge verwenden. Ein Host mit zwei oder vier physischen Ports sollte alle Ports in derselben Verbindung haben.

.Wie meldet ONTAP Select eine fehlerhafte physische Festplatte oder einen NIC auf dem Hypervisor-Host? Ruft ONTAP Select diese Informationen vom Hypervisor ab, oder sollte die Überwachung auf Hypervisor-Ebene gesetzt werden?
Bei Verwendung eines Hardware-RAID-Controllers hat ONTAP Select keinerlei Einfluss auf die zugrunde liegenden Server-Probleme. Wenn der Server gemäß unseren Best Practices konfiguriert ist, sollte eine gewisse Menge an Redundanz vorhanden sein. Wir empfehlen RAID 5/6, um Laufwerksausfälle zu überleben. Bei Software-RAID-Konfigurationen sendet ONTAP Warnungen zu Festplattenausfällen und initiiert im Falle eines Ersatzlaufwerks die Neuerstellung des Laufwerks.

Sie sollten mindestens zwei physische NICs verwenden, um einen einzelnen Fehlerpunkt auf der Netzwerkebene zu vermeiden. NetApp empfiehlt, dass Daten-, Mgmt- und interne Port-Gruppen NIC-Teaming und Verbindung mit zwei oder mehr Uplinks im Team oder Bond konfiguriert sind. Diese Konfiguration stellt sicher, dass der virtuelle Switch bei einem Uplink-Fehler den Datenverkehr vom ausgefallenen Uplink auf einen gesunden Uplink im NIC-Team verschiebt. Weitere Informationen zur empfohlenen Netzwerkkonfiguration finden Sie unter link:reference_plan_best_practices.html#networking["Zusammenfassung der Best Practices: Networking"].

Alle anderen Fehler werden bei einem Zwei- oder Vier-Knoten-Cluster von ONTAP HA behandelt. Wenn der Hypervisor-Server ersetzt und der ONTAP Select Cluster mit einem neuen Server neu zusammengestellt werden muss, lesen Sie _Kann ich einen ONTAP Select Knoten wiederherstellen?_.

.Kann ich einen ONTAP Select Knoten wiederherstellen?
Wenden Sie sich an den technischen Support von NetApp , wenn Sie einen ONTAP Select Knoten wiederherstellen müssen, beispielsweise wenn eine ONTAP Select VM oder ein ONTAP Select-Host vollständig verloren geht oder ein Einzelknotencluster versehentlich gelöscht wird. Weitere Informationen finden Sie im Knowledge Base-Artikel link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-KBs/ONTAP_Select_node_VM_recovery_in_case_of_disaster["ONTAP Select Node VM-Wiederherstellung im Katastrophenfall"^] .

.Welche maximale Datastore-Größe unterstützt ONTAP Select?
Alle Konfigurationen, einschließlich vSAN, unterstützen 400 TB Storage pro ONTAP Select Node.

Wenn Sie eine Installation auf Datastores durchführen, die größer als die unterstützte Maximalgröße sind, müssen Sie während des Produkt-Setups Capacity Cap verwenden.

.Wie kann ich die Kapazität eines ONTAP Select-Knotens erhöhen?
ONTAP Select Deploy enthält einen Workflow zum Hinzufügen von Storage, der die Kapazitätserweiterung auf einem ONTAP Select Node unterstützt. Sie können den zu managenden Storage erweitern, indem Sie den Speicherplatz aus demselben Datastore nutzen (sofern noch kein Platz verfügbar ist) oder Speicherplatz von einem separaten Datastore hinzufügen. Die Kombination von lokalen Datastores und Remote-Datastores im selben Aggregat wird nicht unterstützt.

Storage Add unterstützt auch Software RAID. Bei Software-RAID müssen jedoch zusätzliche physische Laufwerke der ONTAP Select-VM hinzugefügt werden. Der Storage-Add ähnelt in diesem Fall dem Management eines FAS- oder AFF-Arrays. RAID-Gruppengrößen und Laufwerkgrößen müssen beim Hinzufügen von Storage zu einem ONTAP Select Node mithilfe von Software-RAID berücksichtigt werden.

.Unterstützt ONTAP Select vSAN oder externe Array-Datastores?
ONTAP Select Deploy und ONTAP Select for ESXi unterstützen die Konfiguration eines ONTAP Select Einzelknotenclusters unter Verwendung entweder eines vSAN- oder eines externen Array-Typs von Datenspeicher für seinen Speicherpool.

ONTAP Select Deploy and ONTAP Select for KVM unterstützt die Konfiguration eines ONTAP Select Single-Node-Clusters mithilfe eines logischen Shared Storage Pool-Typs in externen Arrays. Die Storage Pools können auf iSCSI oder FC/FCoE basieren. Andere Arten von Speicherpools werden nicht unterstützt.

Multi-Node-HA-Cluster auf gemeinsam genutztem Speicher werden unterstützt.

.Unterstützt ONTAP Select Multi-Node-Cluster auf vSAN oder anderen gemeinsam genutzten externen Speichern, einschließlich einiger HCI-Stacks?
Multi-Node-Cluster mit externem Speicher (Multi-Node-vNAS) werden sowohl für ESXi als auch für KVM unterstützt. Die Mischung von Hypervisoren im selben Cluster wird nicht unterstützt. Eine HA-Architektur mit gemeinsam genutztem Speicher setzt weiterhin voraus, dass jeder Node in einem HA-Paar eine Spiegelkopie der Partnerdaten besitzt. Ein Multi-Node-Cluster bietet jedoch die Vorteile der unterbrechungsfreien ONTAP-Betriebsabläufe im Gegensatz zu einem Single-Node-Cluster, der auf VMware HA oder KVM Live Motion angewiesen ist.

Obwohl ONTAP Select Deploy die Unterstützung mehrerer ONTAP Select VMs auf demselben Host hinzufügt, erlaubt es nicht, dass diese Instanzen während der Clustererstellung Teil desselben ONTAP Select Clusters sind. Für ESXi-Umgebungen empfiehlt NetApp, VM-Anti-Affinitätsregeln zu erstellen, damit VMware HA nicht versucht, mehrere ONTAP Select VMs aus demselben ONTAP Select Cluster auf einen einzelnen ESXi-Host zu migrieren. Wenn ONTAP Select Deploy außerdem feststellt, dass eine administrative (benutzerinitiierte) vMotion oder Live-Migration einer ONTAP Select VM zu einem Verstoß gegen unsere Best Practices geführt hat, wie zum Beispiel dass zwei ONTAP Select Nodes auf demselben physischen Host enden, gibt ONTAP Select Deploy eine Warnung in der Deploy-Benutzeroberfläche und im Protokoll aus. Die einzige Möglichkeit, wie ONTAP Select Deploy vom Standort der ONTAP Select VM erfährt, ist das Ergebnis einer Clusteraktualisierung, die ein manueller Vorgang ist, den der ONTAP Select Deploy-Administrator initiieren muss. Es gibt keine Funktionalität in ONTAP Select Deploy, die proaktives Monitoring ermöglicht, und die Warnung ist nur über die Deploy-Benutzeroberfläche oder das Protokoll sichtbar. Mit anderen Worten: Diese Warnung kann nicht an eine zentrale Überwachungsinfrastruktur weitergeleitet werden.

.Unterstützt ONTAP Select NSX VXLAN von VMware?
NSX-V VXLAN-Portgruppen werden unterstützt. Für Multi-Node-HA, einschließlich ONTAP MetroCluster SDS, stellen Sie sicher, dass Sie die interne Netzwerk-MTU auf einen Wert zwischen 7500 und 8900 (statt 9000) konfigurieren, um den VXLAN-Overhead zu berücksichtigen. Die interne Netzwerk-MTU kann mit ONTAP Select Deploy während der Clusterbereitstellung konfiguriert werden.

.Unterstützt ONTAP Select KVM-Live-Migration?
ONTAP Select VMs, die auf externen Array-Storage-Pools ausgeführt werden, unterstützen virsh Live-Migrationen.

.Benötige ich ONTAP Select Premium für vSAN AF?
Nein, alle Versionen werden unterstützt, unabhängig davon, ob es sich um rein Flash-basierte externe Arrays- oder vSAN Konfigurationen handelt.

.Welche vSAN FTT/FTM-Einstellungen werden unterstützt?
Die Select VM übernimmt die vSAN Datastore-Storage-Richtlinie und es gibt keine Einschränkungen bei FTT/FTM-Einstellungen. Beachten Sie jedoch, dass abhängig von den FTT/FTM-Einstellungen die ONTAP Select-VM-Größe erheblich größer sein kann als die während des Setups konfigurierte Kapazität. ONTAP Select nutzt Thick-Eager und Zeroed VMDKs, die während der Einrichtung erstellt werden. Um zu vermeiden, dass andere VMs denselben gemeinsam genutzten Datenspeicher verwenden, ist es wichtig, genügend freie Kapazität im Datastore bereitzustellen, damit die echte Select VM-Größe gemäß den Select-Kapazitäten und FTT/FTM-Einstellungen berücksichtigt werden kann.

.Können mehrere ONTAP Select-Nodes auf demselben Host ausgeführt werden, wenn sie Teil verschiedener Select-Cluster sind?
Diverse ONTAP Select Nodes können auf demselben Host nur für vNAS Konfigurationen konfiguriert werden, sofern diese Nodes nicht Teil desselben ONTAP Select Clusters sind. Dies wird für das-Konfigurationen nicht unterstützt, da mehrere ONTAP Select-Nodes auf demselben physischen Host mit dem Zugriff auf den RAID-Controller konkurrieren können.

.Kann ein Host mit einem einzelnen 10GE-Port ONTAP Select ausführen, und ist es sowohl für ESXi als auch für KVM verfügbar?
Sie können einen einzelnen 10GE-Port für die Verbindung zum externen Netzwerk verwenden. Allerdings empfiehlt NetApp, dies nur in beengten Umgebungen mit kleinem Formfaktor zu nutzen. Dies wird sowohl mit ESXi als auch mit KVM unterstützt.

.Welche zusätzlichen Prozesse müssen Sie ausführen, um eine Live-Migration auf KVM durchzuführen?
Auf jedem Host, der an der Live-Migration teilnimmt, müssen Sie Open-Source-Komponenten CLVM und Pacemaker (PCs) installieren und ausführen. Dieser Vorgang muss auf dieselben Volume-Gruppen auf jedem Host zugreifen können.



== VCenter

Es gibt mehrere Fragen und Antworten, die sich mit VMware vCenter befassen.

.Wie kommuniziert ONTAP Select Deploy mit vCenter und welche Firewall-Ports sollten geöffnet werden?
ONTAP Select Deploy verwendet die VMware VIX API, um mit dem vCenter, dem ESXi-Host oder beiden zu kommunizieren. Die VMware-Dokumentation gibt an, dass die erste Verbindung zu einem vCenter Server oder einem ESXi-Host über HTTPS/SOAP auf TCP-Port 443 erfolgt. Dies ist der Port für sicheres HTTP über TLS/SSL. Zweitens wird eine Verbindung zum ESXi-Host über einen Socket auf TCP-Port 902 geöffnet. Daten, die über diese Verbindung übertragen werden, sind mit SSL verschlüsselt. Zusätzlich führt ONTAP Select Deploy einen  `PING` Befehl aus, um zu überprüfen, ob unter der von Ihnen angegebenen IP-Adresse ein ESXi-Host antwortet.

ONTAP Select Deploy muss auch in der Lage sein, mit den ONTAP Select Knoten- und Cluster-Management-IP-Adressen zu kommunizieren:

* Ping
* SSH (Port 22)
* SSL (Port 443)


ONTAP Select hostet die Cluster-Mailboxen für Cluster mit zwei Nodes. Jeder ONTAP Select-Node muss in der Lage sein, ONTAP Select-Bereitstellung über iSCSI zu erreichen (Port 3260).

Bei Multi-Node-Clustern muss das interne Netzwerk vollständig geöffnet sein (kein NAT oder Firewalls).

.Welche vCenter-Rechte müssen durch ONTAP Select bereitgestellt werden, um ONTAP Select Cluster zu erstellen?
Die Liste der erforderlichen vCenter-Rechte finden Sie hier: link:reference_plan_ots_vcenter.html["VMware vCenter Server"].



== HA und Cluster

Es gibt mehrere Fragen und Antworten, die sich mit HA-Paaren und Clustern befassen.

.Worin besteht der Unterschied zwischen einem ONTAP Select Cluster mit vier, sechs oder acht Nodes und einem Cluster mit zwei Nodes?
Im Gegensatz zu Clustern mit vier Nodes, sechs Nodes und acht Nodes, in denen die ONTAP Select VM in erster Linie zum Erstellen des Clusters implementiert wird, ist ein Cluster mit zwei Nodes für das HA-Quorum kontinuierlich auf der ONTAP Select Deploy VM angewiesen. Wenn die ONTAP Select Deploy-VM nicht verfügbar ist, werden die Failover-Services deaktiviert.

.Was ist MetroCluster SDS?
Bei MetroCluster SDS handelt es sich um eine kostengünstige Option zur synchronen Replizierung, die in der Kategorie der MetroCluster Business Continuity-Lösungen von NetApp fällt. Es ist nur mit ONTAP Select verfügbar, im Gegensatz zu NetApp MetroCluster , das auf FAS Hybrid Flash, AFF und NetApp Private Storage for Cloud verfügbar ist.

.Inwiefern unterscheidet sich MetroCluster-SDS von NetApp MetroCluster?
MetroCluster SDS bietet eine synchrone Replizierungslösung und ist unter NetApp MetroCluster Lösungen erhältlich. Die wichtigsten Unterschiede liegen jedoch in den unterstützten Distanzen (~10 km gegenüber 300 km) und der Konnektivität (nur IP-Netzwerke werden unterstützt statt FC und IP).

.Worin besteht der Unterschied zwischen einem ONTAP Select Cluster mit zwei Nodes und einem ONTAP MetroCluster SDS mit zwei Nodes?
Das Cluster mit zwei Nodes wird als Cluster definiert, bei dem sich beide Nodes im selben Datacenter befinden, maximal 300 Millionen voneinander. Im Allgemeinen verfügen beide Knoten über Uplinks mit demselben Netzwerk-Switch oder eine Reihe von Netzwerk-Switches, die über einen Inter-Switch-Link verbunden sind.

Der MetroCluster SDS mit zwei Knoten wird als Cluster definiert, dessen Knoten physisch getrennt sind (verschiedene Räume, unterschiedliche Gebäude oder unterschiedliche Rechenzentren) und die Uplink-Verbindungen jedes Knotens sind mit separaten Netzwerk-Switches verbunden. Obwohl MetroCluster SDS keine dedizierte Hardware erfordert, sollte die Umgebung eine Reihe von Mindestanforderungen hinsichtlich Latenz (5 ms RTT und 5 ms Jitter für max. 10 ms) und physischer Entfernung (10 km) unterstützen.

MetroCluster SDS ist eine Premiumfunktion und erfordert eine Premium- oder Premium-XL-Lizenz. Eine Premium-Lizenz unterstützt die Erstellung kleiner und mittlerer VMs sowie von HDD- und SSD-Medien. Alle diese Konfigurationen werden unterstützt.

.Erfordert ONTAP MetroCluster SDS lokalen Storage (das)?
ONTAP MetroCluster SDS unterstützt alle Arten von Storage-Konfigurationen (das und vNAS).

.Unterstützt ONTAP MetroCluster SDS Software-RAID?
Ja, Software-RAID wird mit SSD-Medien sowohl auf KVM als auch auf ESX unterstützt.

.Unterstützt ONTAP MetroCluster SDS sowohl SSDs als auch rotierende Medien?
Ja, obwohl eine Premium-Lizenz erforderlich ist, unterstützt diese Lizenz sowohl kleine als auch mittlere VMs sowie SSDs und rotierende Medien.

.Unterstützt ONTAP MetroCluster SDS Cluster mit vier und größeren Nodes?
Nein, nur Cluster mit zwei Nodes und einem Mediator können als MetroCluster SDS konfiguriert werden.

.Welche Anforderungen gelten für ONTAP MetroCluster-SDS?
Die Anforderungen lauten wie folgt:

* Drei Datacenter (eines für den ONTAP Select Deploy Mediator und eines für jeden Node)
* 5 ms RTT und 5 ms Jitter für max. 10 ms Gesamtlänge und max. 10 km Entfernung zwischen den ONTAP Select-Knoten.
* 125 ms RTT und eine minimale Bandbreite von 5 MB/s zwischen dem ONTAP Select Deploy Mediator und jedem ONTAP Select Node.
* Eine Premium- oder Premium XL-Lizenz.


.Unterstützt ONTAP Select vMotion oder VMware HA?
ONTAP Select VMs, die auf vSAN Datastores oder externen Array-Datastores (mit anderen Worten, vNAS Implementierungen) laufen, unterstützen vMotion, DRS und VMware HA-Funktionen.

.Unterstützt ONTAP Select Storage vMotion?
Storage vMotion wird für alle Konfigurationen unterstützt, einschließlich Single-Node- und Multi-Node-ONTAP Select Clustern sowie der ONTAP Select Deploy VM. Storage vMotion kann verwendet werden, um die ONTAP Select oder die ONTAP Select Deploy VM zwischen verschiedenen VMFS-Versionen (zum Beispiel von VMFS 5 zu VMFS 6) zu migrieren, ist aber nicht auf diesen Anwendungsfall beschränkt. Die Best Practice ist, die VM vor dem Start einer Storage vMotion-Operation herunterzufahren. ONTAP Select Deploy muss nach Abschluss der Storage vMotion-Operation die folgende Operation ausführen:

[listing]
----
cluster refresh
----

NOTE: Ein Speicher-vMotion-Vorgang zwischen verschiedenen Typen von Datenspeichern wird nicht unterstützt. Anders ausgedrückt: Speicher-vMotion-Vorgänge zwischen NFS-Typ-Datenspeichern und VMFS-Datenspeichern werden nicht unterstützt. Im Allgemeinen werden Speicher-vMotion-Vorgänge zwischen externen Datenspeichern und DAS-Datenspeichern nicht unterstützt.

.Kann der HA-Datenverkehr zwischen ONTAP Select Knoten über einen anderen vSwitch und/oder getrennte physische Ports und/oder mittels Punkt-zu-Punkt-IP-Kabeln zwischen ESXi-Hosts abgewickelt werden?
Diese Konfigurationen werden nicht unterstützt. Der ONTAP Select hat keine Übersicht über den Status der physischen Netzwerk-Uplinks, die den Client-Datenverkehr übertragen. Daher verlässt sich ONTAP Select auf den HA-Herzschlag, um sicherzustellen, dass die VM gleichzeitig für Clients und ihren Peer verfügbar ist. Wenn eine physische Konnektivität verloren geht, führt der Ausfall des HA-Heartbeat zu einem automatischen Failover auf den anderen Node. Dies ist das gewünschte Verhalten.

Eine Trennung des HA Traffic auf einer separaten physischen Infrastruktur kann dazu führen, dass eine Select VM in der Lage ist, mit seinem Peer zu kommunizieren, aber nicht mit seinen Kunden. So wird der automatische HA-Prozess verhindert und die Datenverfügbarkeit erreicht, bis ein manueller Failover aufgerufen wird.



== Mediatordienst

Es gibt mehrere Fragen und Antworten, die sich mit dem Mediatordienst befassen.

.Was ist der Mediator Service?
Ein Cluster mit zwei Nodes basiert kontinuierlich auf der ONTAP Select VM zur Bereitstellung als HA-Quorum. Eine ONTAP Select Deploy-VM, die an einer HA-Quorum-Verhandlung mit zwei Nodes beteiligt ist, wird als Mediator-VM bezeichnet.

.Kann der Mediator-Service fernbedienbar sein?
Ja. ONTAP Select-Implementierung als Mediator für ein HA-Paar mit zwei Nodes unterstützt eine WAN-Latenz von bis zu 500 ms RTT und erfordert eine minimale Bandbreite von 5 MB/s.

.Welches Protokoll verwendet der Mediator-Dienst?
Der Mediator-Datenverkehr ist iSCSI, stammt aus den ONTAP Select-Node-Management-IP-Adressen und wird auf der ONTAP Select Deploy-IP-Adresse beendet. Beachten Sie, dass Sie IPv6 nicht für die ONTAP Select-Node-Management-IP-Adresse verwenden können, wenn Sie ein Cluster mit zwei Nodes verwenden.

.Kann ich einen Mediator-Service für mehrere HA-Cluster mit zwei Nodes nutzen?
Ja. Jede ONTAP Select-VM kann als gängiger Mediator-Service für bis zu 100 ONTAP Select-Cluster mit zwei Nodes verwendet werden.

.Kann der Mediator-Servicenstandort nach der Bereitstellung geändert werden?
Ja. Es ist möglich, einen anderen ONTAP Select Deploy VM zu verwenden, um den Mediator-Service zu hosten.

.Unterstützt ONTAP Select Stretched Cluster mit (oder ohne) dem Mediator?
In einem Stretch-HA-Implementierungsmodell wird nur ein Cluster mit zwei Nodes und einem Mediator unterstützt.
