---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: In Bezug auf die VMware Umgebung müssen Sie verschiedene Hardware-Anforderungen und Planungsprobleme in Betracht ziehen. 
---
= Überlegungen zu ONTAP Select VMware Hypervisor und Hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Bezug auf die VMware Umgebung müssen Sie verschiedene Hardware-Anforderungen und Planungsprobleme in Betracht ziehen.



== Hypervisor-Anforderungen

Der Hypervisor, auf dem ONTAP Select ausgeführt wird, muss unter verschiedenen Anforderungen verbunden sein.


NOTE: Sie sollten dielink:reference_release_notes.html["Versionshinweise zu ONTAP Select"] für alle weiteren bekannten Einschränkungen oder Beschränkungen.



=== VMware Lizenzierung

Um ein ONTAP Select Cluster zu implementieren, muss Ihr Unternehmen über eine gültige VMware vSphere Lizenz für die Hypervisor-Hosts verfügen, auf denen ONTAP Select ausgeführt wird. Sie sollten die für Ihre Implementierung geeigneten Lizenzen verwenden.



=== Softwarekompatibilität

Sie können ONTAP Select auf KVM- und ESXi-Hypervisoren bereitstellen.

[role="tabbed-block"]
====
.KVM
--
ONTAP Select unterstützt die folgenden KVM-Hypervisor-Versionen:

* KVM auf Red Hat Enterprise Linux (RHEL) 10.0, 9.6, 9.5, 9.4, 9.2, 9.1, 9.0, 8.8, 8.7 und 8.6
* KVM auf Rocky Linux 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 und 8.6


[NOTE]
====
Für KVM-Hypervisoren auf RHEL 10.0- und Rocky Linux 10.0-Hosts gibt es Einschränkungen im Software-RAID-Workflow. Weitere Informationen finden Sie in den folgenden Artikeln unserer Wissensdatenbank:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: Warnmeldung beim Erstellen der Cluster-Hardware unter Verwendung von RHEL 10 und ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: Speicherpools und Speicherdatenträger werden für SWR auf der Seite zur Clustererstellung auf Hosts mit RHEL10/Rocky 10 nicht angezeigt."^]


====
--
.ESXi
--
ONTAP Select unterstützt die folgenden ESXi-Hypervisor-Versionen:

* VMware ESXi 9.0
* VMware ESXi 8.0 U3
* VMware ESXi 8.0 U2
* VMware ESXi 8.0 U1 (Build 21495797)
* VMware ESXi 8.0 GA (Build 20513097)



NOTE: NetApp unterstützt ONTAP Select auf den ermittelten Versionen von ESXi, solange VMware weiterhin dieselben Versionen unterstützt.


NOTE: ESXi 7.0 GA hat das Ende des Verfügbarkeitsstatus erreicht.  Wenn Sie ONTAP Select Cluster mit dieser Version verwenden, müssen Sie gemäß der Anleitung auf die unterstützten Versionen aktualisieren. https://mysupport.netapp.com/matrix["Interoperabilitäts-Matrix-Tool (IMT)"^] Die

--
====


=== VMware vCenter und Standalone-ESXi-Hosts

Wenn ein ESXi-Hypervisor-Host von einem vCenter-Server gemanagt wird, müssen Sie den Host mithilfe der vCenter-Anmeldedaten im Deploy-Administration-Utility registrieren. Sie können den Host nicht als eigenständigen Host mit den ESXi-Anmeldeinformationen registrieren.



== Wichtige Hardwareanforderungen

Der physische Hypervisor-Host, auf dem ONTAP Select implementiert wird, muss mehrere Hardwareanforderungen erfüllen. Für den Hypervisor-Host kann eine beliebige Plattform gewählt werden, sofern sie die Mindestanforderungen an die Hardware erfüllt. Folgende Anbieter stellen unterstützte Hardware-Plattformen bereit: Cisco, Dell, HP, Fujitsu, Lenovo, Und Supermicro:


NOTE: Ab ONTAP Select 9.9.1 werden nur noch CPU-Modelle unterstützt, die auf Intel Xeon Sandy Bridge oder neueren Modellen basieren.

Weitere Informationen finden Sie im https://mysupport.netapp.com/matrix["Interoperabilitäts-Matrix-Tool,window=_blank"].



=== Grundlegende Hardwareanforderungen

Es gibt verschiedene allgemeine Hardwareanforderungen, die für alle Plattformen gelten, unabhängig vom Instanztyp oder Lizenzangebot des Nodes.

.Prozessor
Zu den unterstützten Mikroprozessoren gehören Intel Xeon Prozessoren für Server, siehe link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Intel Xeon Prozessoren,window=_blank"] für weitere Informationen.


NOTE: Advanced Micro Devices (AMD)-Prozessoren werden von ONTAP Select nicht unterstützt.

.Ethernet-Konfiguration
Es werden verschiedene unterstützte Ethernet-Konfigurationen basierend auf der Cluster-Größe unterstützt.

[cols="2,3,3"]
|===
| Clustergröße | Mindestanforderungen | Empfohlene Anforderungen 


| Single-Node-Cluster | 2 x 1 GbE | 2 x 10 GbE 


| MetroCluster-SDS für Cluster mit zwei Nodes | 4 x 1 GbE oder 1 x 10 GbE | 2 x 10 GbE 


| Cluster mit vier, sechs, acht, zehn oder zwölf Knoten | 2 x 10 GbE | 4 x 10 GbE oder 2x 25 GbE 
|===


=== Weitere Hardwareanforderungen basierend auf dem Instanztyp

Auf der Grundlage des Node-Instanztyps bestehen weitere Hardwareanforderungen.

Siehe link:concept_lic_platforms.html["Verstehen Sie die Angebote für Plattformlizenzen"] Finden Sie weitere Informationen.

[cols="a1,a2,a2,a2"]
|===
| Knotengröße | CPU-Kerne | Erinnerung | Erforderliches Plattformlizenzangebot 


| Klein | Sechs physische Kerne oder mehr, davon vier reserviert für ONTAP Select | 24 GB oder mehr, davon 16 GB reserviert für ONTAP Select | Standard, Premium oder Premium XL 


| Mittel | Zehn physische Kerne oder mehr, davon acht reserviert für ONTAP Select | 72 GB oder mehr, davon 64 GB reserviert für ONTAP Select | Premium oder Premium XL 


| Groß | Achtzehn physische Kerne oder mehr, davon sechzehn reserviert für ONTAP Select | 136 GB oder mehr, davon 128 GB reserviert für ONTAP Select | Premium XL 
|===

NOTE: Die Plattformlizenz stellt zusätzliche Festplattenanforderungen bereit. Siehe link:reference_plan_ots_storage.html["Storage und RAID"] Finden Sie weitere Informationen.
