---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select bietet vollständige Unterstützung für die meisten ONTAP Funktionen. Viele ONTAP Funktionen werden bei Implementierung eines Clusters automatisch für jeden Node lizenziert. Einige Funktionen erfordern jedoch eine separate Lizenz. 
---
= ONTAP Select-Unterstützung für ONTAP-Funktionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select unterstützt die meisten ONTAP Funktionen. Viele der ONTAP -Funktionen werden bei der Bereitstellung eines Clusters automatisch für jeden Knoten lizenziert. Für einige Funktionen ist jedoch eine separate Lizenz erforderlich.


NOTE: ONTAP Funktionen mit hardwarespezifischen Abhängigkeiten werden in der Regel nicht von ONTAP Select unterstützt.



== ONTAP Funktionen sind standardmäßig lizenziert

Die folgenden ONTAP Funktionen werden von ONTAP Select unterstützt und standardmäßig lizenziert:

* Autonomous Ransomware Protection (ARP) (manuelle Updates)
* CIFS
* Deduplizierung und Komprimierung
* Externes Schlüsselmanagement mittels des Key Management Interoperability Protocol (KMIP)
+
Die externe Schlüsselverwaltung ist die einzige von ONTAP Select unterstützte Schlüsselverwaltung. Erfahren Sie mehr über link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["Aktivierung und Konfiguration der externen Schlüsselverwaltung"^].

* FlexCache
+
ONTAP Select unterstützt FlexCache Cache-Volumes mit Write-Back. FlexCache Origin-Volumes mit Write-Back werden nicht unterstützt.

+
link:concept_ots_overview.html#flexcache-write-back-with-ontap-select["Erfahren Sie mehr über FlexCache Write-Back mit ONTAP Select"]

* FlexClone
* ISCSI
* NDMP
* NetApp Volume Encryption (nur in Ländern ohne Beschränkungen)
* NFS
* NVMe über TCP –
* ONTAP Mandantenfähigkeit
* ONTAP S3
* S3 SnapMirror
* SnapLock Select
+
SnapLock Select ist die Implementierung von ONTAP SnapLock, die für ONTAP Select entwickelt wurde und SnapLock Enterprise umfasst. Es umfasst nicht SnapLock Compliance.

+
link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["Erfahren Sie mehr über ONTAP SnapLock"^]

* SnapMirror
* SnapMirror Cloud
* SnapRestore
* SnapVault
* Disaster Recovery für Storage VM (SVM DR)
+
ONTAP Select unterstützt SVM DR sowohl als Quelle als auch als Ziel mit maximal 16 Beziehungen. Die SVM DR-Unterstützung ist auf die Verwendung der Quell-ONTAP-Version bis zu Version +2 beschränkt. Zum Beispiel kann die ONTAP Select 9.16.1-Quelle eine Verbindung zu den Ziel-ONTAP-Versionen 9.16.1, 9.17.1 oder 9.18.1 herstellen.





== ONTAP-Funktionen, die separat lizenziert werden

Sie benötigen eine separate Lizenz für alle ONTAP-Funktionen, die nicht standardmäßig lizenziert sind, einschließlich:

* FabricPool
+

NOTE: Sie brauchen keine FabricPool Lizenz, wenn Sie StorageGRID nutzen.

* MetroCluster SDS (ONTAP Select Premium-Lizenzangebot)


.Verwandte Informationen
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Vergleichen Sie ONTAP Select und ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Erfahren Sie mehr über die NetApp ONTAP Masterlizenzschlüssel"^]

