---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: Die Implementierung eines Clusters mit zwei Nodes und HA umfasst dieselbe Planung und Konfiguration, die auch bei anderen Cluster Node-Konfigurationen verwendet wird. Es gibt jedoch einige Unterschiede, die Sie beim Erstellen eines Clusters mit zwei Nodes beachten sollten. 
---
= ONTAP Select Cluster mit zwei Nodes und HA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Implementierung eines Clusters mit zwei Nodes und HA umfasst dieselbe Planung und Konfiguration, die auch bei anderen Cluster Node-Konfigurationen verwendet wird. Es gibt jedoch einige Unterschiede, die Sie beim Erstellen eines Clusters mit zwei Nodes beachten sollten.

.Zielumgebung
Das Cluster mit zwei Nodes besteht aus einem HA-Paar und wurde speziell für Implementierungen in Remote-Zweigstellen entwickelt.


NOTE: Obwohl das System hauptsächlich für Remote-Umgebungen und Zweigstellen konzipiert wurde, können Sie bei Bedarf auch ein Cluster mit zwei Nodes im Datacenter implementieren.

.Lizenzierung
Sie können ein 2-Node-Cluster mithilfe einer beliebigen VMware vSphere Lizenz implementieren. Die Lizenzen für VMware ROBO Standard und Advanced sind aber ideal für Implementierungen in Remote Offices und in Zweigstellen.

.Mediatordienst
Wenn ein Cluster aus zwei Nodes besteht, ist es nicht möglich, das erforderliche Quorum zu erreichen, wenn ein Knoten ausfällt oder die Kommunikation verliert. Um diese Arten von Split-Brain-Situationen zu beheben, umfasst jede Instanz des Dienstprogramms ONTAP Select Deploy einen Mediator. Dieser Service stellt eine Verbindung zu jedem Node in den aktiven 2-Node-Clustern her, um die HA-Paare zu überwachen und Fehler beim Management zu unterstützen. Beim Mediator-Service werden die HA-Zustandsdaten zu einem dedizierten iSCSI-Ziel, das zu jedem Cluster mit zwei Nodes verbunden ist, erhalten.


CAUTION: Wenn Sie über ein oder mehrere aktive Cluster mit zwei Nodes verfügen, muss die ONTAP Select Deploy Virtual Machine, die die Cluster verwaltet, jederzeit ausgeführt werden. Wenn die virtuelle Maschine zum Bereitstellen angehalten wird oder ausfällt, ist der Mediator-Service nicht verfügbar und die HA-Funktion geht bei den Clustern mit zwei Nodes verloren.

.Standort des Clusters und des Mediators
Da die Cluster mit zwei Nodes normalerweise in einer Remote- oder Zweigstelle bereitgestellt werden, können sie sich vom Datacenter des Unternehmens aus fernab befinden und das Deploy Utility bietet administrativen Support. Bei dieser Konfiguration fließt der Managementdatenverkehr zwischen dem Dienstprogramm Deploy und dem Cluster über das WAN. In den Versionshinweisen finden Sie weitere Informationen zu Einschränkungen und Einschränkungen.

.Sichern Sie die Konfigurationsdaten der Bereitstellung
Es empfiehlt sich, ein Backup der Bereitstellungskonfigurationsdaten regelmäßig zu erstellen, auch nach dem Erstellen eines Clusters. Dies ist aufgrund der Mediator-Konfigurationsdaten, die im Backup enthalten sind, bei Clustern mit zwei Nodes besonders wichtig.

.Der Bereitstellung zugewiesene statische IP-Adresse
Sie müssen dem Dienstprogramm Administration Deploy eine statische IP-Adresse zuweisen. Diese Anforderung gilt für alle Deploy-Instanzen, die ein oder mehrere ONTAP Select Cluster mit zwei Nodes managen.
