---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select bietet vollständige Unterstützung für die meisten ONTAP Funktionen. Viele ONTAP Funktionen werden bei Implementierung eines Clusters automatisch für jeden Node lizenziert. Einige Funktionen erfordern jedoch eine separate Lizenz. 
---
= Funktionen der ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select bietet vollständige Unterstützung für die meisten ONTAP Funktionen. Viele ONTAP Funktionen werden bei Implementierung eines Clusters automatisch für jeden Node lizenziert. Einige Funktionen erfordern jedoch eine separate Lizenz.


NOTE: ONTAP Funktionen mit hardwarespezifischen Abhängigkeiten werden in der Regel nicht von ONTAP Select unterstützt.



== ONTAP Funktionen werden standardmäßig automatisch aktiviert

Die folgenden Features sind bei ONTAP Select enthalten und standardmäßig lizenziert:

* CIFS
* Deduplizierung und Komprimierung
* FlexCache
* FlexClone
* ISCSI
* NDMP
* NetApp Volume Encryption (nur in Ländern ohne Beschränkungen)
* NFS
* NVMe über TCP –
* ONTAP Mandantenfähigkeit
* ONTAP S3
* SnapMirror
* SnapRestore
* SnapVault




== ONTAP-Funktionen, die separat lizenziert werden

Sie müssen eine separate Lizenz für jede ONTAP-Funktion erwerben, die standardmäßig nicht aktiviert ist. Dazu gehören:

* Datenverfügbarkeitsservice
* FabricPool
* FlexCache (kostenlos)
* MetroCluster SDS (ONTAP Select Premium-Lizenzangebot)
* SnapLock Enterprise (SnapLock-Compliance wird für ONTAP Select nicht unterstützt)
* SyncMirror (kostenlos)



NOTE: Bei der Nutzung von StorageGRID Webscale benötigen Sie keine FabricPool Lizenz.

.Verwandte Informationen
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["Vergleich von ONTAP Select und ONTAP 9"]

