---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: Die Implementierung eines Clusters mit zwei Nodes und HA umfasst dieselbe Planung und Konfiguration, die auch bei anderen Cluster Node-Konfigurationen verwendet wird. Es gibt jedoch einige Unterschiede, die Sie beim Erstellen eines Clusters mit zwei Nodes beachten sollten. 
---
= ONTAP Select Cluster mit zwei Nodes und HA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Implementierung eines Clusters mit zwei Nodes und HA umfasst dieselbe Planung und Konfiguration, die auch bei anderen Cluster Node-Konfigurationen verwendet wird. Es gibt jedoch einige Unterschiede, die Sie beim Erstellen eines Clusters mit zwei Nodes beachten sollten.

.Zielumgebung
Das Cluster mit zwei Nodes besteht aus einem HA-Paar und wurde speziell für Implementierungen in Remote-Zweigstellen entwickelt.


NOTE: Obwohl das System hauptsächlich für Remote-Umgebungen und Zweigstellen konzipiert wurde, können Sie bei Bedarf auch ein Cluster mit zwei Nodes im Datacenter implementieren.

.Lizenzierung
Sie können ein 2-Node-Cluster mithilfe einer beliebigen VMware vSphere Lizenz implementieren. Die Lizenzen für VMware ROBO Standard und Advanced sind aber ideal für Implementierungen in Remote Offices und in Zweigstellen.

.Mediatordienst
Wenn ein Cluster aus zwei Nodes besteht, ist es nicht möglich, das erforderliche Quorum zu erreichen, wenn ein Knoten ausfällt oder die Kommunikation verliert. Um diese Arten von Split-Brain-Situationen zu beheben, umfasst jede Instanz des Dienstprogramms ONTAP Select Deploy einen Mediator. Dieser Service stellt eine Verbindung zu jedem Node in den aktiven 2-Node-Clustern her, um die HA-Paare zu überwachen und Fehler beim Management zu unterstützen. Beim Mediator-Service werden die HA-Zustandsdaten zu einem dedizierten iSCSI-Ziel, das zu jedem Cluster mit zwei Nodes verbunden ist, erhalten.


CAUTION: Wenn Sie über einen oder mehrere aktive Zwei-Knoten-Cluster verfügen, muss die virtuelle ONTAP Select Deploy-Maschine, die die Cluster verwaltet, ständig ausgeführt werden. Wenn die virtuelle Maschine ONTAP Select Deploy angehalten wird oder ausfällt, ist der Mediatordienst nicht verfügbar und die HA-Funktionalität für die Zwei-Knoten-Cluster geht verloren.

.Standort des Clusters und des Mediators
Da die Zwei-Knoten-Cluster typischerweise in einer Außenstelle oder Zweigstelle eingesetzt werden, können sie vom Rechenzentrum des Unternehmens und dem ONTAP Select Deploy-Dienstprogramm, das administrative Unterstützung bietet, getrennt sein.  Bei dieser Konfiguration fließt der Management-Datenverkehr zwischen dem ONTAP Select Deploy-Dienstprogramm und dem Cluster über das WAN. Weitere Informationen zu Einschränkungen und Beschränkungen finden Sie in den Versionshinweisen.

.Sichern Sie die Deploy-Konfigurationsdaten
Es ist eine bewährte Vorgehensweise,link:task_cli_clusters.html["Sichern Sie die ONTAP Select Deploy-Konfigurationsdaten"] regelmäßig, auch nach der Erstellung eines Clusters. Dies ist insbesondere bei Clustern mit zwei Knoten wichtig, da die Mediator-Konfigurationsdaten in der Sicherung enthalten sind.

.Der Bereitstellung zugewiesene statische IP-Adresse
Sie müssen dem Verwaltungsprogramm ONTAP Select Deploy eine statische IP-Adresse zuweisen.  Diese Anforderung gilt für alle ONTAP Select Deploy-Instanzen, die einen oder mehrere ONTAP Select Zwei-Knoten-Cluster verwalten.
