---
sidebar: sidebar 
permalink: sizing-capacity-pool-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: Die Capacity-Tiers-Lizenz basiert auf der von jedem Knoten verwalteten Festplattenkapazität und nicht auf der nutzbaren Kapazität des Knotens, HA-Paars oder Clusters. Jede Capacity-Tiers-Lizenz ist einer einzelnen Knotenseriennummer für eine bestimmte Kapazität zugeordnet und erfordert einen zugehörigen Supportvertrag. 
---
= Überlegungen zur Dimensionierung einer ONTAP Select Capacity Pools License
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die lizenzierte Kapazität für eine Capacity Pool-Lizenz beträgt volle TB, mit einem Minimum von 2 TB. Sie berechnen die lizenzierte Kapazität, indem Sie die Menge des nutzbaren Speicherplatzes mit dem Overhead-Faktor multiplizieren. Der Overhead-Faktor unterscheidet sich zwischen Einzelknoten- und Mehrknoten- (HA-Paar-basierten) Clustern:

* Der Overhead-Faktor für Einzelknoten-Cluster beträgt 1.13
* Der Overhead-Faktor für Multi-Node-Cluster beträgt 2.67


Sie müssen die lizenzierte Kapazität auf Basis der nutzbaren Kapazität berechnen, um sicherzustellen, dass Sie für Ihre Implementierung in der Produktion ausreichend Kapazität haben.

[cols="25,30,45"]
|===
| Beschreibung | Einzelknoten | HA pair oder Mischung aus HA pair und Einzelknoten 


| nutzbare Kapazität | 20 TB | 10 TB pro Einzelknoten-Cluster 20 TB für HA-Paar 


| Lizenzierter Speicherplatz | 23 TB (20 x 1,13 = 22,6, aufgerundet auf das nächste volle TB) | 54 TB (20 x 2,67 = 53,4, auf das nächste volle TB aufrunden) 


| Maximal nutzbarer Speicherplatz pro Knoten *Hinweis*: Der maximal verwaltete Speicherplatz pro Knoten oder HA-Paar beträgt 400 TB | 353 TB (400 / 1,13)  a| 
Pro Einzelknoten in einem Cluster:

149 TB (400 / 2,67)

Pro HA-Paar in einem Cluster:

298 TB (2 x 149)

|===
.Was kommt als Nächstes
link:task_lic_acquire_cp.html["Erwerben Sie eine Capacity Pools-Lizenz für ONTAP Select"]
