---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: Wenn das Dienstprogramm ONTAP Select Deploy aus irgendeinem Grund ausfällt oder aus irgendeinem Grund nicht mehr verfügbar ist, können Sie ONTAP Select-Nodes und -Cluster nicht mehr verwalten. Zudem verlieren alle 2-Node-Cluster die HA-Funktion, da der bei der Bereitstellung enthaltene Mediator-Service nicht verfügbar ist. Wenn ein nicht behebbarer Fehler auftritt, müssen Sie die Deploy Utility-Instanz wiederherstellen, um administrative und HA-Funktionen wiederherzustellen. 
---
= Stellen Sie das Dienstprogramm ONTAP Select Deploy für ein Cluster mit zwei Nodes wieder her
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn das Dienstprogramm ONTAP Select Deploy aus irgendeinem Grund ausfällt oder aus irgendeinem Grund nicht mehr verfügbar ist, können Sie ONTAP Select-Nodes und -Cluster nicht mehr verwalten. Zudem verlieren alle 2-Node-Cluster die HA-Funktion, da der bei der Bereitstellung enthaltene Mediator-Service nicht verfügbar ist. Wenn ein nicht behebbarer Fehler auftritt, müssen Sie die Deploy Utility-Instanz wiederherstellen, um administrative und HA-Funktionen wiederherzustellen.



== Bereiten Sie die Wiederherstellung des Deploy-Dienstprogramms vor.

Um den Erfolg beim Wiederherstellen einer Instanz des Deploy-Dienstprogramms zu gewährleisten, müssen Sie entsprechende Vorbereitungen treffen.  Sie müssen mit verschiedenen administrativen Abläufen vertraut sein und über die erforderlichen Informationen verfügen.

.Schritte
. Überprüfen Sie, ob Sie eine neue Instanz des ONTAP Select Deploy-Dienstprogramms in Ihrer Hypervisor-Umgebung installieren können.
+
link:task_install_deploy.html["Erfahren Sie mehr über die Installation des ONTAP Select Deploy-Dienstprogramms."]

. Überprüfen Sie, ob Sie sich beim ONTAP Select -Cluster anmelden und auf die ONTAP -Cluster-Shell (CLI) zugreifen können.
. Prüfen Sie, ob Sie eine Sicherungskopie der Konfigurationsdaten der fehlgeschlagenen Deploy-Utility-Instanz besitzen, die den ONTAP Select Zwei-Knoten-Cluster enthält. Möglicherweise verfügen Sie über eine Sicherungskopie, die den Cluster nicht enthält.
. Prüfen Sie, ob Sie eine Sicherung der Deploy-Konfigurationsdaten wiederherstellen können, abhängig vom verwendeten Wiederherstellungsverfahren.
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["Erfahren Sie, wie Sie die Deploy-Konfigurationsdaten auf der neuen virtuellen Maschine wiederherstellen."]

. Sie haben die IP-Adresse der ursprünglichen virtuellen Maschine des Bereitstellungsdienstes, die fehlgeschlagen ist.
. Ermitteln Sie, ob eine Lizenzierung über Kapazitätspools oder Kapazitätsstufen verwendet wird. Wenn Sie die Lizenzierung von Kapazitätspools verwenden, müssen Sie nach der Wiederherstellung der Deploy-Instanz jede Kapazitätspool-Lizenz neu installieren.
. Entscheiden Sie, welches Verfahren Sie bei der Wiederherstellung einer Instanz des ONTAP Select Deploy-Dienstprogramms anwenden möchten. Ihre Entscheidung hängt davon ab, ob Sie über eine Sicherungskopie der Konfigurationsdaten des ursprünglichen fehlgeschlagenen Deploy-Dienstprogramms verfügen, das den ONTAP Select Zwei-Knoten-Cluster enthält.
+
[cols="35,65"]
|===
| Verfügen Sie über ein Bereitstellungs-Backup mit dem zwei-Node-Cluster? | Führen Sie das Wiederherstellungsverfahren durch... 


| Ja. | <<restore-deploy-backup,Stellen Sie eine Instanz eines Dienstprogramms mithilfe eines Konfigurationsbackups wieder her>> 


| Nein | <<restore-and-recover-deploy,Neukonfigurieren und Wiederherstellen einer Dienstprogramminstanz>> 
|===




== Stellen Sie eine Instanz eines Dienstprogramms mithilfe eines Konfigurationsbackups wieder her

Wenn Sie über ein Backup der fehlgeschlagenen Deploy Utility-Instanz verfügen, die das Cluster mit zwei Nodes enthält, können Sie die Konfigurationsdaten auf der neuen virtuellen Maschineninstanz implementieren wiederherstellen. Anschließend müssen Sie die Recovery durch eine zusätzliche Konfiguration der beiden Nodes im ONTAP Select Cluster abschließen.

.Bevor Sie beginnen
Sichern Sie die Konfigurationsdaten der ursprünglich fehlgeschlagenen virtuellen Maschine „Deploy“, die den Zwei-Knoten-Cluster enthält. Sie müssen sich bei der ONTAP CLI des Zwei-Knoten-Clusters anmelden können und die ONTAP Namen der beiden Knoten kennen.

.Über diese Aufgabe
Da das von Ihnen wiederhergestellte Konfigurations-Backup das Cluster mit zwei Nodes enthält, werden die iSCSI-Ziele und Mailboxen des Mediators auf der neuen Virtual Machine des Deploy Utility neu erstellt.

.Schritte
. Bereiten Sie eine neue Instanz des ONTAP Select Deploy-Dienstprogramms vor:
+
.. Installieren Sie eine neue Virtual Machine für das Deploy Utility.
.. Stellen Sie die Bereitstellungskonfiguration von einem früheren Backup auf der neuen virtuellen Maschine wieder her.
+
Weitere Informationen zu den Installations- und Wiederherstellungsverfahren finden Sie in den zugehörigen Aufgaben.



. Melden Sie sich bei der ONTAP Befehlszeilenschnittstelle des ONTAP Select Clusters mit zwei Nodes an.
. Wechseln Sie in den erweiterten Berechtigungsmodus:
+
[source, cli]
----
set adv
----
. Wenn die IP-Adresse der neuen virtuellen Maschine für die Bereitstellung von der IP-Adresse der ursprünglichen virtuellen Maschine für die Bereitstellung abweicht, entfernen Sie die alten Mediator-iSCSI-Ziele und fügen Sie neue Ziele hinzu:
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
Der `<ip_address>` Parameter ist die IP-Adresse der neuen virtuellen Maschine bereitstellen.

+
Mit diesen Befehlen können die ONTAP Select-Knoten die Mailbox-Platten auf der neuen Deploy Utility Virtual Machine erkennen.

. Ermitteln Sie die Namen der Mediator-Festplatten:
+
[source, cli]
----
disk show -container-type mediator
----
. Weisen Sie die Mailbox-Platten den beiden Knoten zu:
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. Vergewissern Sie sich, dass Storage-Failover aktiviert ist:
+
[source, cli]
----
storage failover show
----


.Nachdem Sie fertig sind
Wenn Sie Capacity Pools-Lizenzen verwenden, müssen Sie jede Capacity Pool-Lizenz neu installieren.  Sehenlink:task_adm_licenses.html#reinstall-a-capacity-pool-license["Installieren Sie eine Capacity Pool-Lizenz neu"] Weitere Einzelheiten finden Sie hier.



== Neukonfigurieren und Wiederherstellen einer Dienstprogramminstanz

Falls Sie keine Sicherungskopie der fehlgeschlagenen Deploy-Utility-Instanz besitzen, die den Zwei-Knoten-Cluster enthält, konfigurieren Sie das Mediator-iSCSI-Ziel und die Mailbox in der neuen virtuellen Deploy-Maschine.  Anschließend schließen Sie die Wiederherstellung ab, indem Sie zusätzliche Konfigurationen der beiden Knoten im ONTAP Select -Cluster vornehmen.

.Bevor Sie beginnen
Überprüfen Sie, ob Sie den Namen des Mediator-Ziels für die neue Deploy-Utility-Instanz haben. Sie müssen sich bei der ONTAP CLI des Zwei-Knoten-Clusters anmelden können und die ONTAP Namen der beiden Knoten kennen.

.Über diese Aufgabe
Sie können optional ein Konfigurationbackup auf der neuen Deploy Virtual Machine wiederherstellen, obwohl es das Cluster mit zwei Nodes nicht enthält. Da das Cluster mit zwei Nodes nicht mit dem Restore wiederhergestellt wird, müssen Sie das iSCSI-Ziel und die Mailbox des Mediators manuell zur neuen Utility-Instanz mithilfe der ONTAP Select Online-Dokumentation bei der Bereitstellung hinzufügen. Sie müssen sich beim Cluster mit zwei Nodes anmelden und die ONTAP-Namen der beiden Nodes kennen.


NOTE: Ziel des Recovery-Verfahrens ist es, den Cluster mit zwei Nodes in einem ordnungsgemäßen Zustand wiederherzustellen, in dem normale HA Takeover- und Giveback-Vorgänge durchgeführt werden können.

.Schritte
. Bereiten Sie eine neue Instanz des ONTAP Select Deploy-Dienstprogramms vor:
+
.. Installieren Sie eine neue Virtual Machine für das Deploy Utility.
.. Stellen Sie optional die Bereitstellungskonfiguration aus einer früheren Sicherung auf der neuen virtuellen Maschine wieder her.
+
Wenn Sie ein vorheriges Backup wiederherstellen, enthält die neue Deploy-Instanz nicht das Cluster mit zwei Nodes. Weitere Informationen zu den Installations- und Wiederherstellungsverfahren finden Sie im Abschnitt „Verwandte Informationen“.



. Melden Sie sich bei der ONTAP Befehlszeilenschnittstelle des ONTAP Select Clusters mit zwei Nodes an.
. Erweiterten privilegierten Modus aufrufen:
+
[source, cli]
----
set adv
----
. Holen Sie sich den iSCSI-Zielnamen des Mediators:
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. Greifen Sie auf die Webseite für die Online-Dokumentation auf der virtuellen Maschine des neuen Dienstprogramms bereitstellen zu, und melden Sie sich über das Administratorkonto an:
+
`\http://<ip_address>/api/ui`

+
Sie müssen die IP-Adresse Ihrer virtuellen Maschine bereitstellen verwenden.

. Wählen Sie *Mediator* und anschließend *GET /mediators*.
. Wählen Sie *Ausprobieren!*, um eine Liste der von Deploy verwalteten Mediatoren anzuzeigen.
+
Notieren Sie die ID der gewünschten Mediatorinstanz.

. Wählen Sie *Mediator* und anschließend *POST*.
. Geben Sie den Wert für Mediator_ID an
. Wählen Sie das *Modell* neben `iscsi_target` und vervollständigen Sie den Namenswert.
+
Verwenden Sie den Zielnamen für den Parameter iqn_Name.

. Wählen Sie *Ausprobieren!*, um das Mediator-iSCSI-Ziel zu erstellen.
+
Wenn die Anfrage erfolgreich ist, erhalten Sie den HTTP-Statuscode 200.

. Wenn sich die IP-Adresse der neuen Virtual Machine „Bereitstellen“ von der ursprünglichen Virtual Machine „Bereitstellen“ unterscheidet, müssen Sie die ONTAP CLI verwenden, um die alten iSCSI-Ziele des Mediators zu entfernen und neue Ziele hinzuzufügen:
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
Der `<ip_address>` Parameter ist die IP-Adresse der neuen virtuellen Maschine bereitstellen.

+
Mit diesen Befehlen können die ONTAP Select-Knoten die Mailbox-Platten auf der neuen Deploy Utility Virtual Machine erkennen.

. Ermitteln Sie die Namen der Mediator-Festplatten:
+
[source, cli]
----
disk show -container-type mediator
----
. Weisen Sie die Mailbox-Platten den beiden Knoten zu:
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. Vergewissern Sie sich, dass Storage-Failover aktiviert ist:
+
[source, cli]
----
storage failover show
----


.Nachdem Sie fertig sind
Wenn Sie Capacity Pools-Lizenzen verwenden, müssen Sie jede Capacity Pool-Lizenz neu installieren.  Sehenlink:task_adm_licenses.html#reinstall-a-capacity-pool-license["Installieren Sie eine Capacity Pool-Lizenz neu"] Weitere Einzelheiten finden Sie hier.
