---
sidebar: sidebar 
permalink: task_adm_connectivity.html 
keywords: administer, administering, web, connectivity, network connectivity, network checker 
summary: Sie können die Netzwerkkonnektivität zwischen zwei oder mehr ONTAP Select Nodes im internen Cluster-Netzwerk testen. Sie führen diesen Test in der Regel vor der Implementierung eines Cluster mit mehreren Nodes aus, um Probleme zu erkennen, die den Vorgang möglicherweise zum Ausfall führen. 
---
= Bestätigung der Konnektivität zwischen den ONTAP Select-Nodes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Netzwerkkonnektivität zwischen zwei oder mehr ONTAP Select Nodes im internen Cluster-Netzwerk testen. Sie führen diesen Test in der Regel vor der Implementierung eines Cluster mit mehreren Nodes aus, um Probleme zu erkennen, die den Vorgang möglicherweise zum Ausfall führen.

Alle ONTAP Select-Nodes im Test müssen konfiguriert und eingeschaltet sein.

Jedes Mal, wenn Sie einen Test starten, wird eine neue Prozessdurchlauf im Hintergrund erstellt und einer eindeutigen Laufkennung zugewiesen. Es kann jeweils nur ein Durchlauf aktiv sein.

Der Test verfügt über zwei Modi, die den Betrieb steuern:

* Quick This Mode führt einen grundlegenden unterbrechungsfreien Test durch. ES wird ein PING-Test durchgeführt, zusammen mit einem Test der MTU-Größe des Netzwerks und des vSwitch.
* Erweitert dieser Modus führt einen umfassenderen Test über alle redundanten Netzwerkpfade durch. Wenn Sie dies auf einem aktiven ONTAP Select Cluster ausführen, kann die Performance des Clusters beeinträchtigt werden.



NOTE: Es wird empfohlen, vor dem Erstellen eines Clusters mit mehreren Nodes immer einen schnellen Test durchzuführen. Nachdem der Schnelltest erfolgreich abgeschlossen wurde, können Sie optional einen erweiterten Test basierend auf Ihren Produktionsanforderungen durchführen.

.Schritte
. Melden Sie sich über das Administratorkonto bei der Webbenutzeroberfläche des Deploy Utility an.
. Klicken Sie oben auf der Seite auf die Registerkarte *Administration* und klicken Sie auf *Network Checker*.
. Klicken Sie auf *Neuer Lauf starten* und wählen Sie die Hosts und Netzwerke für das HA-Paar aus
+
Sie können bei Bedarf weitere HA-Paare hinzufügen und konfigurieren.

. Klicken Sie auf *Start*, um den Netzwerkverbindungstest zu starten.

