---
sidebar: sidebar 
permalink: task_vpi_access.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, access, accessing 
summary: Sie können über den vSphere Web-Client auf das Deploy vCenter Plug-in zugreifen. 
---
= Greifen Sie über vSphere auf das vCenter Plug-in zu
:allow-uri-read: 


[role="lead"]
Sie können über den vSphere Web-Client auf das Deploy vCenter Plug-in zugreifen.

.Bevor Sie beginnen
Das vCenter-Plug-in muss installiert sein. Darüber hinaus muss das vCenter-Konto, das Sie bei der Anmeldung bei vSphere verwenden, über die folgende Berechtigung verfügen:

* NetApp
+
** ONTAP Select Deploy
+
*** Verwalter






.Schritte
. Melden Sie sich vom vSphere Web-Client ab, wenn Sie angemeldet sind.
. Melden Sie sich mit dem vSphere Web Client bei vCenter an, wählen Sie HTML5 aus und akzeptieren Sie das SSL-Zertifikat.
+
Durch das Auszeichnen und anschließend wieder zurück in werden die vCenter Konfigurationsdaten aktualisiert.

. Klicken Sie Auf *Global Inventory Lists*.


.Ergebnis
Die Optionen *ONTAP Select Cluster* und *ONTAP Select Deploy* sind im Fenster auf der linken Seite verfügbar. Wenn sie nicht angezeigt werden, sollten Sie sich abzeichnen und sich dann wieder anmelden.
