---
sidebar: sidebar 
permalink: task_vpi_deploy_cluster.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, deploy cluster, deploying cluster, create cluster, creating cluster 
summary: Verwenden Sie das Deploy vCenter Plug-in über die vSphere Web User Interface, um ONTAP Select Cluster zu implementieren. 
---
= Implementieren eines ONTAP Select-Clusters
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie das Deploy vCenter Plug-in über die vSphere Web User Interface, um ONTAP Select Cluster zu implementieren.



== Bevor Sie beginnen

Sie sollten die Verwendung des Deploy vCenter Plug-ins vorbereiten, bevor Sie ein ONTAP Select Cluster bereitstellen.



=== Gemeinsame Vorbereitung für Cluster jeder Größe

Es gibt verschiedene Schritte, die unabhängig von der Cluster-Größe ausgeführt werden müssen:

* Lesen Sie den Abschnitt _erste Schritte_, um sich mit dem vCenter Plug-in zur Bereitstellung vertraut zu machen.
* Stellen Sie sicher, dass das ONTAP Select Deploy Administration Utility installiert ist und ausgeführt wird.
* Installieren Sie das vCenter Plug-in Deploy.
* Bereiten Sie den Hypervisor-Host oder die Hosts vor, auf denen das ONTAP Select-Cluster ausgeführt wird.
* Erwerben Sie die erforderlichen Storage-Lizenzdateien für den Node oder die Nodes im Cluster.
* Erwerben Sie die Zugangsdaten für die folgenden Konten:
+
** Administratorkonto bereitstellen
** VCenter-Konto mit Zugriff auf das Plug-in


* Installieren Sie bei Bedarf das SSL-Zertifikat bereitstellen auf dem Windows Certificate Manager als „Trusted Root Certificate Authority“.
* Stellen Sie sicher, dass das Deploy-Dienstprogramm Netzwerkzugriff auf Port 443 am vCenter-Server hat.




=== Vorbereitung für einen Multi-Node-Cluster

Neben der allgemeinen Vorbereitung sollten Sie sich vor der Bereitstellung eines Multi-Node-Clusters mit dem Deploy Network Checker vertraut machen.



== Hinzufügen eines Hypervisor-Hosts

Sie können Hypervisoren-Hosts zum Deploy-Dienstprogramm hinzufügen, auf dem die ONTAP Select-Nodes ausgeführt werden, bevor Sie ein Cluster implementieren. Falls erforderlich können Sie stattdessen die Hosts im Dialogfeld zur Cluster-Erstellung hinzufügen.

.Bevor Sie beginnen
Sie sollten die Vorbereitung der Implementierung eines ONTAP Select Clusters prüfen.

.Über diese Aufgabe
Sie können je nach Größe des Clusters einen oder mehrere Hosts hinzufügen.

.Schritte
. Melden Sie sich über vSphere HTML5 mit einem Browser beim vCenter-Server an.
. Klicken Sie in der Symbolleiste auf *Menü* und dann auf *Globale Bestandslisten*.
. Klicken Sie im linken Fensterbereich auf *ONTAP Select Bereitstellen* und dann auf die Registerkarte *Hosts*.
. Klicken Sie rechts auf *Hinzufügen*.
. Geben Sie den Hostnamen oder die IP-Adresse des Hosts an und klicken Sie dann auf *Hinzufügen* oder *Hinzufügen und Beenden*.




== Erstellen eines Single-Node-Clusters

Sie können das VMware vCenter Plug-in über den vSphere Web-Client verwenden, um ein ONTAP Select-Cluster bestehend aus einem einzelnen Node zu implementieren.

.Bevor Sie beginnen
Sie sollten die Vorbereitung der Implementierung eines ONTAP Select Clusters und das Hinzufügen eines Hypervisor-Hosts prüfen. Sie können den Host hinzufügen, auf dem der ONTAP Select-Node ausgeführt wird, bevor Sie das Cluster erstellen oder zum Erstellen des Single-Node-Clusters.

.Schritte
. Melden Sie sich über vSphere HTML5 mit einem Browser beim vCenter-Server an.
. Klicken Sie oben auf *Menü* und dann auf *Global Inventory Lists*.
. Klicken Sie im linken Fensterbereich auf *ONTAP Select Cluster* und dann auf *New ONTAP Select*.
+
Wenn Sie das SSL-Zertifikat noch nicht akzeptiert haben, klicken Sie in der Warnmeldung auf den IP-Link und akzeptieren Sie das Zertifikat. Kehren Sie dann zur vCenter-Seite zurück und klicken Sie in der Warnmeldung auf den Link, um die Seite neu zu laden.

. Geben Sie auf der Seite *New ONTAP Select* die Cluster-Details ein und klicken Sie auf *Fertig*.
. Geben Sie im Abschnitt *Knoten-Setup* die Konfiguration ein und wählen Sie eine Lizenz aus.
+
Sie können den Standard-Node-Namen ändern und bei Bedarf eine neue Lizenz hochladen.

. Wählen Sie im Abschnitt *Hypervisor und Netzwerk* den Instanztyp, den Host und die Netzwerke aus.
+
Sie können bei Bedarf einen Host hinzufügen. Die Lizenz für den Node muss den Instanztyp erfüllen oder überschreiten.

. Wählen Sie im Abschnitt *Storage* die Speicherkapazität und einen Speicherpool aus.
+
Optional können Sie Software-RAID aktivieren, wenn Sie eine Premium-Lizenz verwenden.

. Klicken Sie auf *Fertig* und prüfen Sie die Konfiguration des Clusters.
+
Sie können die Konfiguration ändern, indem Sie in jedem Abschnitt auf Bearbeiten klicken.

. Klicken Sie Auf *Weiter*.
. Geben Sie das ONTAP Administrator-Passwort ein und klicken Sie auf *Cluster erstellen*, um den Cluster-Erstellungsprozess zu starten, und klicken Sie dann im Bestätigungsfenster auf *OK*.
+
Es kann bis zu 30 Minuten dauern, bis der Cluster erstellt wurde.

. Aktualisieren Sie die Seite, und wählen Sie den neuen Cluster aus. Klicken Sie dann auf *Zusammenfassung* und *Details*, um den mehrstufigen Cluster-Erstellungsprozess zu überwachen.
+

TIP: Wenn der Vorgang zum Erstellen des Clusters initiiert, aber nicht abgeschlossen wird, ist das von Ihnen definierte ONTAP-Administratorpasswort nicht registriert. In diesem Fall können Sie mit dem Passwort auf die Managementoberfläche für das ONTAP Select-Cluster zugreifen `changeme123` Mit dem `admin` Konto.



.Nachdem Sie fertig sind
* Vergewissern Sie sich, dass die ONTAP Select AutoSupport-Funktion aktiviert ist.
* Sichern Sie die Konfigurationsdaten für ONTAP Select Deploy.




== Erstellen eines Multi-Node-Clusters

Das VMware vCenter Plug-in kann über den vSphere Web-Client verwendet werden, um ein ONTAP Select-Cluster aus mehreren Nodes zu implementieren.

.Bevor Sie beginnen
Sie sollten die Vorbereitung der Implementierung eines ONTAP Select Clusters und das Hinzufügen eines Hypervisor-Hosts prüfen. Sie können die Hosts hinzufügen, auf denen die ONTAP Select-Nodes ausgeführt werden, bevor Sie das Cluster erstellen, oder sie erstellen das Multi-Node-Cluster.

.Über diese Aufgabe
Ein ONTAP Select Multi-Node-Cluster besteht aus einer geraden Anzahl an Nodes. Die Nodes werden immer als HA-Paare verbunden.

.Schritte
. Melden Sie sich über vSphere HTML5 mit einem Browser beim vCenter-Server an.
. Klicken Sie oben auf *Menü* und dann auf *Global Inventory Lists*.
. Klicken Sie im linken Fensterbereich auf *ONTAP Select Cluster* und dann auf *New ONTAP Select*
+
Wenn Sie das SSL-Zertifikat noch nicht akzeptiert haben, klicken Sie in der Warnmeldung auf den IP-Link und akzeptieren Sie das Zertifikat. Kehren Sie dann zur vCenter-Seite zurück und klicken Sie in der Warnmeldung auf den Link, um die Seite neu zu laden.

. Geben Sie auf der Seite *New ONTAP Select* die Cluster-Details ein und klicken Sie auf *Fertig*.
+
Wenn Sie keinen Grund zur Festlegung der MTU-Größe des Clusters haben, sollten Sie den Standardwert akzeptieren und die Bereitstellung ggf. Anpassungen vornehmen lassen.

. Geben Sie im Abschnitt *Node Setup* die Konfiguration an und wählen Sie Lizenzen für die beiden Nodes im HA-Paar aus.
+
Sie können bei Bedarf die Standard-Node-Namen ändern und neue Lizenzen hochladen.

. Wählen Sie im Abschnitt *Hypervisor und Netzwerk* den Instanztyp, den Host und die Netzwerke für jeden Knoten aus.
+
Sie können bei Bedarf einen Host hinzufügen. Sie müssen die drei Netzwerke auswählen. Das interne Netzwerk kann nicht mit dem Management- oder Datennetzwerk übereinstimmen. Die Lizenzen für die Nodes müssen den Instanztyp erfüllen oder überschreiten.

. Wählen Sie im Abschnitt *Storage* die Speicherkapazität und einen Speicherpool aus.
+
Optional können Sie Software-RAID aktivieren, wenn Sie eine Premium-Lizenz verwenden.

. Wenn das Cluster über vier oder mehr Nodes verfügt, müssen Sie die Nodes in den zusätzlichen HA-Paaren konfigurieren. Befolgen Sie dazu die gleichen Schritte, die für das erste HA-Paar verwendet werden.
. Klicken Sie auf *Fertig* und prüfen Sie die Konfiguration des Clusters.
+
Sie können die Konfiguration ändern, indem Sie in jedem Abschnitt auf *Bearbeiten* klicken.

. Führen Sie optional den Netzwerk-Konnektivitätsprüfer aus, um die Konnektivität zwischen den Knoten im internen Clusternetzwerk zu testen.
. Klicken Sie Auf *Weiter*.
. Geben Sie das ONTAP Administrator-Passwort ein und klicken Sie auf *Cluster erstellen*, um den Cluster-Erstellungsprozess zu starten, und klicken Sie dann im Bestätigungsfenster auf *OK*.
+
Es kann bis zu 30 Minuten dauern, bis der Cluster erstellt wurde.

. Aktualisieren Sie die Seite, und wählen Sie den neuen Cluster aus. Klicken Sie dann auf *Zusammenfassung* und *Details*, um den mehrstufigen Cluster-Erstellungsprozess zu überwachen.
+

TIP: Wenn der Vorgang zum Erstellen des Clusters initiiert, aber nicht abgeschlossen wird, ist das von Ihnen definierte ONTAP-Administratorpasswort nicht registriert. In diesem Fall können Sie mit dem Passwort auf die Managementoberfläche für das ONTAP Select-Cluster zugreifen `changeme123` Mit dem `admin` Konto.



.Nachdem Sie fertig sind
* Vergewissern Sie sich, dass die ONTAP Select AutoSupport-Funktion aktiviert ist.
* Sichern Sie die Konfigurationsdaten für ONTAP Select Deploy.

