---
sidebar: sidebar 
permalink: task_vpi_adm_licenses.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, licenses, licensing 
summary: Bei der Administration der ONTAP Select-Lizenzen können Sie mehrere verwandte Aufgaben ausführen. 
---
= ONTAP Select-Lizenzen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bei der Administration der ONTAP Select-Lizenzen können Sie mehrere verwandte Aufgaben ausführen.



== Lizenzen verwalten

Lizenzen für ONTAP Select Capacity Tiers können nach Bedarf hinzugefügt, bearbeitet und gelöscht werden.

.Schritte
. Klicken Sie im Fenster *Globale Inventarlisten* auf *ONTAP Select bereitstellen*.
. Klicken Sie auf die Registerkarte *Administration*.
. Erweitern Sie die Option *Licenses* und klicken Sie entweder auf *Capacity Tier* oder *Capacity Pool*, um den Lizenztyp auszuwählen.
+
Die aktuellen Lizenzen und alle Probleme werden angezeigt.

. Klicken Sie optional auf *Filtern* und erstellen Sie einen Filter, um die angezeigten Lizenzen einzuschränken.
. Führen Sie die gewünschte Aufgabe aus:
+
.. Klicken Sie zum Hinzufügen einer Lizenz auf *+ADD*, klicken Sie auf *Lizenz(en) hochladen* und wählen Sie eine Lizenzdatei aus.
.. Um eine vorhandene Lizenz zu löschen, klicken Sie rechts neben der Lizenz auf das Papierkorb-Symbol.



