---
sidebar: sidebar 
permalink: task_cli_deploy_cluster.html 
keywords: administer, administering, cli, create cluster, deploy cluster 
summary: Über die mit dem ONTAP Select Deploy Administration Utility bereitgestellte Befehlszeilenschnittstelle können Sie ein Single Node oder Multi-Node ONTAP Select Cluster erstellen. 
---
= Implementieren Sie ein ONTAP Select-Cluster über die CLI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Über die mit dem ONTAP Select Deploy Administration Utility bereitgestellte Befehlszeilenschnittstelle können Sie ein Single Node oder Multi-Node ONTAP Select Cluster erstellen.



== Schritt 1: Bereiten Sie die Bereitstellung vor

Bevor Sie ein ONTAP Select-Cluster auf einem Hypervisor erstellen, sollten Sie die erforderlichen Vorbereitungen kennen.

.Schritte
. Bereiten Sie das Verbinden des Speichers mit dem ONTAP Select-Node vor
+
[role="tabbed-block"]
====
.Hardware-RAID
--
Wenn Sie einen lokalen Hardware-RAID-Controller verwenden, müssen Sie mindestens einen Datenspeicher (ESX) oder einenlink:kvm-host-configuration-and-preparation-checklist.html#step-2-create-a-storage-pool["Speicherpool (KVM)"] an jedem Knoten für die Systemdaten sowie die Wurzel und die Datenaggregate. Sie müssen den Speicherpool im Rahmen der Konfiguration des ONTAP Select Knotens anhängen.

--
.Software-RAID
--
Wenn Sie Software-RAID verwenden, müssen Sie mindestens einen Datenspeicher (ESX) oder einenlink:kvm-host-configuration-and-preparation-checklist.html#step-2-create-a-storage-pool["Speicherpool (KVM)"] für die Systemdaten und stellen Sie sicher, dass die SSD-Laufwerke für das Stammverzeichnis und die Datenaggregate verfügbar sind. Sie müssen den Speicherpool und die Festplatten im Rahmen der Konfiguration des ONTAP Select Knotens anhängen.

--
====
. Verfügbare ONTAP Select-Versionen
+
Das Deploy Administration Utility enthält eine einzige Version von ONTAP Select. Wenn Sie Cluster mit einer früheren Version von ONTAP Select bereitstellen möchten, müssen Sie zunächst link:task_cli_deploy_image_add.html["Fügen Sie das ONTAP Select Image hinzu"] zu Ihrer Deploy-Instanz.

. Lizenzieren Sie ONTAP Select für eine Produktionsbereitstellung
+
Bevor Sie ein ONTAP Select Cluster in einer Produktionsumgebung implementieren, müssen Sie eine Storage-Kapazitätslizenz erwerben und die zugehörige Lizenzdatei herunterladen. Du kannst link:concept_lic_production.html["Lizenzieren Sie den Speicher an jedem Knoten"] mithilfe des _Capacity Tiers_-Modells oder lizenzieren Sie einen gemeinsam genutzten Pool mithilfe des _Capacity Pools_-Modells.





== Schritt 2: Hochladen und Registrieren einer Lizenzdatei

Nachdem Sie eine Lizenzdatei mit Speicherkapazität erworben haben, müssen Sie die Datei mit der Lizenz auf die virtuelle Maschine bereitstellen und registrieren.


NOTE: Wenn Sie nur einen Cluster zur Evaluierung implementieren, können Sie diesen Schritt überspringen.

.Bevor Sie beginnen
Sie müssen das Passwort für das Admin-Benutzerkonto besitzen.

.Schritte
. Verwenden Sie in einer Command Shell auf Ihrer lokalen Arbeitsstation das sftp-Dienstprogramm, um die Lizenzdatei auf die virtuelle Maschine bereitstellen hochzuladen.
+
Beispielausgabe

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put NLF-320000nnn.txt
exit
....
. Melden Sie sich über SSH bei der CLI des Deploy Utility mit dem Administratorkonto an.
. Registrieren Sie die Lizenz:
+
[source, cli]
----
license add -file-name <file_name>
----
+
Geben Sie bei der entsprechenden Aufforderung das Kennwort für das Administratorkonto an.

. Zeigen Sie die Lizenzen im System an, um zu bestätigen, dass die Lizenz ordnungsgemäß hinzugefügt wurde:
+
[source, cli]
----
license show
----




== Schritt 3: Hypervisor-Hosts hinzufügen

Sie müssen jeden Hypervisor-Host registrieren, auf dem ein ONTAP Select-Node ausgeführt wird.

[role="tabbed-block"]
====
.KVM
--
Sie müssen einen Hypervisor-Host registrieren, auf dem der ONTAP Select-Node ausgeführt wird. Im Rahmen dieser Authentifizierung authentifiziert sich das Dienstprogramm Deploy Administration beim KVM-Host.

.Über diese Aufgabe
Wenn mehr als ein Hypervisor-Host benötigt wird, verwenden Sie dieses Verfahren, um jeden Host hinzuzufügen.

.Schritte
. Melden Sie sich in der CLI des Bereitstellungsdienstprogramms mithilfe von SSH mit dem Administratorkonto an.
. Registrieren des Hosts:
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type KVM -username <KVM_username>
----
+
Beispielausgabe

+
[listing]
----
host register -name 10.234.81.14 -hypervisor-type KVM -username root
----
+
Geben Sie das Passwort für das Hostkonto an, wenn Sie dazu aufgefordert werden.

. Zeigen Sie den Status des Hosts an und bestätigen Sie, dass er authentifiziert ist:
+
[source, cli]
----
host show -name <FQDN|IP> -detailed
----
+
Beispielausgabe

+
[listing]
----
host show -name 10.234.81.14 -detailed
----


--
.ESXi
--
In diesem Rahmen authentifiziert das Deploy-Administration-Utility entweder auf dem vCenter-Server, der den Host verwaltet, oder direkt auf dem ESXi-Standalone-Host.

.Über diese Aufgabe
Bevor Sie einen von vCenter verwalteten Host registrieren, müssen Sie ein Management-Server-Konto für den vCenter-Server hinzufügen. Wenn der Host nicht von vCenter gemanagt wird, können Sie die Hostanmeldeinformationen im Rahmen der Registrierung des Hosts angeben. Verwenden Sie dieses Verfahren, um jeden Host hinzuzufügen.

.Schritte
. Melden Sie sich in der CLI des Bereitstellungsdienstprogramms mithilfe von SSH mit dem Administratorkonto an.
. Wenn der Host von einem vCenter-Server gemanagt wird, fügen Sie die Anmeldeinformationen für das vCenter-Konto hinzu:
+
[source, cli]
----
credential add -hostname <FQDN|IP> -type vcenter -username <vcenter_username>
----
+
Beispielausgabe

+
....
credential add -hostname vc.select.company-demo.com -type vcenter -username administrator@vsphere.local
....
. Registrieren des Hosts:
+
** Registrieren eines eigenständigen Hosts, der nicht von vCenter gemanagt wird:
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type ESX -username <esx_username>
----
** Registrieren eines von vCenter gemanagten Hosts:
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type ESX -mgmt-server <FQDN|IP>
----
+
Beispielausgabe

+
....
host register -name 10.234.81.14 -hypervisor-type ESX -mgmt-server vc.select.company-demo.com
....


. Zeigen Sie den Status des Hosts an und bestätigen Sie, dass er authentifiziert ist.
+
[source, cli]
----
host show -name <FQDN|IP> -detailed
----
+
Beispielausgabe

+
....
host show -name 10.234.81.14 -detailed
....


--
====


== Schritt 4: Erstellen und Konfigurieren eines ONTAP Select Clusters

Sie müssen den ONTAP Select-Cluster erstellen und dann konfigurieren. Nach der Konfiguration des Clusters können Sie die einzelnen Nodes konfigurieren.

.Bevor Sie beginnen
Entscheiden Sie, wie viele Knoten der Cluster enthält, und legen Sie die zugehörigen Konfigurationsinformationen bereit.

.Über diese Aufgabe
Wenn Sie ein ONTAP Select-Cluster erstellen, generiert das Deploy-Dienstprogramm basierend auf dem von Ihnen angegeben Cluster-Namen und der Anzahl der Nodes automatisch die Node-Namen. Die Implementierung generiert auch die eindeutige Node-IDs.

.Schritte
. Melden Sie sich in der CLI des Bereitstellungsdienstprogramms mithilfe von SSH mit dem Administratorkonto an.
. Erstellen des Clusters:
+
[source, cli]
----
cluster create -name <cluster_name> -node-count <count>
----
+
Beispielausgabe

+
....
cluster create -name test-cluster -node-count 1
....
. Konfigurieren des Clusters:
+
[source, cli]
----
cluster modify -name <cluster_name> -mgmt-ip <IP_address> -netmask <netmask> -gateway <IP_address> -dns-servers <FQDN|IP>_LIST -dns-domains <domain_list>
----
+
Beispielausgabe

+
....
cluster modify -name test-cluster -mgmt-ip 10.234.81.20 -netmask 255.255.255.192
-gateway 10.234.81.1 -dns-servers 10.221.220.10 -dnsdomains select.company-demo.com
....
. Anzeigen der Konfiguration und des Status des Clusters:
+
[source, cli]
----
cluster show -name <cluster_name> -detailed
----




== Schritt 5: Konfigurieren eines ONTAP Select Knotens

Sie müssen jeden der Nodes im ONTAP Select-Cluster konfigurieren.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Sie über die Konfigurationsinformationen für den Knoten verfügen.
* Überprüfen Sie, ob die Lizenzdatei für die Kapazitätsstufe oder den Kapazitätspool hochgeladen und im Bereitstellungsprogramm installiert wurde.


.Über diese Aufgabe
Sie sollten diese Vorgehensweise zum Konfigurieren der einzelnen Knoten verwenden. In diesem Beispiel wird eine Capacity Tier-Lizenz auf den Node angewendet.

.Schritte
. Melden Sie sich in der CLI des Bereitstellungsdienstprogramms mithilfe von SSH mit dem Administratorkonto an.
. Legen Sie die Namen fest, die den Cluster-Nodes zugewiesen sind:
+
[source, cli]
----
node show -cluster-name <cluster_name>
----
. Wählen Sie den Knoten aus und führen Sie eine Basiskonfiguration durch:
+
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -host-name <FQDN|IP> -license-serial-number <number> -instance-type TYPE -passthrough-disks false
----
+
Beispielausgabe

+
....
node modify -name test-cluster-01 -cluster-name test-cluster -host-name 10.234.81.14
-license-serial-number 320000nnnn -instance-type small -passthrough-disks false
....
+
Die RAID-Konfiguration für den Knoten wird mit dem Parameter _Passthrough-Disks_ angezeigt. Wenn Sie einen lokalen Hardware-RAID-Controller verwenden, muss dieser Wert „false“ sein. Wenn Sie Software-RAID verwenden, muss dieser Wert „true“ sein.

+
Für den ONTAP Select Node wird eine Capacity Tier Lizenz verwendet.

. Zeigen Sie die am Host verfügbare Netzwerkkonfiguration an:
+
[source, cli]
----
host network show -host-name <FQDN|IP> -detailed
----
+
Beispielausgabe

+
....
host network show -host-name 10.234.81.14 -detailed
....
. Netzwerkkonfiguration für den Node durchführen:
+
[role="tabbed-block"]
====
.ESXi-Host
--
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -mgmt-ip IP -management-networks <network_name> -data-networks <network_name> -internal-network <network_name>
----
--
.KVM-Host
--
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -mgmt-ip IP -management-vlans <vlan_id> -data-vlans <vlan_id> -internal-vlans <vlad_id>
----
--
====
+
Wenn Sie einen Einzelknotencluster bereitstellen, benötigen Sie kein internes Netzwerk und sollten „-internal-network“ entfernen.

+
Beispielausgabe

+
....
node modify -name test-cluster-01 -cluster-name test-cluster -mgmt-ip 10.234.81.21
-management-networks sDOT_Network -data-networks sDOT_Network
....
. Anzeigen der Konfiguration des Knotens:
+
[source, cli]
----
node show -name <node_name> -cluster-name <cluster_name> -detailed
----
+
Beispielausgabe

+
....
node show -name test-cluster-01 -cluster-name test-cluster -detailed
....




== Schritt 6: Speicher an die ONTAP Select Knoten anhängen

Konfigurieren Sie den von jedem Knoten im ONTAP Select Cluster verwendeten Speicher. Jedem Node muss immer mindestens ein Storage-Pool zugewiesen werden. Bei der Verwendung von Software-RAID muss jedem Knoten auch mindestens ein Laufwerk zugewiesen werden.

.Bevor Sie beginnen
Erstellen Sie den Speicherpool mit VMware vSphere. Wenn Sie Software-RAID verwenden, benötigen Sie auch mindestens ein verfügbares Laufwerk.

.Über diese Aufgabe
Wenn Sie einen lokalen Hardware-RAID-Controller verwenden, müssen Sie die Schritte 1 bis 4 ausführen. Bei der Verwendung von Software-RAID müssen Sie die Schritte 1 bis 6 ausführen.

.Schritte
. Melden Sie sich in der CLI des Bereitstellungsdienstprogramms mithilfe von SSH mit den Anmeldedaten des Administratorkontos an.
. Anzeigen der am Host verfügbaren Speicherpools:
+
[source, cli]
----
host storage pool show -host-name <FQDN|IP>
----
+
Beispielausgabe

+
[listing]
----
host storage pool show -host-name 10.234.81.14
----
+
Über VMware vSphere erhalten Sie auch die verfügbaren Storage-Pools.

. Schließen Sie einen verfügbaren Speicherpool an den ONTAP Select-Node an:
+
[source, cli]
----
node storage pool attach -name <pool_name> -cluster-name <cluster_name> -node-name <node_name> -capacity-limit <limit>
----
+
Wenn Sie den Parameter „-capacity-limit“ einschließen, geben Sie den Wert als GB oder TB an.

+
Beispielausgabe

+
[listing]
----
node storage pool attach -name sDOT-02 -cluster-name test-cluster -
node-name test-cluster-01 -capacity-limit 500GB
----
. Anzeigen der mit dem Node verbundenen Speicherpools:
+
[source, cli]
----
node storage pool show -cluster-name <cluster_name> -node-name <node_name>
----
+
Beispielausgabe

+
[listing]
----
node storage pool show -cluster-name test-cluster -node-name testcluster-01
----
. Wenn Sie Software-RAID verwenden, verbinden Sie das verfügbare Laufwerk oder die verfügbaren Laufwerke:
+
[source, cli]
----
node storage disk attach -node-name <node_name> -cluster-name <cluster_name> -disks <list_of_drives>
----
+
Beispielausgabe

+
[listing]
----
node storage disk attach -node-name NVME_SN-01 -cluster-name NVME_SN -disks 0000:66:00.0 0000:67:00.0 0000:68:00.0
----
. Wenn Sie Software-RAID verwenden, zeigen Sie die mit dem Node verbundenen Festplatten an:
+
[source, cli]
----
node storage disk show -node-name <node_name> -cluster-name <cluster_name>`
----
+
Beispielausgabe

+
[listing]
----
node storage disk show -node-name sdot-smicro-009a -cluster-name NVME
----




== Schritt 7: Bereitstellen eines ONTAP Select Clusters

Nachdem das Cluster und die Nodes konfiguriert wurden, können Sie das Cluster implementieren.

.Bevor Sie beginnen
Führen Sie den Netzwerkkonnektivitätsprüfer mit dem link:task_adm_connectivity.html["Web-Benutzeroberfläche"] oder die link:task_cli_connectivity.html["CLI"] um die Konnektivität zwischen den Clusterknoten im internen Netzwerk zu bestätigen.

.Schritte
. Melden Sie sich in der CLI des Bereitstellungsdienstprogramms mithilfe von SSH mit dem Administratorkonto an.
. Implementierung des ONTAP Select-Clusters:
+
[source, cli]
----
cluster deploy -name <cluster_name>
----
+
Beispielausgabe

+
[listing]
----
cluster deploy -name test-cluster
----
+
Geben Sie das Kennwort ein, das für das ONTAP-Administratorkonto verwendet werden soll, wenn Sie dazu aufgefordert werden.

. Anzeigen des Status des Clusters, um zu bestimmen, wann es erfolgreich implementiert wurde:
+
[source, cli]
----
cluster show -name <cluster_name>
----


.Wie geht es weiter?
link:task_cli_clusters.html["Sichern Sie die ONTAP Select Deploy-Konfigurationsdaten."].
