---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: Sie können ein ONTAP Select-Image zu Ihrer Instanz des Deploy Administration Utility hinzufügen. Nach der Installation des Images können Sie es bei der Implementierung eines ONTAP Select-Clusters verwenden. 
---
= Fügen Sie ein ONTAP Select-Image zur Bereitstellung hinzu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können ein ONTAP Select-Image zu Ihrer Instanz des Deploy Administration Utility hinzufügen. Nach der Installation des Images können Sie es bei der Implementierung eines ONTAP Select-Clusters verwenden.



== Bevor Sie beginnen

Das Hinzufügen eines ONTAP Select Images zu einer Instanz der Bereitstellung besteht im Wesentlichen aus vier Schritten:

. Herunterladen des Installations-Images
. Hochladen des Installations-Images auf die virtuelle Maschine bereitstellen
. Hinzufügen des Installations-Images
. Anzeigen der verfügbaren Installationsabbilder


Bevor Sie neue ONTAP Select-Images zur Bereitstellung hinzufügen, sollten Sie zunächst alle nicht benötigten Bilder entfernen.


NOTE: Sie sollten nur ein ONTAP Select-Image mit einer Version hinzufügen, die vor der ursprünglichen Version liegt, die in Ihrer Instanz des Deploy-Dienstprogramms enthalten ist. Das Hinzufügen weiterer Versionen von ONTAP Select, da diese von NetApp verfügbar werden, wird von dieser Konfiguration nicht unterstützt.



== Laden Sie das Installations-Image herunter

Wenn Sie ein ONTAP Select Image zu einer Instanz des Deploy Utility hinzufügen möchten, müssen Sie das Installations-Image von der NetApp Support Website herunterladen. Das ONTAP Select Installations-Image ist als einzelne komprimierte Datei formatiert.

.Schritte
. Greifen Sie über einen Webbrowser auf die NetApp Support-Website zu und klicken Sie auf *Support Quick Links*.
. Klicken Sie unter *Top Tasks* auf *Software herunterladen* und melden Sie sich auf der Website an.
. Klicken Sie auf *Produkt finden*.
. Scrollen Sie nach unten und klicken Sie auf *ONTAP Select*.
. Klicken Sie unter *Other Available Select Software* auf *Deploy Upgrade, Node Upgrade, Image Install*.
. Wählen Sie die gewünschte Version des Aktualisierungspakets aus.
. Lesen Sie die Endbenutzer-Lizenzvereinbarung (EULA) durch und klicken Sie auf *Akzeptieren und fortfahren*.
. Wählen Sie das entsprechende Paket aus, und laden Sie es herunter. Gehen Sie dabei auf alle Eingabeaufforderungen für Ihre Umgebung ein.




== Laden Sie das Installations-Image zur Bereitstellung hoch

Nach dem Erfassen des ONTAP Select Installations-Images müssen Sie die Datei auf die virtuelle Maschine bereitstellen hochladen.

.Bevor Sie beginnen
Die Installations-Image-Datei muss auf Ihrer lokalen Arbeitsstation verfügbar sein. Sie müssen außerdem über das Kennwort für das Administratorkonto bereitstellen verfügen.

.Über diese Aufgabe
Diese Aufgabe beschreibt eine Methode zum Hochladen der Datei auf die virtuelle Maschine bereitstellen. Möglicherweise gibt es weitere für Ihre Umgebung geeignetere Optionen.

.Schritt
. Laden Sie die Bilddatei in einer Befehlsshell auf Ihrer lokalen Arbeitsstation auf die virtuelle Maschine bereitstellen hoch.
+
Beispiel

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
Beispiel

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Ergebnis
Die Knoten-Installationsdatei wird im Home-Verzeichnis des Admin-Benutzers gespeichert.



== Fügen Sie das Installationsabbild hinzu

Das ONTAP Select Installations-Image kann in das Verzeichnis Deploy Images hinzugefügt werden, damit es bei der Bereitstellung eines neuen Clusters verfügbar ist.

.Bevor Sie beginnen
Sie müssen wissen, in welchem Verzeichnis die Installations-Image-Datei in der virtuellen Maschine Deploy Utility abgelegt wurde. Es wird davon ausgegangen, dass sich die Datei im Home-Verzeichnis des Administrators befindet.

.Schritte
. Melden Sie sich mit SSH beim Deploy Utility CLI mit dem Administrator-Konto (admin) an.
. Starten Sie die Bash Shell:
+
`shell bash`

. Legen Sie die Installations-Image-Datei in das Bildverzeichnis.
+
Beispiel
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Zeigt die verfügbaren Installationsabbilder an

Sie können die ONTAP Select-Images anzeigen, die bei der Bereitstellung eines neuen Clusters verfügbar sind.

.Schritte
. Greifen Sie auf die Webseite für die Online-Dokumentation auf der virtuellen Maschine des Dienstprogramms bereitstellen zu, und melden Sie sich mit dem Administratorkonto an:
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Verwenden Sie den Domänennamen oder die IP-Adresse der virtuellen Maschine Bereitstellen.

. Navigieren Sie zum Ende der Seite und klicken Sie auf *Bereitstellen* und dann auf *GET /images*.
. Klicken Sie auf *Probieren Sie es aus!*, um die verfügbaren ONTAP Select-Bilder anzuzeigen.
. Stellen Sie sicher, dass das gewünschte Bild verfügbar ist.

