---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, Capacity Pools 
summary: Für jeden von den ONTAP Select-Nodes verwendeten Kapazitäts-Pool muss eine Lizenzdatei erworben werden. Die Lizenzdatei definiert die Speicherkapazität und den Ablauf des Pools. Sie ist für den License Manager gesperrt, indem sie eine Kombination aus der eindeutigen Lizenzseriennummer, die NetApp zugewiesen hat, und der mit der Deploy-Instanz verknüpften Lizenzsperre-ID verwenden. 
---
= Erwerben Sie eine ONTAP Select Capacity Pool-Lizenz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Für jeden von den ONTAP Select-Nodes verwendeten Kapazitäts-Pool muss eine Lizenzdatei erworben werden. Die Lizenzdatei definiert die Speicherkapazität und den Ablauf des Pools. Sie ist für den License Manager gesperrt, indem sie eine Kombination aus der eindeutigen Lizenzseriennummer, die NetApp zugewiesen hat, und der mit der Deploy-Instanz verknüpften Lizenzsperre-ID verwenden.

.Bevor Sie beginnen
* Sie benötigen die neunstellige Lizenzseriennummer, die dem Kapazitätspool von NetApp zugewiesen wurde.
* Sie sollten mindestens 24 Stunden nach dem Versanddatum Ihrer Bestellung warten, bevor Sie eine Lizenzdatei erwerben.
* Sie haben die link:sizing-capacity-pool-license.html["Überlegungen zur Dimensionierung einer Capacity Pools License"] überprüft.


.Über diese Aufgabe
Sie müssen diese Aufgabe für jeden von den ONTAP Select-Nodes verwendeten Kapazitätspool ausführen.

.Schritte
. Melden Sie sich bei der link:https://mysupport.netapp.com/site/["NetApp Support Website"^] an.
. Wählen Sie *Systems* > *Software Licenses*.
. Geben Sie die Lizenz-Seriennummer für den Capacity Pool ein und wählen Sie *Go!*.
. Navigieren Sie auf der Seite Lizenzdetails zur Spalte *Produktdetails*.
. Wählen Sie *Get NetApp License File* in der entsprechenden Zeile aus.
. Geben Sie die License Lock ID für Ihre ONTAP Select Deploy Instanz ein und wählen Sie *Submit*.
. Wählen Sie die entsprechende Zustellungsmethode aus und wählen Sie *Absenden*.
. Wählen Sie im Lieferbestätigungsfenster *OK* aus.


.Nachdem Sie fertig sind
Sie müssen die Lizenzdatei in das Deploy-Verwaltungsprogramm hochladen, bevor ein ONTAP Select Node den Kapazitätspool nutzen kann.
