---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, Capacity Pools 
summary: Für jeden von den ONTAP Select-Nodes verwendeten Kapazitäts-Pool muss eine Lizenzdatei erworben werden. Die Lizenzdatei definiert die Speicherkapazität und den Ablauf des Pools. Sie ist für den License Manager gesperrt, indem sie eine Kombination aus der eindeutigen Lizenzseriennummer, die NetApp zugewiesen hat, und der mit der Deploy-Instanz verknüpften Lizenzsperre-ID verwenden. 
---
= Erwerben Sie eine ONTAP Select Capacity Pool-Lizenz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Für jeden von den ONTAP Select-Nodes verwendeten Kapazitäts-Pool muss eine Lizenzdatei erworben werden. Die Lizenzdatei definiert die Speicherkapazität und den Ablauf des Pools. Sie ist für den License Manager gesperrt, indem sie eine Kombination aus der eindeutigen Lizenzseriennummer, die NetApp zugewiesen hat, und der mit der Deploy-Instanz verknüpften Lizenzsperre-ID verwenden.

.Bevor Sie beginnen
Dem Kapazitäts-Pool muss die neunstellige Lizenzseriennummer von NetApp zugewiesen werden. Bevor Sie versuchen, eine Lizenzdatei zu erwerben, sollten Sie mindestens 24 Stunden nach dem Versanddatum Ihrer Bestellung warten.

.Über diese Aufgabe
Sie müssen diese Aufgabe für jeden von den ONTAP Select-Nodes verwendeten Kapazitätspool ausführen.

.Schritte
. Greifen Sie über einen Webbrowser auf die NetApp Support-Website zu und melden Sie sich an.
. Klicken Sie oben auf *Systems* und dann auf *Software-Lizenzen*.
. Geben Sie die Lizenzseriennummer für den Kapazitäts-Pool ein und klicken Sie auf *Go!*.
. Navigieren Sie auf der Seite Lizenzdetails zur Spalte *Produktdetails*.
. Klicken Sie in der entsprechenden Zeile auf *NetApp Lizenzdatei erhalten*.
. Geben Sie die Lizenzsperre-ID für Ihre ONTAP Select-Deploy-Instanz ein, und klicken Sie auf *Submit*.
. Wählen Sie die passende Liefermethode aus und klicken Sie auf *Absenden*.
. Klicken Sie im Bestätigungsfenster auf *OK*.


.Nachdem Sie fertig sind
Sie müssen die Lizenzdatei in das Dienstprogramm Deploy Administration hochladen, bevor der Kapazitäts-Pool von einem ONTAP Select-Node verwendet werden kann.
