---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: Fügen Sie ein ONTAP Select-Image zu Ihrer Instanz des Deploy-Verwaltungsprogramms hinzu. Nach der Installation können Sie es beim Bereitstellen eines ONTAP Select Clusters verwenden. 
---
= Fügen Sie ein ONTAP Select-Image zur Bereitstellung hinzu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Fügen Sie ein ONTAP Select-Image zu Ihrer Instanz des Deploy-Verwaltungsprogramms hinzu. Nach der Installation des Images können Sie es beim Bereitstellen eines ONTAP Select Clusters verwenden.

.Bevor Sie beginnen
Bevor Sie neue ONTAP Select-Images zur Bereitstellung hinzufügen, sollten Sie zunächst alle nicht benötigten Bilder entfernen.


NOTE: Sie sollten nur ein ONTAP Select-Image mit einer Version hinzufügen, die vor der ursprünglichen Version liegt, die in Ihrer Instanz des Deploy-Dienstprogramms enthalten ist. Das Hinzufügen weiterer Versionen von ONTAP Select, da diese von NetApp verfügbar werden, wird von dieser Konfiguration nicht unterstützt.



== Schritt 1: Installationsabbild herunterladen

Wenn Sie ein ONTAP Select Image zu einer Instanz des Deploy Utility hinzufügen möchten, müssen Sie das Installations-Image von der NetApp Support Website herunterladen. Das ONTAP Select Installations-Image ist als einzelne komprimierte Datei formatiert.

.Schritte
. Rufen Sie die link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site Downloads"^] Seite auf.
. Scrollen Sie nach unten und wählen Sie *ONTAP Select Image* aus.
. Wählen Sie die gewünschte Version des Installationsabbilds aus.
. Lesen Sie die Endbenutzer-Lizenzvereinbarung (EULA), und wählen Sie *Accept & Continue* aus.
. Wählen Sie das passende *ONTAP Select Image Install*-Paket aus und laden Sie es herunter. Beantworten Sie alle erforderlichen Eingabeaufforderungen.




== Schritt 2: Laden Sie das Installationsabbild in Deploy hoch.

Nach dem Erfassen des ONTAP Select Installations-Images müssen Sie die Datei auf die virtuelle Maschine bereitstellen hochladen.

.Bevor Sie beginnen
Vergewissern Sie sich, dass die Installationsabbilddatei auf Ihrem lokalen Rechner verfügbar ist. Sie müssen außerdem das Kennwort für das Deploy-Administratorkonto haben.

.Über diese Aufgabe
Diese Aufgabe beschreibt eine Methode zum Hochladen der Datei auf die virtuelle Maschine bereitstellen. Möglicherweise gibt es weitere für Ihre Umgebung geeignetere Optionen.

.Schritt
. Laden Sie die Image-Datei in einer Befehlsshell auf Ihrer lokalen Workstation auf die virtuelle Maschine „Deploy“ hoch, wie in den folgenden Beispielen gezeigt:
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Ergebnis
Die Knoten-Installationsdatei wird im Home-Verzeichnis des Admin-Benutzers gespeichert.



== Schritt 3: Installationsabbild hinzufügen

Fügen Sie das ONTAP Select Installationsabbild dem Verzeichnis „Deploy images“ hinzu, damit es bei der Bereitstellung eines neuen Clusters verfügbar ist.

.Bevor Sie beginnen
Sie müssen wissen, in welchem Verzeichnis die Installations-Image-Datei in der virtuellen Maschine Deploy Utility abgelegt wurde. Es wird davon ausgegangen, dass sich die Datei im Home-Verzeichnis des Administrators befindet.

.Schritte
. Melden Sie sich mit SSH beim Deploy Utility CLI mit dem Administrator-Konto (admin) an.
. Starten Sie die Bash Shell:
+
[source, cli]
----
shell bash
----
. Platzieren Sie die Installationsabbilddatei im Verzeichnis „images“, wie im folgenden Beispiel gezeigt:
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Schritt 4: Verfügbare Installationsabbilder anzeigen

Zeigen Sie die ONTAP Select -Images an, die beim Bereitstellen eines neuen Clusters verfügbar sind.

.Schritte
. Greifen Sie auf die Webseite für die Online-Dokumentation auf der virtuellen Maschine des Dienstprogramms bereitstellen zu, und melden Sie sich mit dem Administratorkonto an:
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Verwenden Sie den Domänennamen oder die IP-Adresse der virtuellen Maschine Bereitstellen.

. Scrollen Sie zum Ende der Seite und wählen Sie *Deploy* und anschließend *GET /images*.
. Wählen Sie *Ausprobieren!*, um die verfügbaren ONTAP Select -Bilder anzuzeigen.
. Stellen Sie sicher, dass das gewünschte Bild verfügbar ist.

