---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: Ab ONTAP Select 9.15.1 können Sie die Größe eines bestehenden Clusters erhöhen oder verringern. 
---
= Erweitern oder verkleinern Sie einen ONTAP Select Cluster auf einem ESXi- oder KVM-Host.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vergrößern oder verkleinern Sie die Clustergröße eines bestehenden ONTAP Select Clusters für ESXi- und KVM-Hypervisor-Hosts.  Bei beiden Hosttypen kann die Clustergröße in Schritten zwischen vier und zwölf Knoten erhöht oder verringert werden.

Die folgenden Clustererweiterungen und -kontraktionen werden für ESXi- und KVM-Hosts nicht unterstützt:

* Erweiterungen von Clustern mit einem oder zwei Knoten auf Cluster mit sechs, acht, zehn oder zwölf Knoten.
* Kontraktionen von Clustern mit sechs, acht, zehn oder zwölf Knoten auf Cluster mit einem oder zwei Knoten.


[NOTE]
====
Um die Anzahl der Knoten in einem Cluster auf eine Größe zu ändern, die durch die Erweiterung oder Verkleinerung des Clusters nicht unterstützt wird, müssen Sie die folgenden Aufgaben ausführen:

. Stellen Sie einen neuen Multi-Node-Cluster bereit, indem Sie den link:task_cli_deploy_cluster.html["CLI"] oder die link:task_deploy_cluster.html["Web-Benutzeroberfläche"] wird mit dem Verwaltungsdienstprogramm ONTAP Select Deploy bereitgestellt.
. Migrieren Sie die Daten gegebenenfalls in den neuen Cluster, indem Sie link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["SnapMirror Replizierung"^] .


====
Sie initiieren die Verfahren zur Clustererweiterung und -kontraktion von ONTAP Select Deploy über die CLI, API oder Weboberfläche.



== Überlegungen zu Hardware und Storage

Die Funktion zur Clustererweiterung und -kontraktion wird auf den folgenden KVM- und ESXi-Hypervisor-Hosts unterstützt.

[role="tabbed-block"]
====
.ESXi
--
Ab ONTAP Select 9.15.1 wird die Clustererweiterung und -kontraktion auf ESXi-Hypervisor-Hosts unterstützt.

Die Clustererweiterung und -kontraktion wird für die folgenden ESXi-Hypervisor-Versionen unterstützt:

* ESXi 9.0
* ESXi 8.0 U3
* ESXi 8.0 U2
* ESXi 8.0 U1
* ESXi 8.0GA


--
.KVM
--
Ab ONTAP Select 9.17.1 wird die Clustererweiterung und -kontraktion auf KVM-Hypervisor-Hosts unterstützt.

Die Clustererweiterung und -kontraktion wird für die folgenden KVM-Hypervisor-Versionen unterstützt:

* Red Hat Enterprise Linux (RHEL) 64-Bit 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 und 8.6
* Rocky Linux 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 und 8.6


[NOTE]
====
Für KVM-Hypervisoren auf RHEL 10.0- und Rocky Linux 10.0-Hosts gibt es Einschränkungen im Software-RAID-Workflow. Weitere Informationen finden Sie in den folgenden Artikeln unserer Wissensdatenbank:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: Warnmeldung beim Erstellen der Cluster-Hardware unter Verwendung von RHEL 10 und ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: Speicherpools und Speicherdatenträger werden für SWR auf der Seite zur Clustererstellung auf Hosts mit RHEL10/Rocky 10 nicht angezeigt."^]


====
--
====


== Erweitern Sie das Cluster

Verwenden Sie die Cluster-Erweiterungsfunktion, um die Größe eines vorhandenen ONTAP Select Clusters zu erhöhen.

Sie können die Größe eines bestehenden Clusters auf einem ESXi- oder KVM-Host in folgenden Schritten erhöhen:

* Von vier Knoten auf sechs, acht, zehn oder zwölf Knoten
* Von sechs Knoten auf acht, zehn oder zwölf Knoten
* Von acht Knoten auf zehn oder zwölf Knoten
* Von zehn auf zwölf Knoten


.Über diese Aufgabe
Zur Vorbereitung der Clustererweiterung werden neue ESXi- und KVM-Hosts in das Inventar aufgenommen und die Details der neuen Knoten zugewiesen. Vor dem Start der Clustererweiterung wird das ausgewählte interne Netzwerk durch eine Netzwerkvorprüfung überprüft.

.Bevor Sie beginnen
* Wenn Sie einen Cluster mit mehreren Knoten bereitstellen, sollten Sie mit der Netzwerkkonnektivitätsprüfung vertraut sein. Sie können die Netzwerkkonnektivitätsprüfung mithilfe des link:task_adm_connectivity.html["Web-Benutzeroberfläche"] oder die link:task_cli_connectivity.html["CLI"] .
* Vergewissern Sie sich, dass Sie über die Lizenzdetails für die neuen Nodes verfügen.


.Schritte
. Melden Sie sich über das Administratorkonto bei der Webbenutzeroberfläche des Deploy Utility an.
. Wählen Sie oben auf der Seite die Registerkarte *Cluster* aus und wählen Sie den gewünschten Cluster aus der Liste aus.
. Wählen Sie auf der Seite Cluster Details das Zahnradsymbol rechts auf der Seite aus und wählen Sie *Cluster erweitern*.
. Navigieren Sie zum Abschnitt *HA Pair 4*.
. Wählen Sie die folgenden Konfigurationsdetails für Hochverfügbarkeitspaare (HA) für das vierte HA-Paar:
+
** Instanztyp
** Node-Namen
** Zugeordnete Hypervisor-Hosts
** Node-IP-Adressen
** Lizenzen Zu Haben
** Netzwerkkonfiguration
** Speicherkonfiguration (RAID-Typ und Speicherpools)


. Wählen Sie *HA-Paar speichern*, um die Konfigurationsdetails zu speichern.
. Geben Sie die ONTAP -Anmeldeinformationen ein und wählen Sie *Cluster erweitern*.
. Wählen Sie *Weiter* und führen Sie die Netzwerkvorprüfung durch, indem Sie *Ausführen* auswählen.
+
Durch die Netzwerkprüfung wird überprüft, ob das für den ONTAP-Cluster-Datenverkehr ausgewählte interne Netzwerk ordnungsgemäß funktioniert.

. Wählen Sie *Expand Cluster* aus, um den Cluster-Erweiterungsprozess zu starten, und wählen Sie dann im Dialogfeld *OK* aus.
+
Die Erweiterung des Clusters kann bis zu 45 Minuten dauern.

. Überwachen Sie den mehrstufigen Cluster-Erweiterungsprozess, um zu bestätigen, dass das Cluster erfolgreich erweitert wurde.
. Auf der Registerkarte *Ereignisse* finden Sie regelmäßige Aktualisierungen zum Fortschritt des Vorgangs. Die Seite wird in regelmäßigen Abständen automatisch aktualisiert.


.Nachdem Sie fertig sind
Nach der Erweiterung des Clusters sollten Sie Folgendes beachten:link:task_cli_clusters.html["Sichern Sie die ONTAP Select Deploy-Konfigurationsdaten"] Die



== Vertrag mit dem Cluster abschließen

Verwenden Sie die Clusterverkleinerungsfunktion, um die Größe eines bestehenden ONTAP Select Clusters zu verringern.

Sie können die Größe eines bestehenden Clusters auf einem ESXi- oder KVM-Host in folgenden Schritten verringern:

* Von zwölf Knoten auf zehn, acht, sechs oder vier Knoten
* Von zehn Knoten auf acht, sechs oder vier Knoten
* Von acht auf sechs oder vier Knoten
* Von sechs auf vier Knoten


.Über diese Aufgabe
Das gewünschte HA-Paar von Nodes im Cluster wird ausgewählt, um die Cluster-Kontraktion während des Verfahrens vorzubereiten.

.Schritte
. Melden Sie sich über das Administratorkonto bei der Webbenutzeroberfläche des Deploy Utility an.
. Wählen Sie oben auf der Seite die Registerkarte *Cluster* aus und wählen Sie den gewünschten Cluster aus der Liste aus.
. Wählen Sie auf der Seite Cluster Details das Zahnradsymbol rechts auf der Seite aus, und wählen Sie dann *Contract Cluster*.
. Wählen Sie die HA-Paar-Konfigurationsdetails für jedes HA-Paar aus, das Sie entfernen möchten, und geben Sie die ONTAP-Anmeldeinformationen ein. Wählen Sie dann *Contract Cluster*.
+
Es kann bis zu 30 Minuten dauern, bis der Cluster komprimiert wurde.

. Überwachen Sie den mehrstufigen Cluster-Kontraktionsprozess, um zu bestätigen, dass der Cluster erfolgreich abgeschlossen wurde.
. Auf der Registerkarte *Ereignisse* finden Sie regelmäßige Aktualisierungen zum Fortschritt des Vorgangs. Die Seite wird in regelmäßigen Abständen automatisch aktualisiert.

