---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: Sie können ein ONTAP Select-Image zu Ihrer Instanz des Deploy Administration Utility hinzufügen. Nach der Installation des Images können Sie es bei der Implementierung eines ONTAP Select-Clusters verwenden. 
---
= Fügen Sie ein ONTAP Select-Image zur Bereitstellung hinzu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können ein ONTAP Select-Image zu Ihrer Instanz des Deploy Administration Utility hinzufügen. Nach der Installation des Images können Sie es bei der Implementierung eines ONTAP Select-Clusters verwenden.

.Bevor Sie beginnen
Bevor Sie neue ONTAP Select-Images zur Bereitstellung hinzufügen, sollten Sie zunächst alle nicht benötigten Bilder entfernen.


NOTE: Sie sollten nur ein ONTAP Select-Image mit einer Version hinzufügen, die vor der ursprünglichen Version liegt, die in Ihrer Instanz des Deploy-Dienstprogramms enthalten ist. Das Hinzufügen weiterer Versionen von ONTAP Select, da diese von NetApp verfügbar werden, wird von dieser Konfiguration nicht unterstützt.



== Schritt 1: Installationsabbild herunterladen

Wenn Sie ein ONTAP Select Image zu einer Instanz des Deploy Utility hinzufügen möchten, müssen Sie das Installations-Image von der NetApp Support Website herunterladen. Das ONTAP Select Installations-Image ist als einzelne komprimierte Datei formatiert.

.Schritte
. Rufen Sie die NetApp -Supportseite über einen Webbrowser auf und wählen Sie *Support-Schnelllinks*.
. Wählen Sie unter *Top-Aufgaben* die Option *Software herunterladen* und melden Sie sich auf der Website an.
. Wählen Sie *Produkt finden*.
. Scrollen Sie nach unten und wählen Sie *ONTAP Select*.
. Unter *Andere verfügbare Software auswählen* wählen Sie *Upgrade bereitstellen, Knoten-Upgrade, Image installieren*.
. Wählen Sie die gewünschte Version des Aktualisierungspakets aus.
. Lesen Sie die Endbenutzer-Lizenzvereinbarung (EULA) durch und klicken Sie auf *Akzeptieren und fortfahren*.
. Wählen Sie das entsprechende Paket aus, und laden Sie es herunter. Gehen Sie dabei auf alle Eingabeaufforderungen für Ihre Umgebung ein.




== Schritt 2: Laden Sie das Installationsabbild in Deploy hoch.

Nach dem Erfassen des ONTAP Select Installations-Images müssen Sie die Datei auf die virtuelle Maschine bereitstellen hochladen.

.Bevor Sie beginnen
Die Installations-Image-Datei muss auf Ihrer lokalen Arbeitsstation verfügbar sein. Sie müssen außerdem über das Kennwort für das Administratorkonto bereitstellen verfügen.

.Über diese Aufgabe
Diese Aufgabe beschreibt eine Methode zum Hochladen der Datei auf die virtuelle Maschine bereitstellen. Möglicherweise gibt es weitere für Ihre Umgebung geeignetere Optionen.

.Schritt
. Laden Sie die Image-Datei in einer Befehlsshell auf Ihrer lokalen Workstation auf die virtuelle Maschine „Deploy“ hoch, wie in den folgenden Beispielen gezeigt:
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Ergebnis
Die Knoten-Installationsdatei wird im Home-Verzeichnis des Admin-Benutzers gespeichert.



== Schritt 3: Installationsabbild hinzufügen

Fügen Sie das ONTAP Select Installationsabbild dem Verzeichnis „Deploy images“ hinzu, damit es bei der Bereitstellung eines neuen Clusters verfügbar ist.

.Bevor Sie beginnen
Sie müssen wissen, in welchem Verzeichnis die Installations-Image-Datei in der virtuellen Maschine Deploy Utility abgelegt wurde. Es wird davon ausgegangen, dass sich die Datei im Home-Verzeichnis des Administrators befindet.

.Schritte
. Melden Sie sich mit SSH beim Deploy Utility CLI mit dem Administrator-Konto (admin) an.
. Starten Sie die Bash Shell:


[listing]
----
shell bash
----
. Platzieren Sie die Installationsabbilddatei im Verzeichnis „images“, wie im folgenden Beispiel gezeigt:
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Schritt 4: Verfügbare Installationsabbilder anzeigen

Zeigen Sie die ONTAP Select -Images an, die beim Bereitstellen eines neuen Clusters verfügbar sind.

.Schritte
. Greifen Sie auf die Webseite für die Online-Dokumentation auf der virtuellen Maschine des Dienstprogramms bereitstellen zu, und melden Sie sich mit dem Administratorkonto an:
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Verwenden Sie den Domänennamen oder die IP-Adresse der virtuellen Maschine Bereitstellen.

. Scrollen Sie zum Ende der Seite und wählen Sie *Deploy* und anschließend *GET /images*.
. Wählen Sie *Ausprobieren!*, um die verfügbaren ONTAP Select -Bilder anzuzeigen.
. Stellen Sie sicher, dass das gewünschte Bild verfügbar ist.

