---
sidebar: sidebar 
permalink: task_vpi_adm_clusters.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, clusters 
summary: Es gibt verschiedene zugehörige Aufgaben, die Sie zum Verwalten eines ONTAP Select Clusters durchführen können. 
---
= ONTAP Select Cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es gibt verschiedene zugehörige Aufgaben, die Sie zum Verwalten eines ONTAP Select Clusters durchführen können.



== Verschieben Sie ein ONTAP Select Cluster in den Status „Offline“ und „Online“

Nachdem Sie ein Cluster erstellt haben, können Sie dessen Status bei Bedarf in „Offline“ oder „Online“ ändern.

.Schritte
. Klicken Sie im Fenster *Globale Inventarlisten* auf *ONTAP Select Cluster*.
. Klicken Sie mit der rechten Maustaste auf das gewünschte Cluster, um die verfügbaren Aktionen anzuzeigen.
. Klicken Sie auf *Offline nehmen* oder *Online mitbringen* und klicken Sie zur Bestätigung der Anfrage auf *Ja*.




== Löschen eines ONTAP Select-Clusters

Sie können ein ONTAP Select Cluster löschen, wenn er nicht mehr benötigt wird.

.Bevor Sie beginnen
Der Cluster muss sich im Offlinezustand befinden.

.Schritte
. Klicken Sie im Fenster *Globale Inventarlisten* auf *ONTAP Select Cluster*.
. Klicken Sie mit der rechten Maustaste auf das gewünschte Cluster, um die verfügbaren Aktionen anzuzeigen.
. Klicken Sie auf *Cluster löschen* und klicken Sie auf *Ja*, um die Anfrage zu bestätigen.
+
Wenn die Option zum Löschen nicht verfügbar ist, befindet sich das Cluster nicht in einem Offline-Zustand.


