---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: Ab ONTAP Select 9.15.1 können Sie die Größe eines vorhandenen Clusters von sechs auf acht Nodes erhöhen und die Clustergröße von acht auf sechs Nodes verringern. 
---
= Erweitern oder verkleinern Sie das Cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ab ONTAP Select 9.15.1 können Sie die Größe eines vorhandenen Clusters von sechs auf acht Nodes erhöhen und die Clustergröße von acht auf sechs Nodes verringern. Es werden keine anderen Cluster-Erweiterungs- oder -Kontraktionsszenarien unterstützt.

Das Verfahren wird über ONTAP Select Deploy über die CLI, API oder Webschnittstelle gestartet.



== Überlegungen zu Hardware und Storage

Die Funktionen zur Cluster-Erweiterung und -Verkleinerung sind wie folgt eingeschränkt:

* Die Unterstützung ist auf auf auf ESX Hypervisor-Hosts erstellte Cluster beschränkt. Die folgenden ESX-Versionen sind mit ONTAP Select 9.15.1 kompatibel:
+
** ESXi 8.0U2
** ESXi 8.0U1
** ESXi 8.0GA
** ESXi 7.0U3
** ESXi 7.0




Die folgenden Cluster-Erweiterungen und -Kontraktionen werden derzeit nicht unterstützt:

* Erweiterungen von Clustern mit einem, zwei oder vier Nodes auf Cluster mit sechs oder acht Nodes
* Kontraktionen von Clustern mit sechs oder acht Knoten zu Clustern mit einem, zwei oder vier Knoten.




== Erweitern Sie das Cluster

Mit der Cluster-Erweiterungsfunktion können Sie die Größe eines vorhandenen Clusters von einem Cluster mit sechs Nodes auf ein Cluster mit acht Nodes erhöhen.

.Über diese Aufgabe
Zur Vorbereitung der Cluster-Erweiterung werden neue ESX-Hosts zur Bestandsaufnahme hinzugefügt und die Details zu den neuen Nodes zugewiesen. Vor dem Starten der Cluster-Erweiterung überprüft eine Netzwerkprüfung das ausgewählte interne Netzwerk.

.Bevor Sie beginnen
* Wenn Sie ein Cluster mit mehreren Nodes bereitstellen, sollten Sie mit dem vertraut sein link:https://docs.netapp.com/us-en/ontap-select/task_adm_connectivity.html["Prüfung der Netzwerkverbindung"].
* Vergewissern Sie sich, dass Sie über die Lizenzdetails für die neuen Nodes verfügen.


.Schritte
. Melden Sie sich über das Administratorkonto bei der Webbenutzeroberfläche des Deploy Utility an.
. Wählen Sie oben auf der Seite die Registerkarte *Cluster* aus und wählen Sie den gewünschten Cluster aus der Liste aus.
. Wählen Sie auf der Seite Cluster Details das Zahnradsymbol rechts auf der Seite aus und wählen Sie *Cluster erweitern*.
. Navigieren Sie zum Abschnitt *HA Pair 4*.
. Wählen Sie für das vierte HA-Paar die Konfigurationsdetails für Hochverfügbarkeit (HA-Paar) aus, darunter:
+
** Instanztyp
** Node-Namen
** Zugeordnete Hypervisor-Hosts
** Node-IP-Adressen
** Lizenzen Zu Haben
** Netzwerkkonfiguration
** Speicherkonfiguration (RAID-Typ und Speicherpools)


. Wählen Sie *HA-Paar speichern*, um die Konfigurationsdetails zu speichern.
. Geben Sie die ONTAP-Anmeldeinformationen ein, und wählen Sie dann *Cluster erweitern*.
. Wählen Sie *Weiter* und führen Sie die Netzwerkvorprüfung durch, indem Sie *Ausführen* auswählen.
+
Durch die Netzwerkprüfung wird überprüft, ob das für den ONTAP-Cluster-Datenverkehr ausgewählte interne Netzwerk ordnungsgemäß funktioniert.

. Wählen Sie *Expand Cluster* aus, um den Cluster-Erweiterungsprozess zu starten, und wählen Sie dann im Dialogfeld *OK* aus.
+
Die Erweiterung des Clusters kann bis zu 45 Minuten dauern.

. Überwachen Sie den mehrstufigen Cluster-Erweiterungsprozess, um zu bestätigen, dass das Cluster erfolgreich erweitert wurde.
. Auf der Registerkarte *Ereignisse* finden Sie regelmäßige Aktualisierungen zum Fortschritt des Vorgangs. Die Seite wird in regelmäßigen Abständen automatisch aktualisiert.


.Nachdem Sie fertig sind
Nach der Erweiterung des Clusters sollten Sie die Konfigurationsdaten von ONTAP Select Deploy sichern.



== Vertrag mit dem Cluster abschließen

Mit der Cluster-Kontraktionsfunktion können Sie die Größe eines vorhandenen Clusters von einem Cluster mit acht Nodes auf ein Cluster mit sechs Nodes verringern.

.Über diese Aufgabe
Das gewünschte HA-Paar von Nodes im Cluster wird ausgewählt, um die Cluster-Kontraktion während des Verfahrens vorzubereiten.

.Schritte
. Melden Sie sich über das Administratorkonto bei der Webbenutzeroberfläche des Deploy Utility an.
. Wählen Sie oben auf der Seite die Registerkarte *Cluster* aus und wählen Sie den gewünschten Cluster aus der Liste aus.
. Wählen Sie auf der Seite Cluster Details das Zahnradsymbol rechts auf der Seite aus, und wählen Sie dann *Contract Cluster*.
. Wählen Sie die HA-Paar-Konfigurationsdetails für jedes HA-Paar aus, das Sie entfernen möchten, und geben Sie die ONTAP-Anmeldeinformationen ein. Wählen Sie dann *Contract Cluster*.
+
Es kann bis zu 30 Minuten dauern, bis der Cluster komprimiert wurde.

. Überwachen Sie den mehrstufigen Cluster-Kontraktionsprozess, um zu bestätigen, dass der Cluster erfolgreich abgeschlossen wurde.
. Auf der Registerkarte *Ereignisse* finden Sie regelmäßige Aktualisierungen zum Fortschritt des Vorgangs. Die Seite wird in regelmäßigen Abständen automatisch aktualisiert.

